==== Agile and architecture

  Cockcroft quote


  When it
 comes to system implementation, the temptation to be
 fast, often under the nom de guerre of agile, can soften
 quality controls and threaten product usability, relia-
 bility, safety, and lifecycle cost. <<Malan2010>>


Re: "the code is documentation"

... for systems of sufficient scope and complexity
to warrant teams (of teams) working on (incremental)
implementation and evolution, the sheer mass of code
can make it hard to discover the essential structure from
bottom-up decisions made entirely through the medium
of code. <<Malan2010>>

===== The hubris of Agile
We don't always build. Software may be eating the world, but that doesn't mean everyone employs - or should employ - software developers.

Suppose you have a business product/value prop and you know that you will be assembling complex services/products produced by others? And these services overlap? You need a strategy? Who is it that analyzes these services and their capabilities, interfaces, non-functional characteristics, and makes a final recommendation as to how you are going to bring them all into one unified system?

Point back to sourcing chapter. (And forward ref from that chapter to architecture.) Open source, COTS, Cloud, in-house... the options are bewildering and take experience. A consistent evaluation approach is important (pref. under an economic framework Reinertsen/Hubbard)

===== A worked example of architecture cost of delay vs TLM


===== Avoiding the big batch of EA "cleanup" that never works
preparing along the way
understand inventories and dependencies - importance of Bezos mandate to the dependency question - if there is one battle you fight, make it that one -
the importance of documentation - speech to text, text analytics... image recognition... what might the future hold? At least get technical writers... don't make developers write...

If you started from day 1 with source, build, & package mgmt, and have kept it clean, you have a great asset

 is EA using the right tools? systems theory, semantics vs dynamics. Also, IT finance typically doesn't appear...
