==== Architecture practices


===== Architecture as a management program
Bernard fig 1-4: Governance, Framework, Methodology, Best Practices, Standards, Artifacts

Activities/Bernard: (loc 561)
* Management program
* analysis & design method - how to factor out?? key weakness. waterfall.

As a management program, EA provides:     Strategic Alignment: Connects goals, activities, and resources     Standardized Policy: Resource governance and implementation     Decision Support: Financial control and configuration management     Resource Oversight: Lifecycle approach to development/management As an analysis and design method, EA provides:     EA Approach: The framework, analysis/design method, and artifact set     Current Views: Views of as-is strategies, processes, and resources     Future Views: Views of to-be strategies, processes, and resources     EA Management Plan: A plan to move from the current to the future EA

Bernard, Scott A.. An Introduction to Enterprise Architecture: Third Edition (Kindle Locations 585-601). AuthorHouse. Kindle Edition.

so, without EA... all this stuff is NOT getting done?

EA as policy vehicle... how is it that policies are enforced? process gating?

without EA.. how technical standards? how is a config image determined to be gold?

risk mgmt can't do it alone

In Bernard - goals & initiatives are above products & services - showing multiple product orientation - indicative of emergence phase

Entire language/mental model around gaps brings back flower & cog

A flower is not engineered to fill a gap. A cog is.

how do we know there is a gap? We have hypotheses... need to establish that there is a valuable, usable, feasible future state, and if there is progress towards it must not be delayed by queues, cycle time, etc ... need to move with alacrity... Cost of Delay outweighs much...

====== Architecture, governance, process

Many EA-originated policies that appear obsolete today have not always been meaningless. Most probably they have emerged as the architecture group's overreactions to unlikely-to-recur situations that they experienced in their organization in the past. A frequent example is the uncontrolled prolif
eration of newly hyped technologies by the IT crowd, and the EA group's rigid attempt to reinstitute order. Once the technology has matured, the EA rules often appear overly strict and suppress a flexible use of the appropriate technology. <<Bente2012>> p19

Bente is correct to focus on collaborative issues. but the overall benefits of having (for example) a TLM are not usually quantified in terms of cost and risk avoidance. This can be done. TLM should route via corp governance & perf mgmt, align w/vendor mgmt... find sources on how these processes work in non IT domains... (have already discussed in book)

arch review boards as xref:coord-struct[coordination structures]


===== Visualization

Architect as visual facilitator

*Architect as visual thinker*

Because of these facts, it is useful to understand some of the fundamentals of how humans interpret symbolic data.

(*** re-read and summarize Moody)

More on these in future chapters

Moody, but what are his sources?
http://simplybrainy.com/wp-content/uploads/2011/01/2008-Int-Vis-Other-Senses-All-Illustrations.pdf

Further reading on visual processing:

Moody
Tufte & others (that comparison paper cited by Moody)

complex graph...

But Cockcroft: if it changes too quickly, how to capture/represent?

formalisms don't give a good sense of scale - give a visual example

arch formalisms weak on dynamics - semantics vs dynamics problem semantics gravitate to first order predicate logic, binary thinking continuous math... required... how to measure anything. systems thinking.

but visualization is valuable otherwise we would not see so much of it

Cockburn communication problem - artifacts stimulate internal mental models but not Shannon... hence the endless attention to EA metamodelsThe big picture is part of the standard mindset of EA, which
everyoneimmediatelyassociateswiththeactivitiesofanenterprisearchitect.
However, many of these big pictures you meet in practice have been over-
abstracted to the point of insignificance and no longer address any relevant
question.<<Bente2012>> p16

"semantic distortions" - simple example: equal-sized boxes on an EA capability map.

the EA's role is to facilitate discussions by abstracting and visualizing powerfully so that decisions are illuminated.

usually, the resulting diagrams are only good tactically.

EA needs catalogs and matrices maintained. diagrams? it's questionable. every so often there is a ritual expression of a catalog as nested boxes. Of questionable utility. The graph complexity bogs down representation of the matrices.

illustrate: diagrams vs reporting, isometric catalog/matrix/diagram
why draw boxes when a textual report is all that is needed (e.g. Bente p52)


===== The "rationalization" quest
are the economics well understood?

====== application rationalization

====== Data & info

====== TLM
****
*Bad times at Airbus*

In 2006, (Ulrich)

TLM governance

****


****
[quote, Anonymous]
A foolish consistency is the hobgoblin of little minds.

*The folly of letting TLM dominate*

Henrik Kniberg tells the story of one of his most successful projects — a system built for the Swedish police that allowed them to use laptops in the field — and what happened afterwards <<Kniberg2011>>. Because the project was extremely urgent, the group was allowed to use an agile approach and break out of the traditional organizational culture. Everything went well, the police organization viewed it as a success, and the project even won a “project of the year” award.

What came next, however, was even more interesting. A high-level decision was made to rebuild from scratch that same system police had used in the field, using Siebel. This was part of a standardization effort to reduce the complexity and number of systems. Not only was the decision made to use a technology that the development team didn’t agree with, but it was decided to use a more traditional, sequential project-management approach to development. Development took a couple years and when it finally rolled out, it was a disaster because the police found it to be slow and clumsy and basically unusable. Making the change even more difficult was that the police preferred their existing system, which worked. Kniberg estimates that this cost the Swedish police more than £1 billion.

in http://www.infoq.com/resource/minibooks/why-agile-works/en/pdf/InfoQ-Why-Agile-Works-Mini-book.pdf
****

1 billion pounds ($1.6B) would have bought a lot of support & vendor leverage for the "nonstandard" technologies.

Lifecycle management can extend to internal products/services

EA provides guidance about what technologies are a strategic fit, which ones are deprecated, and which are emerging. <<Bente2012>> p8

Case study: The version control controversy: service vs TLM

if enterprise architects claim to be the only decision-making body
in technical matters, there is a huge risk that they create a bottleneck, if decisions take ages due to pending strategic issues, imminent changes in the business model, and so forth, IT projects can be seriously delayed. The practical consequence is that projects deliberately circumvent the enterprise architects—for example, by choosing less suitable technologies not managed by the EA group.<<Bente2012>> p19

Note that we compensate developers with money AND experience. Developer pressure to use a new technology should be seen in part as a demand for increased compensation. developers seeking experience, it is in part how they are compensated. this leads to conflicts over choice of tools. (good blog as well). rational framework for deciding. might go to chapter 8, resource mgmt. intersection between that & tech lifecycle is key.

EA makes the decision to insource or outsource

===== Repositories and knowledge management

backref to ch 11?

Agile & docs "In an agile project, explicit care must be taken to ensure proper documentation—for example, by stating it as part of the condition of satisfaction of a user story or in the definition of done" <<Bente2012>> p 170

====== The repository question

CMDBs, metadata, EA

====== DevOps assets to architecture

If you started from day 1 with source, build, & package mgmt, and have kept it clean, you have a great asset

====== Metamodels and ontologies
app v svc def'n
