anchor:portfolio-management[]

==== Portfolio management
[quote, Peter Drucker]
…every product and every activity of a business begins to obsolesce as soon as it is started. Every product, every operation, and every activity in a business should be put on trial for its life every two or three years.

Each should be considered the way we consider a proposal to go into a new product, a new operation, or activity – complete with budget, capital appropriation request, and so on.

One question should be asked of each: “if we were not in this already, would we now go into it?” And if the answer is “no,” the next question should be: “How do we get out and how fast?”

Peter F. Drucker


EA & M&A - Bernard location 432 - like that value prop  - who is an EA? the person you would bring in to help assess a potential acquisition's systems for fit/overlap etc.


****
Sidebar: IT analytics experts
Magennis, Cantor, etc
****


===== Digital pipeline analytics

Over time, the IT operation develops significant data by which to manage itself. It may develop one or more definitive portfolio list, typically applications, services, assets, and/or technology products. Distinguishing and baselining high quality versions of these data sets can consume inordinate resource, and yet managing the IT organization at scale is nearly impossible without them.. [_didn't want to discuss data per se in the introduction_]

Feedback loop from architecture to investment (chapter 8) - hopefully you have been quantitative enough, now you are formalizing (e.g.) an "IT mgmt data warehouse"

ARch: limited by lack of analytics. That's where PM comes in. For example discussion in Bente is badly weakened by reliance on interviews/expert opinions. A problem for EA in general.



Defining portfolio. "Things of consequence managed over long time horizon (betz)" TOGAF catalogs

Apples to apples
Objective vs. subjective data
Subjective
Usability
Customer satisfaction
Objective
Service levels, changes, incidents
Cost
Staffing
Technical debt & complexity

Types of portfolio segmentation

Portfolio hazards
Throwing money down a hole –
is the (proposed or in-flight) project a good idea?
Will it add value?
In light of changing business conditions?
Expensive and un-anticipated sourcing requirements.
Does the IT organization have the staff to execute the project portfolio?
Will local contractors need to be brought on at the last minute, at a negotiation disadvantage?

No project plan for steady state
Was total cost of ownership analyzed and defined?
Were the resulting staff increases for operations and maintenance agreed to as additional to the current base budget?
Poor systems quality – even when the project is deemed a “success.”
What is the incident rate?
Unplanned maintenance releases?

Lack of re-use and re-usability –
were expensive investments made in functionality that cannot easily be integrated into new business models?
Is there redundancy in the infrastructure or applications?
Were new technologies acquired requiring new systems engineering skills?
Complexity – even when the system “works.”
Does it take 8 hours staff time on average every week (or night!) to get the overnight batch to completion?
Did the last team working on a maintenance release spend half their time re-analyzing the system’s current state?

Obsolescence –
Are knowledgeable staff more and more expensive?
Is the hardware beyond a total cost of ownership “sweet spot”?
Vendor/product issues –
did your database vendor force you into a new version, imposing new maintenance releases across 25% of the applications in your portfolio?
Did you understand the impact of this sufficiently in advance?
Security risks due to obsolescence?
Service non-use.
Has this capability simply outlived its usefulness?
Business value.
Does the capability make sense to continue?

Costs
Hardware depreciation or leasing
Software licensing (typically 15%-20% annually of initial acquisition, required for vendor support).
Floor space – i.e., real estate charges
Facilities infrastructure: power, high volume air conditioning (HVAC), raised floor, racks, etc.
Network connectivity and related infrastructure (e.g. directory services software, security perimeters, and the like)
Operational software infrastructure: monitoring systems, batch schedulers, backup systems, and so on, all with their own associated costs.
Operations and support staff. Staffing typically can come in various flavors:
Data center operations monitors
Help desk operators
Application specialists
Senior engineers
Senior IT executives and customer relationship managers
Business-side lead users and process and information specialists
Vendor relationship owners and contract managers
Etc..

4-box

Taxonomies for classification

Application functions (examined for redundancy)
Application total cost of ownership
Application complexity,
Fitness and currency of underlying technical products
Application service performance
Application customer feedback
