==== Conclusion

Architecture is a challenging topic for both the student and the practitioner. Its value is too often unclear, but when it is eliminated, it tends to re-emerge in response to operational learnings. "If we'd just had some architecture, X would not have happened" is too often heard.

As humans we think in abstractions and architecture is an expression of this. The architect skilled in doing so, in sense-making across the landscape and providing guidance on key decisions, identifying opportunities, and taking care for stewardship of the longer horizon will remain a valuable asset to the digital organization as it scales up into the largest problems.

===== Discussion questions

* Should digital professions continue to use the term "architect"?
* Debate the pros and cons of having an architecture organization approve designs or technology platform choices. Be prepared to argue either side.
* Debate the pros and cons of visual modeling
* Do you agree that architecture is a form of staff function? Why or why not?
* Read the articles by Bloomberg below and discuss whether there is any future in architecture.
** http://www.forbes.com/sites/jasonbloomberg/2014/07/11/is-enterprise-architecture-completely-broken/#1febba552f30[Is Enterprise Architecture Completely Broken?]
** http://www.forbes.com/sites/jasonbloomberg/2014/07/23/agile-enterprise-architecture-finally-crosses-the-chasm/#224402cb3c77[Agile Enterprise Architecture Finally Crosses the Chasm]

===== Research & practice

* Build a virtual machine cluster and install or develop software for it, ideally including a database. Download the free http://www.archimatetool.com/[Archi] tool for Archimate and draw a representation of the software or data architecture.
* Draw the same idea in two different ways in Archimate.
* Draw two or three catalogs and associated matrices and diagrams. Make sure all are consistent (e.g. lines correspond to matrix intersection data)
* Compare and contrast any two xref:vertical-standards[industry vertical architectures.]
* Compare and contrast business model versus operating model, and in the same analysis consider the distinction between enterprise architecture and business architecture. Can enterprise architecture be equated with the operating model? If business architecture is a subset of enterprise architecture, does that mean it also is primarily concerned with the operating model? Or is business architecture also concerned with the business model?

===== Further reading

*Books*

Stefan Bente, https://www.goodreads.com/book/show/14788822-collaborative-enterprise-architecture[Collaborative Enterprise Architecture: Enriching EA with Lean, Agile, and Enterprise 2.0 Practices]

Chris Potts, https://www.goodreads.com/book/show/11655528-recreation[RecrEAtion: Realizing the Extraordinary Contribution of Your Enterprise Architects]

Jeanne Ross, https://www.goodreads.com/book/show/70137.Enterprise_Architecture_As_Strategy[Enterprise Architecture As Strategy: Creating a Foundation for Business Execution]

Steven Spewak, https://www.goodreads.com/book/show/223940.Enterprise_Architecture_Planning[Enterprise Architecture Planning: Developing a Blueprint for Data, Applications, and Technology]

William Ulrich, https://www.goodreads.com/book/show/11877561-business-architecture[Business Architecture: The Art and Practice of Business Transformation]

*Articles*

* https://www.itpreneurs.com/blog/agile-togaf-and-enterprise-architecture-will-they-blend/[Agile, TOGAF and Enterprise Architecture: Will They Blend?]

* http://www.forbes.com/sites/jasonbloomberg/2014/07/11/is-enterprise-architecture-completely-broken/#1febba552f30[Is Enterprise Architecture Completely Broken?]

* http://www.forbes.com/sites/jasonbloomberg/2014/07/23/agile-enterprise-architecture-finally-crosses-the-chasm/#224402cb3c77[Agile Enterprise Architecture Finally Crosses the Chasm]

* https://www.microsoft.com/en-us/research/wp-content/uploads/2016/02/p557-cherubini.pdf[Let’s Go to the Whiteboard: How and Why Software Developers Use Drawings]
* https://softvis.files.wordpress.com/2010/12/gradybooch-whydontdevelopersdrawdiagrams-softvis2010.pdf[Booch: Why Don’t Developers Draw Diagrams?]

* http://www.ruthmalan.com/Journal/2010/2010JournalOctober.htm#Why_Dont_Developers_Draw_Diagrams[Malan: Why Don't Developers Draw Diagrams?]

* http://www.ruthmalan.com/Journal/2010/2010JournalOctober.htm#Reworking_some_of_the_ideas:_Why_Dont_Developers_Draw_Diagrams[Malan: Reworking some of the ideas: Why Don't Developers Draw Diagrams?]

* http://search.proquest.com/openview/b0c1cf4f68c5b1d08ce290f75bb3c332/1?pq-origsite=gscholar[Booch: Draw Me a Picture]

* http://www.ruthmalan.com/journal/2011/2011JournalSeptember.htm#When_Are_Diagrams_Useful[Malan: When Are Diagrams Useful?]

*Professional*

* http://www.businessarchitectureguild.org/[Business Architecture Guild]
* https://www.globalaea.org/[Association of Enterprise Architects]
* http://iasaglobal.org/[Iasa Global, a non-profit association for ALL IT Architects]
