==== Why architecture?
[quote, Fred Brooks, Planning a Computer System: Project Stretch]
Computer architecture, like other architecture, is the art of determining the needs of the user of a structure and then designing to meet those needs as effectively as possible within economic and technological constraints. Architecture must include engineering considerations, so that the design will be economical and feasible; but the emphasis in architecture is upon the needs of the user, whereas in engineering the emphasis is upon the needs of the fabricator. [1962, first published use of the term "architecture" with respect to computing system organization.]

[quote, Grady Booch]
Architecture represents the significant design decisions that shape a system, where significant is measured by cost of change.

"Architecture" is of course a word usually associated with physical construction: buildings, landscapes, etc. It was appropriated by systems engineers at IBM around 1960 to describe the problems of designing complex information processing hardware and software.

This leads to some confusion, and occasional questions from "real" architects as to why IT people are calling themselves "architects." Perhaps a different choice of word would have been advisable.

Regardless, the architecture concept is not something new or foreign. In our journey to date, we have covered:

* Business xref:what-is-IT-value[motivations] and xref:digital-context[context],
* xref:what-is-IT-infrastructure[Infrastructure]
* xref:chapter-app-deliv[Applications],
* xref:prod-mgmt-definition[Products] and/or services,
* xref:organization[Organization] and xref:chap-process-mgmt[process], and
* xref:chap-ent-info-mgmt[Data and information].

We have also covered the practices by which ideas and intentions are established and translated by investment into actions, including:

* Investment of time and resources towards digital objectives (e.g. through xref:project-mgmt[project management]),
* Acquisition of technologies and external services (i.e. xref:it-sourcing[sourcing]),
* xref:resource-mgmt[Hiring of employees],
* xref:gov-chap[Governance] of digital organizations for xref:risk-management[risk], xref:security[security], and other purposes.

*Enterprise architecture is nothing but the unification of these topics into a common, formalized, scalable framework for understanding.*

As we have progressed in our journey, and scaled our company up, all these areas have continued to evolve. Specialization emerges. You have people with deep experience in Cloud architectures, and people with deep experience in e-records management and compliance. You don't have too many who are deep in both.

Your product portfolio (internal and external) is now in the hundreds or thousands. Some were built with the latest technology, and others run on older technologies now perceived to be dead ends. But investing in rewriting them would not provide as much value as other uses of the funds, so you have to manage the risk of the older technology.

Investment decisions become harder. You're far beyond the days when you had a one-product focus. You have multiple interacting products and multiple interacting teams, and the relationship between the teams and products is not one to one. Understanding the business case for the investment gets harder; when you have a thousand services over multiple business units, how do you know if someone is proposing a redundant new one?

And then there are the big headaches. A major commercial product version is going off support, and it's the perfect time to think about a rewrite or replatform (say into the Cloud). But the moving pieces and interdependencies are formidably complex, and if you get the analysis wrong the business impact will be severe. Or a major outage does impact the business, and all of a sudden the organizational priority (from the Board on down) is "fix this so it never happens again." Everything else is to go "on hold." Except, of course, it can't.

In response to these and a thousand other complexities of digital management as organizations scale up, a general purpose coordination capability emerges sometimes called Enterprise Architecture.

===== Defining Enterprise Architecture
[quote, Jeanne Weill and Peter Ross, Enterprise Architecture as Strategy]
The enterprise architecture is the organizing logic for business processes and IT infrastructure, reflecting the integration and standardization requirements of the company's operating model. The enterprise architecture provides a long-term view of a company's processes, systems, and technologies so that individual projects can build capabilities—not just fulfill immediate needs.

[quote, Bente et al, Collaborative Enterprise Architecture]
Enterprise architecture (EA) is the representation of the structure and behavior of an enterprise's IT landscape in relation to its business environment. It reflects the current and future use of IT in the enterprise and provides a roadmap to reach a future state. <<Bente2012>> p 35

There are numerous definitions of enterprise architecture. It can be defined as:

* an organizational unit
* an organizational capability
* a professional discipline or set of practices
* a process or process group; a ongoing activity or activities
* a large-scale artifact (i.e. an integrated model consisting of catalogs, diagrams, and matrices) maintained on an ongoing basis for communication and planning
* an integrated and standardized language for reasoning about complexity

Enterprise architecture in the whole covers organizational as well as technical domains; we will discuss this in more detail in the next chapter section.

In general, definitions of enterprise architecture characterize it as a coordination and problem solving discipline, suited to large scale problems at the intersection of digital technology and human organization. It has a variety of specialist domains, as we'll discuss in the next chapter section. Its definition can be extended pragmatically through looking at its relationships to other significant capabilities in the large organization.



====== Business model vs operating model


blurry boundaries, certainly
One core question decided by governance is how much autonomy is granted to business units or geographical regions. In case this autonomy is high, would a quest for high IT integration and standardization not be like fighting windmills? <<bente2012>> p.45 and cross ref ch 1

 BM vs OM - matrix



All arch is design not all design is arch (Booch)


===== Architecture organization


"Office of CIO" - general staff model


====== Architecture as staff function
[quote, Elihu Root, 1903 congressional testimony on US army re-organization]
\... the organization is weak at the top ... because there is ... no coordination of the exercise of powers provided for in the system. That coordination ... can be done only by a body ... organized for that purpose and having no other duties to perform; and in all the armies of the civilized world that duty is ... performed by a ... General Staff ... because their duties are staff duties ... pertaining to the general conduct of affairs, and not merely to the work [of specific departments].

Architecture = intersection of technical management with investment, sourcing, information, governance

Roots in Berthier

Sense-making at scale will not go away.

Many elements that have become integral parts of managerial economics and organizing sciences can be traced back to the Prussian-German General Staff system. <<Millotat1992>>, p. 7

====== EA vs operating model
as opposed to business model

Bernard claims: [without EA]...leadership will not have the ability to generate clear, consistent views of the overall enterprise on an ongoing basis, they won’t be able to effectively compare business units, and the locus of power for planning and decision-making will be at the line-of-business, program, and/or system owner levels-with significant differences in how things are done and high potential for overlapping or duplicative functions and resources.

Bernard, Scott A.. An Introduction to Enterprise Architecture: Third Edition (Kindle Locations 456-459). AuthorHouse. Kindle Edition.

Of course, corporations compare business units all the time, on P&L and other enterprise metrics, without an architecture. If an enterprise is a holding company, by definition it is not seeking a common operating model.

Parsimony. What is the value of saying that EA and EOM are distinct? We have too many abstractions.

====== Architecture versus corporate strategy & planning

the business-IT alignment gap exists because there is a pervasive assumption that technology is a tactical rather than a strategic concern. <<???>>

model stability -- strat consults tend to swap out methods & frameworks as needed for the problem - this is good but no consistency

arch is poorly quantified, limited line of sight to revenue & profitability

Bezos: all service oriented

will microservices be better? SOA finally done right?

Architecture overreach - here, we restrict to OM. Business model questions are discussed throughout other chapters. But biz arch overlaps. Finance & competitive strat is not primarily EA, even BA.

Logistics vs strategy

====== Architecture vs program/project
projects tended to disregard - systems were more monolithic

“Enterprise architecture tends to be viewed as a hostile takeover by program managers and executives who have previously had a lot of independence in developing solutions for their own requirements” <<Bernard2012>>


===== The value of EA

Critical importance of an economic model

Architecture HIPPOS

Present master impact map & discuss step by step

On the value side, EA is unique in its ability to promote enterprise-wide thinking about resource utilization. EA replaces the systems-level approaches to IT resource development that have characterized the last several decades, and has left many enterprises with stovepipe and/or duplicative IT resources. EA promotes the development of more efficient enterprise-wide common operating environments for business and technology, within which more capable and flexible business services and systems can be hosted. This in turn makes an enterprise more agile and able to respond to internal and external drivers of change, which promotes greater levels of competitiveness in the marketplace. <<Bernard2012>>

The true measure of the value of a model is whether it actually influences behavior. Smith/Reinertsen 1998 p46.

Instead of tapping into the existing knowledge of the organization the autonomous team is prone to reinvent the wheel, and the wheel that they reinvent will not always be superior to the one we are currently using. <<Reinertsen1997>> p 104

Bernard, Scott A. (2012-08-13). An Introduction to Enterprise Architecture: Third Edition (Kindle Locations 1113-1117). AuthorHouse. Kindle Edition.

Barnard asserted value:

* Shorting planning & decision-making
* Reducing duplication
* Reducing re-work
* Reducing headcount (e.g. in processes)
* Improved communication

Whether EA is perceived as a hygiene factor for the IT landscape or as a strategic foundation for business enablement, it is obliged to deliver value. As a hygiene factor, benefits from EA can be valued in terms of reduction in management escalations, emergency occurrences, and year-on-year operational expenses. As a strategic foundation, EA facilitates the deployment of new capabilities. This way it helps IT gain more business trust—and hence more funding for new IT projects. Unfortunately, these benefits are difficult to quantify on a short-term base. Therefore they need to be tracked over a sufficient time period and then be normalized to a common baseline. Only then can they serve as a sensible benchmark for measuring the success of EA. <<Bente2012>>

Flexibility at high levels in the architecture comes from standardization at low levels in the architecture. Paradoxically, structure is the key to freedom. ibid 120

"work not done"

limiting options

====== Reducing Cost of Delay
need baseline COD (should we introduce this in Chapter 8? probably.)

====== Technical debt

reinertsen critique of the concept

Scrum vs XP - Scrum as promoter of tech debt - inattention to practices... (blogs was reading 9/28/16 PM)

how does it monetize?
