==== Conclusion

Architecture is a challenging topic for both the student and the practitioner. Its value is too often unclear, but when it is eliminated, it tends to re-emerge in response to operational learnings. "If we'd just had some architecture, X would not have happened" is too often heard.

As humans we think in abstractions and architecture is an expression of this. The architect skilled in doing so, in sense-making across the landscape and providing guidance on key decisions, identifying opportunities, and taking care for stewardship of the longer horizon will remain a valuable asset to the digital organization as it scales up into the largest problems.

===== Discussion questions

* Should digital professions continue to use the term "architect"?
* Debate the pros and cons of having an architecture organization approve designs or technology platform choices. Be prepared to argue either side.
* Debate the pros and cons of visual modeling
* Do you agree that architecture is a form of staff function? Why or why not?

===== Research & practice

* Build a virtual machine cluster and install or develop software for it, ideally including a database. Download the free http://www.archimatetool.com/[Archi] tool for Archimate and draw a representation of the software or data architecture.
* Draw the same idea in two different ways in Archimate.
* Draw two or three catalogs and associated matrices and diagrams. Make sure all are consistent (e.g. lines correspond to matrix intersection data)
* Compare and contrast any two xref:vertical-standards[industry vertical architectures.]
* Compare and contrast business model versus operating model, and in the same analysis consider the distinction between enterprise architecture and business architecture. Can enterprise architecture be equated with the operating model? If business architecture is a subset of enterprise architecture, does that mean it also is primarily concerned with the operating model? Or is business architecture also concerned with the business model?

===== Further reading

*Books*


*Articles*

https://softvis.files.wordpress.com/2010/12/gradybooch-whydontdevelopersdrawdiagrams-softvis2010.pdf

http://www.ruthmalan.com/Journal/2010/2010JournalOctober.htm#Why_Dont_Developers_Draw_Diagrams

http://www.ruthmalan.com/Journal/2010/2010JournalOctober.htm#Reworking_some_of_the_ideas:_Why_Dont_Developers_Draw_Diagrams

http://www.computer.org/csdl/mags/so/2011/01/mso2011010006-abs.html

http://www.ruthmalan.com/journal/2011/2011JournalSeptember.htm#When_Are_Diagrams_Useful

https://www.itpreneurs.com/blog/agile-togaf-and-enterprise-architecture-will-they-blend/

* http://www.forbes.com/sites/jasonbloomberg/2014/07/11/is-enterprise-architecture-completely-broken/#1febba552f30

* http://www.forbes.com/sites/jasonbloomberg/2014/07/23/agile-enterprise-architecture-finally-crosses-the-chasm/#224402cb3c77

https://www.microsoft.com/en-us/research/wp-content/uploads/2016/02/p557-cherubini.pdf[Let’s Go to the Whiteboard: How and Why Software Developers Use Drawings]

*Videos*

*Professional*
