==== Agile and architecture
[quote, Bente et al, Collaborative Enterprise Architecture]
...we encountered companies that, despite having a fully institutionalized EA in place, were in a state close to paralysis...Although EA has reached the mainstream, a skeptical undertone with regard to its effectiveness has always existed. (p 12-13)

The relationship between architecture (both "enterprise" and other forms of architecture) and current Agile, DevOps, and digital product development approahces is too often troubled. However, the hope is that this book has given you a set of tools for resolving these concepts in a productive way.

This chapter will challenge you by presenting the polemical arguments directly and frankly, as two sides to a debate, concluding with thoughts on finding common ground. Note that these points of view are deliberately extreme, to make the point:

.Author's Note
****
As a practicing architect I can confirm that there is often friction between developers with an Agile perspective and enterprise architects. This carries through into industry discussions and conference presentations.

I think the best approach to resolving this conflict is through careful understanding of the perspective of each "side." Both have validity. I recommend framing the conversation in terms of xref:arch-impacts[architecture's value impacts].
****

===== The hubris of architecture
_The goal of enterprise architecture is to act as a guide, perhaps a pathfinder, who takes the enterprise on a transformational journey—from an incoherent and complex world with line-of-business separation, product-specific stovepipes, legacy systems estate, and costly operation to a more rationally organized and useful state with multiservice, revenue-generating platforms and an efficient operational regime. On the way, radical surgeries may be required to eliminate duplication, reduce costs, improve reliability, and increase agility in the business. EA acts as a strategic foundation for business enablement._ <<Bente2012>> p9

Product development organizations often experience architecture and its goals as unwarranted interference, imposing a high xref:cost-of-delay[Cost of Delay] with little apparent return on investment. Architecture approvals can be required on:

* application designs
* database designs
* selection of technology products

and other such topics. When development cannot proceed without those approvals - or if the approvals come at the cost of expensive re-work - the experience can often be challenging. Bente et al warn: "if enterprise architects claim to be the only decision-making body in technical matters, there is a huge risk that they create a bottleneck...The practical consequence is that projects deliberately circumvent the enterprise architects..." <<Bente2012>> p19

And, looking more broadly at the practice and history of architecture, the case against it is strong. Enterprise architecture has presented itself as a solution to complexity, long IT time scales, business frustration, and other various IT problems. But in the past decade to the extent these issues have been solved, it has not been by architecture but by Agile and DevOps practices rethinking open-loop, slow feedback, batch-oriented delivery. Architecture has failed in many ways:

It failed to realize the emergent issue of too much enterprise work in process, instead championing the proliferation of enterprise processes and their associated queues. Fundamentally, they did not adopt enough of a systems view of IT delivery.

Architects' motivation for "efficiency" and interest in capability mapping did not help the cause of cross-functional teams. Instead, functional silos were reinforced as supply-centric "capabilities" and the antipattern of "bringing the team to the work" was accepted as enterprise standard operating procedure - despite the growing evidence of Scrum and Agile success. The iterative, experimental narrative of Lean Startup did not originate from EA.

Architects too often fall into the trap of the  xref::HIPPO[HIPPO] (Highest Paid Person's Opinion). Despite dabbling in systems theory, architecture has only recently begun to realize the fundamental problems of stage-gated delivery, big bang releases, and so forth. It has been too sympathetic to the now-discredited Capability Maturity Model and PMBOK and cannot escape the criticism of "top down planning," which in complex systems domains too often doesn't work. Hypothetical "synergies" emerging from "common platforms" are often offered as justification for architecture, with little follow up in measuring actual value delivered.  A sense of xref:lean-startup[Lean Startup] experimentation, of placing bets on options and testing hypotheses, is not part of the mainstream enterprise architecture understanding. Instead, the architecture is presented as an established fact, with "governance" to ensure conformity.

Justifications for architecture often invoke "complexity" in the portfolio of systems. In response, architecture has often given in to the desire for a  complete "radical surgery" systems re-engineering, the temptation of the "clean slate." But as Jez Humble accurately notes,

_A common response to getting stuck in a big ball of mud is to fund a large systems replacement project. Such projects typically take months or years before they deliver any value to users, and the switchover from the old to the new system is often performed in “big bang” fashion. These projects also run an unusually high risk of running late and over budget and being cancelled. Systems rearchitecture should not be done as a large program of work funded from the capital budget. It should be a continuous activity that happens as part of the product development process. <<Humble2013>> ch10_

Architecture methodology, with its focus on identifying capability gaps for feeding into the project portfolio process, has perhaps been too prone to supporting these large, troubled programs. As we know from our earlier chapters, large system changes are inherently risky and any intervention into a complex system is better undertaken as a series of smaller, incremental changes with frequent monitoring and assessment.

===== The hubris of Agile
[quote, Donald Reinertsen, Managing the Design Factory]
Instead of tapping into the existing knowledge of the organization the autonomous team is prone to reinvent the wheel, and the wheel that they reinvent will not always be superior to the one we are currently using <<Reinertsen1997>>, p. 104.

====== The limitations of Cost of Delay
[quote, Ruth Malan]
When it  comes to system implementation, the temptation to be  fast, often under the nom de guerre of agile, can soften  quality controls and threaten product usability, reliability, safety, and lifecycle cost <<Malan2010>>.

Cost of Delay is a real and often overlooked issue, in understanding the net value of architecture. But it is only a factor, and does not eliminate the value proposition of architecture. If the Cost of Delay is only a few hundred dollars a month, but the risk or technical debt represent millions, then delay may be appropriate. Don Reinertsen, who has done more than anyone to promote the idea of Cost of Delay, emphasizes that *all* decision making must take place within an economic framework (<<Reinertsen2009>>, chapter 2) and that means that the other xref:arch-impacts[architectural impact factors] on organization value must also be considered.

====== Documentation

Documentation has been a core concern of the Agile movement, being mentioned in one of the four core principles of the Agile Manifesto:

_"Working software over comprehensive documentation" <<Alliance2001>>_.

When documentation primarily takes the form of xref:secondary-artifacts[secondary artifacts], it is appropriate to question the need for it. "The code is the documentation," some will argue. While it is true that good coding practices result in easier-to-understand (and maintain) source code, the code cannot be the only documentation.

As Ruth Malan notes,

_...for systems of sufficient scope and complexity to warrant teams (of teams) working on (incremental) implementation and evolution, the sheer mass of code can make it hard to discover the essential structure from bottom-up decisions made entirely through the medium of code. <<Malan2010>>_

In terms of systems theory, a complex software system has emergent behavior, not obvious from just looking at its components. Because the system's behavior can't be reduced to its pieces, "self documenting code" can only go so far. The behavior of the assembled components as a system needs to be represented somehow, in a way that transcends the mere mechanics of the pieces. Abstraction is necessary to understand emergent behavior, and this leads inevitably to xref:arch-visualization[visual representation].

====== Sourcing and technology standards

Agile and DevOps are software-development centric, and have transformed that world. However, we don't always build. Software may be eating the world, but that doesn't mean everyone employs - or should employ - software developers. Agile has not had a primary focus on xref:sourcing[sourcing], and certainly evaluating commercial software is not a common topic.

Suppose you have an idea for a digital product, and you know that you will be (at least in part) assembling complex services/products produced by others? Suppose further that these provided services overlap (the providers compete)? You need to carefully analyze which services you are going to acquire from which provider.  You will need a strategy, and who is it that analyzes these services and their capabilities, interfaces, non-functional characteristics, and makes a final recommendation as to how you are going to bring them all into one unified system?

It is easy to say things like, "the teams get to define their own architecture" but at some point the enterprise must reckon with the cost of an overly diverse supplier base. This is a very old topic in business, not restricted to IT. At the end of the day, supplier and sourcing fragmentation costs real money. Open source, Commercial-off-the-shelf, Cloud, in-house... the options are bewildering and require experience. A consistent evaluation approach is important (preferably under an economic framework Reinertsen/Hubbard). And at some point, product development teams should not have to do too much of their own R&D on possible platforms for their work.

====== Architecture as emergent
[quote, Adrian Cockcroft, former CTO Netflix]
“At Netflix, we had no central control [of the architecture] ... The goal of architecture was to create the right emergent behaviors...”

The Agile Manifesto is well known for saying "The best architectures, requirements, and designs emerge from self-organizing teams" <<Alliance2001>>. This is one of the more frequently discussed Agile statements. Netflix CTO Adrian Cockcroft has expressed similar views (quote above).

A key question is whether "architecture" is considered at the single product or multi-product level. At the single product level, collaborative teams routinely develop effective architectures. However, when multiple products are involved, it is hard to see how all the xref:arch-impacts[architectural value] scenarios are fulfilled without some investment being directed to the goal.

It helps when rules of the road are established; both Amazon and Netflix have benefitted from having certain widely accepted platform standards. The question does get harder when layered products and services with xref:IT-lifecycles[complex lifecycle interactions] are involved.

===== Towards reconciliation
toward a rapprochement: it  all starts with "respect the team" - and this applies to teams of architects - or one architect on a team - trouble is that architects are often spread too thin...

====== Rethinking investment

great Josh A insight: what problems can be handled w/projects vs. which need steady state capaiblities? Cynefin: simple/complicated vs complex/chaotic.. - if your strategy is to elucidate the complex you need an ongoing mental model... preserve the team -


====== Architecture kata

Our experience is that standardization on a particular toolchain or technology stack is neither necessary nor sufficient for achieving enterprise architecture goals such as enabling teams to respond rapidly to changing requirements, creating high-performance systems at scale, or reducing the risk of intrusion or data theft. Just like we drive product and process innovation through the Improvement Kata, we can drive architectural alignment through it too. Architectural goals—for example, desired performance, availability, and security—should be approached by iteratively specifying target conditions at the program level. Following the Principle of Mission, set out a clear vision of the goals of your enterprise architecture without specifying how the goals are to be achieved, and create a context in which teams can determine how to achieve them through experimentation and collaboration.   <<Humble2013>> ch10

Toyota Kata and EA  - importance of target condition


====== Cost of Delay-based prioritization
[quote, Bente et al, Collaborative Enterprise Architecture]
Another possible objection against agile methods is that the processes in EA, and in the enterprise generally, are simply not operating with a time window of the typical sprint length of three weeks. This, of course, is true. But it is at closer inspection not a counter-argument against the application of agile principles to EA—just the opposite. The long process cycles add to EA's lack of transparency and promote a silo mentality. Agile techniques can help here. <<Bente2012>>

feedback loop between line & staff???

Entire language/mental model around gaps brings back flower & cog

A flower is not engineered to fill a gap. A cog is.

how do we know there is a gap? We have hypotheses... need to establish that there is a valuable, usable, feasible future state, and if there is progress towards it must not be delayed by queues, cycle time, etc ... need to move with alacrity... Cost of Delay outweighs much...

EA "process"

- queuing and fast feedback

====== Ongoing portfolio evolution

Amazon Obidos example, strangler pattern.
* Start by delivering new functionality—at least at first
* Do not attempt to port existing functionality unless it is to support a business process change
* Deliver something fast
* Design for testability and deployability
* Architect the new software to run on a PaaS

====== Visualization and documentation

understanding purposes of diagrams and appropriate level of investment/formality

In the Agile world,  xref:2.05.02-kanban[Kanban] is a strongly visual system for building a shared mental model of work in process.


preparing along the way understand inventories and dependencies - importance of Bezos mandate to the dependency question - if there is one battle you fight, make it that one -

the importance of documentation - speech to text, text analytics... image recognition... what might the future hold? At least get technical writers... don't make developers write...

====== Scaling & architecture
* systems too big for 1 team
* features that are too complex to be implemented in 1 iteration
* features that cause too much org chg mgmt

====== "Coding architects?"
Primarily in SW domain
But virtualization now makes it possible for all archs to be hands-on, even w/pkgs

<<Cohn2010>> chapter on architect role - confusion of software & enterprise arch

keep EAs off product teams, agree but they set overall direction @ portfolio level difficult for them to stay hands on

Lot of confusion in the literature about sol arch vs EA.


====== Architecture and digital exhaust
we can assess the degree to which architecture is influencing real choices

Agile & docs "In an agile project, explicit care must be taken to ensure proper documentation—for example, by stating it as part of the condition of satisfaction of a user story or in the definition of done" <<Bente2012>> p 170

If you started from day 1 with source, build, & package mgmt, and have kept it clean, you have a great asset

anchor:TLM-CoD-worked[]

===== Architecture, queues, and Cost of Delay

worked TLM example

TLM should route via corp governance & perf mgmt, align w/vendor mgmt... find sources on how these processes work in non IT domains... (have already discussed in book)

review Reinertsen

Bente p 194 looks @ arch process optimization - local optima, bad. Goes down the work/wait alley and DSM (anti-rework). Limitations.

Also, IT finance typically doesn't appear...

All the coordination mechs can be applied... cadence/synch - queue understanding, CoD critical



====== NOTES

Cockcroft quote

Cathedral / bazaar



Bente's four perspectives & eight caricatures

[quote, Bente et al]
With regard to the nature of complex systems, it is not advisable to search for the "optimal enterprise architecture." Optimality is always relative to an environment, and the frame conditions are likely to change. Hence it is better to accept certain ugly spots of the IT landscape and strengthen the viability of the whole, which means developing and using capabilities such as being able to learn, solve problems, adapt, or absorb disruptions.

 critical importance of not confusing solutions with EA. Scale matters.

 from bente: Anti-patterns in EA and architecture in general can be found, for instance, in Kruchten (2008), Mar and Spacey (2011), Ambler, Nalbone. and Vizdos (2005), and Coplien and Harrison (2005).

 Cockburn quote on CCC project - disbanded & disintegrated due to relying on oral tradition

 https://philippe.kruchten.com/2011/02/13/the-elephants-in-the-agile-room/
