==== Why architecture?

Roots in Berthier


 Bezos: all service oriented


 For enduring competitive
 advantage, the organization needs
 to seek leverage across its prod-
 ucts and/or services and to create
 strategic capabilities that are hard
 to imitate because they rely on a
 mix of process, technology, skills,
 resources, facilities, culture, and
 even history <<Malan2005>>

 projects tended to disregard - systems were more monolithic

 will microservices be better? SOA finally done right?

CEO as architect... go back to chapter 1 -

But you can have the goodness without formalizing architecture as a program, practice, discipline, or capability.

This is about formalizing it. Not the idea that products should be well designed and delightful. We covered that in Chapter 4.

===== Drivers
On the value side, EA is unique in its ability to promote enterprise-wide thinking about resource utilization. EA replaces the systems-level approaches to IT resource development that have characterized the last several decades, and has left many enterprises with stovepipe and/or duplicative IT resources. EA promotes the development of more efficient enterprise-wide common operating environments for business and technology, within which more capable and flexible business services and systems can be hosted. This in turn makes an enterprise more agile and able to respond to internal and external drivers of change, which promotes greater levels of competitiveness in the marketplace.

Bernard, Scott A. (2012-08-13). An Introduction to Enterprise Architecture: Third Edition (Kindle Locations 1113-1117). AuthorHouse. Kindle Edition.

===== Architecture versus corporate strategy & planning

the business-IT alignment gap
exists because there is a pervasive
assumption that technology is a
tactical rather than a strategic
concern.

model stability
strat consults tend to swap out methods & frameworks as needed for the problem - this is good but no consistency

arch is poorly quantified, limited line of sight to revenue & profitability

formalisms don't give a good sense of scale - give a visual example

arch formalisms weak on dynamics - semantics vs dynamics problem
semantics gravitate to first order predicate logic, binary thinking
continuous math... required... how to measure anything. systems thinking.

but visualization is valuable otherwise we would not see so much of it

Cockburn communication problem - artifacts stimulate internal mental models but not Shannon... hence the endless attention to EA metamodels

===== Architecture vs program/project

“Enterprise architecture tends to be viewed as a hostile takeover by program managers and executives who have previously had a lot of independence in developing solutions for their own requirements” <<Bernard2012>>

===== EA as operating model
as opposed to business model

Bernard claims: [without EA]...leadership will not have the ability to generate clear, consistent views of the overall enterprise on an ongoing basis, they won’t be able to effectively compare business units, and the locus of power for planning and decision-making will be at the line-of-business, program, and/or system owner levels-with significant differences in how things are done and high potential for overlapping or duplicative functions and resources.

Bernard, Scott A.. An Introduction to Enterprise Architecture: Third Edition (Kindle Locations 456-459). AuthorHouse. Kindle Edition.

Of course, corporations compare business units all the time, on P&L and other enterprise metrics, without an architecture. If an enterprise is a holding company, by definition it is not seeking a common operating model.

Parsimony. What is the value of saying that EA and EOM are distinct? We have too many abstractions.

===== The hubris of architecture
The challenge of Taylorism, top-down planning, determinism...
example of antipatterns

EA arguably reluctant to see itself in terms of testing hypotheses and making bets

 BPR?

* "mess," "gratuitous complexity," etc

* all loaded terms that disregard operational reality of the moment

* why is "inconsistency" bad - need to demonstrate impact map

* hypothetical "synergies down the road" - need evidence

(above from <<Malan2010>>)

Laundry list discussions of all that's wrong with IT, with a strong implication that EA is a magical silver bullet -- but poorly documented as to how in fact it solves all this wrongness. These *are* complex systems and even in the best managed contexts they fail and degrade.

The reality is that enterprise architecture presented itself as a solution to complexity, long IT time scales, business frustration, and all kinds of badness. And when those problems were finally solved, it was not by architecture, but by Agile and DevOps practices finally overthrowing open-loop, slow feedback, batch-oriented delivery. Architects also failed to realize the emergent issue of too much enterprise work in process, instead championing the proliferation of enterprise processes and their associated queues.

Finally, architects' efficiency motivations and interest in capability mapping did not help the cause of cross-functional teams. Instead, functional silos were reinforced as supply-side "capabilities" and the  antipattern of "bringing the team to the work" was accepted as enterprise SOP - despite the growing evidence of Scrum and Agile success. The iterative, experimental narrative of Lean Startup did not originate from EA.

In particular, despite dabbling in systems theory, architects did not realize the fundamental problems of stage-gated delivery, big bang releases, and so forth. They were too sympathetic to the now-discredited Capability Maturity Model and PMBOK.

Architecture promoted the idea that standardizing platforms would make them more adaptive and agile, without sufficient caution that such standardization might have the opposite effect. Wrong lesson learned from software?

Yes tightly coupled M:M architectures are hard to change. But SPOFs also bad. When too much is centralized, the general case issues become intractable. Domain driven design...

nor was this all architecture's fault. A materialist explanation for the success of Agile and DevOps starts with Cloud, which in turn relies on Moore's Law and related dimensions of progress in manufacturing computing infrastructure.

Architecture overreach - here, we restrict to OM. Business model questions are discussed throughout other chapters. But biz arch overlaps. Finance & competitive strat is not primarily EA, even BA.


===== Arch as design vs arch as map
_the sheer absurdity of undertaking something so ambitious, on the one hand, and, foolhardy, on the other, as any kind of intentional design of so complex and poorly (and even mis-) understood an entity as an organization in a context of rapid change._ <<Malan2010>>



===== Architecture as just good design

Design is ACID. Architecture is BASE.?

Design thinking is encroaching on architecture. Enterprise design?

===== Architecture as a language for reasoning about complexity at scale

===== EA as systems thinking
hard to argue with

===== Technical debt

reinertsen critique of the concept

Scrum vs XP - Scrum as promoter of tech debt - inattention to practices... (blogs was reading 9/28/16 PM)




===== Architecture as knowledge mgmt

===== Architecture as re-emergent
Who has the best overall understanding of your digital capabilities?

Potts - CEO as arch?

Architect as wise counselor, lore-master

Sense-making across the landscape
Guidance on key decisions
Identification of opportunities otherwise un-apparent

Stewardship of longer horizon, expensive to change... where are the constraints & degrees of freedom

CoD as inherent weakness... remediable
