==== Agile and architecture
[quote, Adrian Cockcroft, former CTO Netflix]
“At Netflix, we had no central control [of the architecture] ... The goal of architecture was to create the right emergent behaviors...”

[quote, Bente et al, Collaborative Enterprise Architecture]
...we encountered companies that, despite having a fully institutionalized EA in place, were in a state close to paralysis...Although EA has reached the mainstream, a skeptical undertone with regard to its effectiveness has always existed. (p 12-13)

.Author's Note
****
As a practicing architect I can confirm that there is often friction between developers with an Agile perspective and enterprise architects. This carries through into industry discussions and conference presentations.

I think the best approach to resolving this conflict is through careful understanding of the perspective of each "side." Both have validity. I recommend framing the conversation in terms of xref:arch-impacts[architecture's value impacts].
****

The relationship between architecture (both "enterprise" and other forms of architecture) and current Agile, DevOps, and digital product development approahces is too often troubled. However, the hope is that this book has given you a set of tools for resolving these concepts in a productive way.

This chapter will challenge you by presenting the arguments directly and frankly, as two sides to a debate, concluding with thoughts on finding common ground. Note that these points of view are deliberately extreme, to make the point:

===== The hubris of architecture
_The goal of enterprise architecture is to act as a guide, perhaps a pathfinder, who takes the enterprise on a transformational journey—from an incoherent and complex world with line-of-business separation, product-specific stovepipes, legacy systems estate, and costly operation to a more rationally organized and useful state with multiservice, revenue-generating platforms and an efficient operational regime. On the way, radical surgeries may be required to eliminate duplication, reduce costs, improve reliability, and increase agility in the business. EA acts as a strategic foundation for business enablement._ <<Bente2012>> p9

Product development organizations often experience architecture and its goals as unwarranted interference, imposing a high xref:cost-of-delay[Cost of Delay] with little apparent return on investment. Architecture approvals can be required on:

* application designs
* database designs
* selection of technology products

and other such topics. When development cannot proceed without those approvals - or if the approvals come at the cost of expensive re-work - the experience can often be challenging. Bente et al warn: "if enterprise architects claim to be the only decision-making body in technical matters, there is a huge risk that they create a bottleneck...The practical consequence is that projects deliberately circumvent the enterprise architects..." <<Bente2012>> p19

And, looking more broadly at the practice and history of architecture, the case against it is strong. Enterprise architecture has presented itself as a solution to complexity, long IT time scales, business frustration, and other various IT problems. But in the past decade to the extent these issues have been solved, it has not been by architecture but by Agile and DevOps practices rethinking open-loop, slow feedback, batch-oriented delivery. Architecture has failed in many ways:

It failed to realize the emergent issue of too much enterprise work in process, instead championing the proliferation of enterprise processes and their associated queues. Fundamentally, they did not adopt enough of a systems view of IT delivery.

Architects' motivation for "efficiency" and interest in capability mapping did not help the cause of cross-functional teams. Instead, functional silos were reinforced as supply-centric "capabilities" and the antipattern of "bringing the team to the work" was accepted as enterprise standard operating procedure - despite the growing evidence of Scrum and Agile success. The iterative, experimental narrative of Lean Startup did not originate from EA.

Despite dabbling in systems theory, architects did not realize the fundamental problems of stage-gated delivery, big bang releases, and so forth. They were too sympathetic to the now-discredited Capability Maturity Model and PMBOK and cannot escape the criticism of "top down planning," which in complex systems domains too often doesn't work. Hypothetical "synergies" emerging from "common platforms" are often offered as justification for architecture, with little follow up as to actual value delivered. A sense of xref:lean-startup[Lean Startup] experimentation, of placing bets on options and testing hypotheses, is not part of the mainstream enterprise architecture understanding. 

Justifications for architecture often invoke "complex" systems. In response, architecture has often given in to the desire for a  complete "radical surgery" systems re-engineering, the temptation of the "clean slate." But as Jez Humble accurately notes,

_A common response to getting stuck in a big ball of mud is to fund a large systems replacement project. Such projects typically take months or years before they deliver any value to users, and the switchover from the old to the new system is often performed in “big bang” fashion. These projects also run an unusually high risk of running late and over budget and being cancelled. Systems rearchitecture should not be done as a large program of work funded from the capital budget. It should be a continuous activity that happens as part of the product development process. <<Humble2013>> ch10_

Architecture methodology, with its focus on identifying capability gaps for feeding into the project portfolio process, has perhaps been too prone to supporting these large, troubled programs. As we know from our earlier chapters, large system changes are inherently risky and any intervention into a complex system is better undertaken as a series of smaller, incremental changes with frequent monitoring and assessment.



Bente EA wastes

The often-minimal value of expert opinion revisited (also covered chapter 4)

Architecture HIPPOS

Entire language/mental model around gaps brings back flower & cog

A flower is not engineered to fill a gap. A cog is.

how do we know there is a gap? We have hypotheses... need to establish that there is a valuable, usable, feasible future state, and if there is progress towards it must not be delayed by queues, cycle time, etc ... need to move with alacrity... Cost of Delay outweighs much...

===== The hubris of Agile

Instead of tapping into the existing knowledge of the organization the autonomous team is prone to reinvent the wheel, and the wheel that they reinvent will not always be superior to the one we are currently using. <<Reinertsen1997>> p 104

https://philippe.kruchten.com/2011/02/13/the-elephants-in-the-agile-room/

When it  comes to system implementation, the temptation to be  fast, often under the nom de guerre of agile, can soften  quality controls and threaten product usability, reliability, safety, and lifecycle cost. <<Malan2010>>

Re: "the code is documentation"

... for systems of sufficient scope and complexity to warrant teams (of teams) working on (incremental) implementation and evolution, the sheer mass of code can make it hard to discover the essential structure from bottom-up decisions made entirely through the medium of code. <<Malan2010>>

We don't always build. Software may be eating the world, but that doesn't mean everyone employs - or should employ - software developers.

Suppose you have a business product/value prop and you know that you will be assembling complex services/products produced by others? And these services overlap? You need a strategy? Who is it that analyzes these services and their capabilities, interfaces, non-functional characteristics, and makes a final recommendation as to how you are going to bring them all into one unified system?

Point back to sourcing chapter. (And forward ref from that chapter to architecture.) Open source, COTS, Cloud, in-house... the options are bewildering and take experience. A consistent evaluation approach is important (pref. under an economic framework Reinertsen/Hubbard)

Arch as emergent is one of the most troubled Agile memes. Within one team, perhaps. Across teams - no.

You can't call for a systems perspective and then say "but the code is self documenting" on the other hand.

Cockburn quote on CCC project - disbanded & disintegrated due to relying on oral tradition

 toward a rapprochement: it  all starts with "respect the team" - and this applies to teams of architects - or one architect on a team - trouble is that architects are often spread too thin...

 Note that we compensate developers with money AND experience. Developer pressure to use a new technology should be seen in part as a demand for increased compensation. developers seeking experience, it is in part how they are compensated. this leads to conflicts over choice of tools. (good blog as well). rational framework for deciding. might go to chapter 8, resource mgmt. intersection between that & tech lifecycle is key.


 great Josh A insight: what problems can be handled w/projects vs. which need steady state capaiblities? Cynefin: simple/complicated vs complex/chaotic.. - if your strategy is to elucidate the complex you need an ongoing mental model... preserve the team -

===== Some ways forward

feedback loop between line & staff???
In the Agile world,  xref:2.05.02-kanban[Kanban] is a strongly visual system for building a shared mental model of work in process. Humans more readily understand complex systems through diagrams.


Amazon Obidos example, strangler pattern.
* Start by delivering new functionality—at least at first
* Do not attempt to port existing functionality unless it is to support a business process change
* Deliver something fast
* Design for testability and deployability
* Architect the new software to run on a PaaS

====== Scaling & architecture


====== "Coding architects?"
Primarily in SW domain
But virtualization now makes it possible for all archs to be hands-on, even w/pkgs

<<Cohn2010>> chapter on architect role - confusion of software & enterprise arch

keep EAs off product teams, agree but they set overall direction @ portfolio level difficult for them to stay hands on

* systems too big for 1 team
* features that are too complex to be implemented in 1 iteration
* features that cause too much org chg mgmt

EA "process"

Another possible objection against agile methods is that the processes in EA, and in the enterprise generally, are simply not operating with a time window of the typical sprint length of three weeks. This, of course, is true. But it is at closer inspection not a counter-argument against the application of agile principles to EA—just the opposite. The long process cycles add to EA's lack of transparency and promote a silo mentality. Agile techniques can help here. <<Bente2012>> - queuing and fast feedback

Lot of confusion in the literature about sol arch vs EA.

====== Arch kata

Our experience is that standardization on a particular toolchain or technology stack is neither necessary nor sufficient for achieving enterprise architecture goals such as enabling teams to respond rapidly to changing requirements, creating high-performance systems at scale, or reducing the risk of intrusion or data theft. Just like we drive product and process innovation through the Improvement Kata, we can drive architectural alignment through it too. Architectural goals—for example, desired performance, availability, and security—should be approached by iteratively specifying target conditions at the program level. Following the Principle of Mission, set out a clear vision of the goals of your enterprise architecture without specifying how the goals are to be achieved, and create a context in which teams can determine how to achieve them through experimentation and collaboration.   <<Humble2013>> ch10

preparing along the way understand inventories and dependencies - importance of Bezos mandate to the dependency question - if there is one battle you fight, make it that one -

the importance of documentation - speech to text, text analytics... image recognition... what might the future hold? At least get technical writers... don't make developers write...

====== Architecture and digital exhaust
we can assess the degree to which architecture is influencing real choices

Agile & docs "In an agile project, explicit care must be taken to ensure proper documentation—for example, by stating it as part of the condition of satisfaction of a user story or in the definition of done" <<Bente2012>> p 170


====== DevOps assets to architecture

If you started from day 1 with source, build, & package mgmt, and have kept it clean, you have a great asset



anchor:TLM-CoD-worked[]

===== Architecture, queues, and Cost of Delay

worked TLM example

TLM should route via corp governance & perf mgmt, align w/vendor mgmt... find sources on how these processes work in non IT domains... (have already discussed in book)

review Reinertsen

Bente p 194 looks @ arch process optimization - local optima, bad. Goes down the work/wait alley and DSM (anti-rework). Limitations.

Also, IT finance typically doesn't appear...

All the coordination mechs can be applied... cadence/synch - queue understanding, CoD critical


Toyota Kata and EA  - importance of target condition

====== NOTES

Cockcroft quote

Cathedral / bazaar



Bente's four perspectives & eight caricatures

[quote, Bente et al]
With regard to the nature of complex systems, it is not advisable to search for the "optimal enterprise architecture." Optimality is always relative to an environment, and the frame conditions are likely to change. Hence it is better to accept certain ugly spots of the IT landscape and strengthen the viability of the whole, which means developing and using capabilities such as being able to learn, solve problems, adapt, or absorb disruptions.

 critical importance of not confusing solutions with EA. Scale matters.

 from bente: Anti-patterns in EA and architecture in general can be found, for instance, in Kruchten (2008), Mar and Spacey (2011), Ambler, Nalbone. and Vizdos (2005), and Coplien and Harrison (2005).
