==== Architecture domains

ifdef::collaborator-draft[]

****
*Collaborative*

 Status: This and later sections are in active development as of 5 September 2016. Expect volatility.

include::../../../collab-links.adoc[]

****

endif::collaborator-draft[]


One of the most widely known visual depictions of enterprise architecture is the Zachman framework.

Zachman as intro

matrix illuminates question of "EA v biz etc"

people align w/columns and w/rows

biz v it = demand v supply

===== Business architecture
Business architecture offers views of the business that are un
available from other sources, including IT. Business architecture
can tell you what is being done, by which business units, for cer
tain customers, involving various products, via certain processes,
involving selected business information. Business
architecture
generated blueprints serve as the basis for root cause analysis of
critical business requirements while providing the foundation for
establishing a solution-oriented roadmap that leaves the specula
tion and guesswork by the roadside. In a word, business architec
ture delivers "transparency" to a wide variety of internal teams,
roles and business units. Ulrich p 195

The repeatable development of a
structured,
consensus,
representation of
demand-side concepts
essential to the organization’s goals.

Things we DO NOT expect to see in business architecture
Specific technology products (Oracle 11g)
Specific devices (NASRVDCPRD01234.att.com, serial # TRN26543FJDC)
Software architectures (.Net assembly, REST API, Java object)
Detailed deployment diagrams
Specific project plans
Flowcharts beyond large-grained lifecycles

Process and its relatives
Ordered (at least partially), “glass box,” countable
Value chain
Value stream
Business process
Workflow
Procedure
Task
Step
Processes CROSS Functions. (Michael Hammer)

Function and its relatives
Unordered, “black box,” steady state
Function
Capability
Service (sometimes)
Often implies hierarchy

Data and its relatives
The universe of discourse.
Ontology
Semantics & Semantic Web
Objects (sometimes)
Data subjects & records
Entities/attributes/relationships
Tables/columns/constraints

System and its relatives
A relatively fixed form instantiation of definite methods, often based on general purpose computing machinery. Practically relevant. Obtainable and operable.  (You can buy one of these.)
Application (sometimes)
Service (sometimes)
Technology product



===== Solutions architecture

====== Software architecture

[quote, Grady Booch]
Architecture represents the significant design decisions that shape a system, where significant is measured by cost of change.

====== "Coding architects?"
Primarily in SW domain
But virtualization now makes it possible for all archs to be hands-on, even w/pkgs

<<Cohn2010>> chapter on architect role - confusion of software & enterprise arch

keep EAs off product teams, agree but they set overall direction @ portfolio level difficult for them to stay hands on

====== Data architecture
ch 11 backref

===== Technical architecture

 ===== Enterprise architecture
all of the above
