==== Architecture standards

This section briefly describes a number of key architecture standards for the student's reference.

===== Business architecture

NOTE: We previously discussed the Business Analysis Body of Knowledge. Although they have similar names, BABOK and BIZBOK are distinct in terms of content and their sponsoring organizations.

* The _Business Analysis Body of Knowledge_ (BABOK), from the International Institute of Business Analysis <<IIBA2015>>, focuses on business analysis: "the practice of enabling change in an enterprise by defining needs and recommending solutions that deliver value to stakeholders."
* The Business Architecture Body of Knowledge (BIZBOK) is a broader, more diverse set of guidance from the BA Guild<<BAGuild2016>>. It defines business architecture as "a blueprint of the enterprise that provides a common understanding of the organization and is used to align strategic objectives and tactical demands."

anchor:deeper-TOGAF[]

===== TOGAF
The Open Group Architecture Framework is a 

===== Archimate
Not just a drawing spec... as a simplification of Zachman, more practical


===== Governmental frameworks


===== Industry verticals
