=== Chapter 12: Architecture and Portfolio

ifdef::collaborator-draft[]

****
*Collaborative*

 Status: Chapter 12 is in active development as of 5 September 2016. Expect volatility.

include::../../../collab-links.adoc[]

****

endif::collaborator-draft[]

==== Introduction to Chapter 12

Regardless of whether you started off as a digital startup, or are an older corporation now digitally transforming, your world is complex and getting more so.

Decisions that might have been made quickly and casually by a product or project team become more difficult, due to increasing challenges both internal and external. Decisions made years ago come back to haunt current strategies with a vengeance. With scale, management needs some way of making sense across digital operations of mind-numbing complexity. Should we invest in 15 new internally-developed microservices, or sunset 12 existing ones and implement a commercial package developed by people we trust? When we have 1500 applications or services in our portfolio, how do we know that proposed #1501 is not redundant or outright conflicting with existing services?

Architecture provides tools to manage such problems, but doing so is difficult and controversial. How do we know that our understanding of the digital operation is current and up to date? How much should we spend on keeping it so? What happens when management decides to set direction using these same abstractions, and architects find themselves now enforcing what had originally started as mere explanation and sense-making?

Vendor relationships become a two-edged sword, providing increased value with access to higher levels of vendor resources, but at the cost of increased lock-in. Pure open-source strategies inevitably give way to monetized relationships, as the risk of not having support becomes unacceptable.

Portfolio management in terms of information technology means looking at long-lived IT investments in terms of their overall benefit, cost, and risk to the organization. This can and should be done regardless of whether the IT investment is external or internal facing. Products, services, and applications are the most useful portfolio constructs, although assets, technology products, and even projects also figure into longer-horizon value management. Enterprise architecture benefits from a tight alignment with IT portfolio management, as well; it's not clear that a firm boundary between them could be drawn.

This chapter is in a way summative: it reflects all of the concerns discussed through the previous 11 chapters. Every chapter represents topics of interest to the architect. Now, we discuss a language and way of thinking to bring these concerns all together.

IMPORTANT: As with other chapters in the later part of this book, we are going to introduce this topic "on its own terms." We will then add additional context and critique in subsequent sections.

 Decide: get more technical in this part as well, as we did in previous?

===== Chapter 12 outline

* Value of architecture - impact mapping

* Defining architecture
  - Enteprise
  - Business
  - Data
  - Solutions
  - Technical

* Architecture processes and practices
** But what do architects *do*?
** The problems with "method" - waterfall...
** The repository problem

* "Service-izaton" - pros and cons
 - need in higher ed, health -

* Portfolio management

* The digital architecture

* Topics

****
Sidebar: IT analytics experts
Magennis, Cantor, etc
****

===== Chapter 12 learning objectives

* Identify various use cases for IT analytics
** Identify the basic types of IT architecture
* Describe basic architectural practices
* Characterize some typical challenges for architects

* Identify current approaches to understanding complex systems and their failure modes
