==== Agile and architecture

Cockcroft quote

Cathedral / bazaar

When it  comes to system implementation, the temptation to be  fast, often under the nom de guerre of agile, can soften  quality controls and threaten product usability, reliability, safety, and lifecycle cost. <<Malan2010>>

Re: "the code is documentation"

... for systems of sufficient scope and complexity to warrant teams (of teams) working on (incremental) implementation and evolution, the sheer mass of code can make it hard to discover the essential structure from bottom-up decisions made entirely through the medium of code. <<Malan2010>>

Bente's four perspectives & eight caricatures

[quote, Bente et al]
With regard to the nature of complex systems, it is not advisable to search for the "optimal enterprise architecture." Optimality is always relative to an environment, and the frame conditions are likely to change. Hence it is better to accept certain ugly spots of the IT landscape and strengthen the viability of the whole, which means developing and using capabilities such as being able to learn, solve problems, adapt, or absorb disruptions.

 critical importance of not confusing solutions with EA. Scale matters.


===== The hubris of architecture

[quote, Bente et al, Collaborative Enterprise Architecture]
...we encountered companies that, despite having a fully institutionalized EA in place, were in a state close to paralysis...Although EA has reached the mainstream, a skeptical undertone with regard to its effectiveness has always existed. (p 12-13)

from bente: Anti-patterns in EA and architecture in general can be found, for instance, in Kruchten (2008), Mar and Spacey (2011),
Ambler, Nalbone. and Vizdos (2005), and Coplien and Harrison (2005).

The challenge of Taylorism, top-down planning, determinism...
example of antipatterns

EA arguably reluctant to see itself in terms of testing hypotheses and making bets

BPR?

* "mess," "gratuitous complexity," etc

* all loaded terms that disregard operational reality of the moment

* why is "inconsistency" bad - need to demonstrate impact map

* hypothetical "synergies down the road" - need evidence

(above from <<Malan2010>>)

Laundry list discussions of all that's wrong with IT, with a strong implication that EA is a magical silver bullet -- but poorly documented as to how in fact it solves all this wrongness. These *are* complex systems and even in the best managed contexts they fail and degrade.

The reality is that enterprise architecture presented itself as a solution to complexity, long IT time scales, business frustration, and all kinds of badness. And when those problems were finally solved, it was not by architecture, but by Agile and DevOps practices finally overthrowing open-loop, slow feedback, batch-oriented delivery. Architects also failed to realize the emergent issue of too much enterprise work in process, instead championing the proliferation of enterprise processes and their associated queues. Fundamentally, they did not adopt enough of a systems view of IT delivery. That took Gene Kim and others.

Architects' efficiency motivations and interest in capability mapping did not help the cause of cross-functional teams. Instead, functional silos were reinforced as supply-side "capabilities" and the  antipattern of "bringing the team to the work" was accepted as enterprise SOP - despite the growing evidence of Scrum and Agile success. The iterative, experimental narrative of Lean Startup did not originate from EA.

In particular, despite dabbling in systems theory, architects did not realize the fundamental problems of stage-gated delivery, big bang releases, and so forth. They were too sympathetic to the now-discredited Capability Maturity Model and PMBOK.

Architecture promoted the idea that standardizing platforms would make them more adaptive and agile, without sufficient caution that such standardization might have the opposite effect. Wrong lesson learned from software?

Yes tightly coupled M:M architectures are hard to change. But SPOFs also bad. When too much is centralized, the general case issues become intractable. Domain driven design...

nor was this all architecture's fault. A materialist explanation for the success of Agile and DevOps starts with Cloud, which in turn relies on Moore's Law and related dimensions of progress in manufacturing computing infrastructure.

===== The hubris of Agile

https://philippe.kruchten.com/2011/02/13/the-elephants-in-the-agile-room/

We don't always build. Software may be eating the world, but that doesn't mean everyone employs - or should employ - software developers.

Suppose you have a business product/value prop and you know that you will be assembling complex services/products produced by others? And these services overlap? You need a strategy? Who is it that analyzes these services and their capabilities, interfaces, non-functional characteristics, and makes a final recommendation as to how you are going to bring them all into one unified system?

Point back to sourcing chapter. (And forward ref from that chapter to architecture.) Open source, COTS, Cloud, in-house... the options are bewildering and take experience. A consistent evaluation approach is important (pref. under an economic framework Reinertsen/Hubbard)

EA wastes... have covered elsewhere

You can't call for a systems perspective and then say "but the code is self documenting" on the other hand.

Cockburn quote on CCC project - disbanded & disintegrated due to relying on oral tradition

===== Solution arch consequences to scaling agile
* systems too big for 1 team
* features that are too complex to be implemented in 1 iteration
* features that cause too much org chg mgmt

EA "process"

Another possible objection against agile methods is that the processes in EA, and in the
enterprise generally, are simply not operating with a time window of the typical sprint length of three
weeks. This, of course, is true. But it is at closer inspection not a counter-argument against the appli
cation of agile principles to EA—just the opposite. The long process cycles add to EA's lack of trans
parency and promote a silo mentality. Agile techniques can help here. <<Bente2012>> - queuing and fast feedback

Lot of confusion in the literature about sol arch vs EA.

===== A worked example of architecture cost of delay vs TLM


===== Avoiding the big batch of EA "cleanup" that never works

A common response to getting stuck in a big ball of mud is to fund a large systems replacement project. Such projects typically take months or years before they deliver any value to users, and the switchover from the old to the new system is often performed in “big bang” fashion. These projects also run an unusually high risk of running late and over budget and being cancelled. Systems rearchitecture should not be done as a large program of work funded from the capital budget. It should be a continuous activity that happens as part of the product development process. <<Humble2013>> ch10

 Amazon Obidos example, strangler pattern.
 * Start by delivering new functionality—at least at first
 * Do not attempt to port existing functionality unless it is to support a business process change
 * Deliver something fast
 * Design for testability and deployability
 * Architect the new software to run on a PaaS

Our experience is that standardization on a particular toolchain or technology stack is neither necessary nor sufficient for achieving enterprise architecture goals such as enabling teams to respond rapidly to changing requirements, creating high-performance systems at scale, or reducing the risk of intrusion or data theft. Just like we drive product and process innovation through the Improvement Kata, we can drive architectural alignment through it too. Architectural goals—for example, desired performance, availability, and security—should be approached by iteratively specifying target conditions at the program level. Following the Principle of Mission, set out a clear vision of the goals of your enterprise architecture without specifying how the goals are to be achieved, and create a context in which teams can determine how to achieve them through experimentation and collaboration. We cover alternatives to standardization and related issues in more detail in Chapter 14. <<Humble2013>> ch10


preparing along the way
understand inventories and dependencies - importance of Bezos mandate to the dependency question - if there is one battle you fight, make it that one -
the importance of documentation - speech to text, text analytics... image recognition... what might the future hold? At least get technical writers... don't make developers write...

If you started from day 1 with source, build, & package mgmt, and have kept it clean, you have a great asset

 is EA using the right tools? systems theory, semantics vs dynamics. Also, IT finance typically doesn't appear...

 Review SAFE on architecture, also Reinertsen

 All the coordination mechs can be applied... cadence/synch - queue understanding, CoD critical

 Agile & docs "In
an agile project, explicit care must be taken to ensure proper documentation—for example, by stating it
as part of the condition of satisfaction of a user story or in the definition of done" <<Bente2012>> p 170

 Bente p 194 looks @ arch process optimization - local optima, bad. Goes down the work/wait alley and DSM (anti-rework). Limitations.

 Toyota Kata and EA  - importance of target condition

 The often-minimal value of expert opinion revisited (also covered chapter 4)
