==== Architecture standards
This section briefly describes a number of key architecture standards for the student's reference.

===== Business architecture

NOTE: We previously discussed the Business Analysis Body of Knowledge. Although they have similar names, BABOK and BIZBOK are distinct in terms of content and their sponsoring organizations.

* The _Business Analysis Body of Knowledge_ (BABOK), from the International Institute of Business Analysis <<IIBA2015>>, focuses on business analysis: "the practice of enabling change in an enterprise by defining needs and recommending solutions that deliver value to stakeholders."
* The Business Architecture Body of Knowledge (BIZBOK) is a broader, more diverse set of guidance from the BA Guild<<BAGuild2016>>. It defines business architecture as "a blueprint of the enterprise that provides a common understanding of the organization and is used to align strategic objectives and tactical demands."

anchor:deeper-TOGAF[]

===== TOGAF
The Open Group Architecture Framework is a general purpose framework and method, currently in Version 9 <<Open2009>>. TOGAF dates from 1995 and is based on even earlier work from the US Department of Defense, dating back to 1986.

===== Archimate
Archimate is an architectural notation specification, now owned by The Open Group.

anchor:vertical-standards[]

===== Industry verticals
Industry sectors often develop architectural representations of their concerns. Examples include:

* Association for Retail Standards (National Retail Federation)
* Banking Information Architecture Network (BIAN)
* The Enhanced Telecom Operating Model and related work of the Tele-Management Forum
* The ACORD architecture for insurance
* The  Exploration, Mining, Metals and Minerals (EMMM™) Forum of The Open Group

===== Governmental frameworks

Governmental architecture frameworks are often used to standardize architecture, for example:

* The U.S. Federal Enterprise Architecture Framework (FEAF)
* The U.S. Department of Defense Architecture Framework (DODAF)
* The U.K. Ministry of Defense Architecture Framework (MODAF)

_This section to be expanded in future editions._
