==== Architecture practices

Before we get into a detailed discussion of architecture domains, let's talk in general about what architects do and some common practices and themes.

As we mentioned xref:defining-ea[previously], architecture itself as a term shows up in many ways, as role, artifact, program, and organization.


.Author's corner
****
What do architects do, actually?

I was a Lead Architect (job class Systems Architect 6) for Wells Fargo for 6 years. This is a director-level position, and I was ultimately awarded the VP title, which in financial services tends to be honorary. (I never managed a large organization.) My assigned domain was the "business of IT," including systems management, service management, portfolio management, and the data, processes, and tools of architecture itself.

Across an annual IT spend of around $5 billion, many of course were involved in all these questions, but I was a nexus and was often called on to lead workshops and discussions with senior executives. These folks were typically at the "2-down" level from the CIO, that is, executives reporting to one of the CIO's direct reports, themselves leading large teams of teams. They called me in when they were struggling with managing one of the larger IT shops on the planet, especially when it came to processes, data, and systems *internal to the IT* organization. (I always admit, I never learned that much about banking; there was plenty to do just coordinating that IT pipeline and the thousands of systems it was delivering.)

Comparing my activities during those 6 years with how industry standards (such as TOGAF) describe architecture is interesting. Building models and "architectures" was only a small part of my work. I found myself involved in, or playing the role of:

* IT strategic planning
* IT portfolio management
* Program architect (e.g. Application Decommissioning and Portfolio Rationalization for the Wells Fargo/Wachovia merger)
* Technology standards governance
* RFP owner for selecting new technologies
* Data governance
* Vendor product analysis (often in liaison with analyst firms such as Gartner Group)
* Center of Excellence for data, process (BPM), and systems analysis and modeling
* Solutions design standards and patterns
* Continuous service improvement
* Major incident root cause analysis
* Project governance
* IT ombudsman and process troubleshooter ("you architects say the process should work this way, but it doesn't - help me")
* Shuttle diplomat - driving agreement between deeply conflicted business units or individuals, where relationships had broken down.

If I had to characterize the important skills for this role, they would start with communication and facilitation. In terms of the principles discussed in this book, the architecture team was a mechanism for synchronizing across the organization. It definitely fit the classic definition and value proposition of a xref:arch-as-staff[staff organization].
****

====== Architecture and governance

Enterprise architecture has a clear relationship to xref:gov-chap[governance] as we discussed it in Chapter 10. It provides a framework for managing xref:tech-prod-lifecycle[long-lifecycle concerns] and various forms of enterprise xref:risk-management[risk], especially as related to digital and IT systems.

EA therefore may have a role in defining xref:how-policy-begins[policies], especially at the mid-tier of the xref:policy-hierarchy[policy hierarchy] - neither the highest enterprise principles, nor the most detailed technical standards, but rather policies and standards related to:

* Choice of certain enterprise products expected to be heavily leveraged (e.g. common database and middleware products)
* Design patterns for solving recurring requirements (e.g. user authentication, load balancing, etc)
* xref:system-of-record[System of Record]
 identification and enforcement

As discussed in xref:policy-hierarchy[Chapter 10], there needs to be traceability from tactical standards to strategic codes and principles. The preference for a given database should not be a policy, but having a process that establishes such a preference *would* be -- that is, a policy should exist saying (for example) "there shall be a Technology Lifecycle Management process with the following objectives and scope." Where appropriate, such policies might also be linked to specific risks as xref:controls[controls] or xref:enablers[enablers].

It's important to have some sort of sunset mechanism. As Bente et al note, _Many EA-originated policies that appear obsolete today have not always been meaningless. Most probably they have emerged as the architecture group's overreactions to unlikely-to-recur situations that they experienced in their organization in the past. A frequent example is the uncontrolled proliferation of newly hyped technologies by the IT crowd, and the EA group's rigid attempt to reinstitute order. Once the technology has matured, the EA rules often appear overly strict and suppress a flexible use of the appropriate technology._ <<Bente2012>> p19

The issue with the quote above is that the overall benefits of having (for example) a Technology Lifecycle Management process are not usually quantified in terms of cost and risk avoidance. Without an overall governance mandate and value proposition, Enterprise Architecture activities may seesaw in response to the "issue of the moment." This is not a recipe for sustainable architecture; whose most important value proposition lies in the long term.


arch review boards as xref:coord-struct[coordination structures]

===== Architecture as a management program
Bernard fig 1-4: Governance, Framework, Methodology, Best Practices, Standards, Artifacts

Activities/Bernard: (loc 561)
* Management program
* analysis & design method - how to factor out?? key weakness. waterfall.

As a management program, EA provides:     
Strategic Alignment: Connects goals, activities, and resources    
Standardized Policy: Resource governance and implementation     
Decision Support: Financial control and configuration management   
Resource Oversight: Lifecycle approach to development/management

As an analysis and design method, EA provides:     
EA Approach: The framework, analysis/design method, and artifact set
Current Views: Views of as-is strategies, processes, and resources
Future Views: Views of to-be strategies, processes, and resources
EA Management Plan: A plan to move from the current to the future EA

Bernard, Scott A.. An Introduction to Enterprise Architecture: Third Edition (Kindle Locations 585-601). AuthorHouse. Kindle Edition.

Got to bring in TOGAF

so, without EA... all this stuff is NOT getting done?

EA as policy vehicle... how is it that policies are enforced? process gating?

without EA.. how technical standards? how is a config image determined to be gold?

risk mgmt can't do it alone

In Bernard - goals & initiatives are above products & services - showing multiple product orientation - indicative of emergence phase

Entire language/mental model around gaps brings back flower & cog

A flower is not engineered to fill a gap. A cog is.

how do we know there is a gap? We have hypotheses... need to establish that there is a valuable, usable, feasible future state, and if there is progress towards it must not be delayed by queues, cycle time, etc ... need to move with alacrity... Cost of Delay outweighs much...

===== Modeling and visualization
The true measure of the value of a model is whether it actually influences behavior. Smith/Reinertsen 1998 p46.

Architect as visual facilitator

“At Netflix, we had no central control” of the architecture,
“The goal of architecture was to create the right emergent behaviors,”
“Our architecture was changing faster than you can draw it… As a result, it wasn’t useful to try to draw it.”

*Architect as visual thinker*

EA needs catalogs and matrices maintained. diagrams? it's questionable. every so often there is a ritual expression of a catalog as nested boxes. Of questionable utility. The graph complexity bogs down representation of the matrices.


Because of these facts, it is useful to understand some of the fundamentals of how humans interpret symbolic data.

(*** re-read and summarize Moody)

More on these in future chapters

Moody, but what are his sources?
http://simplybrainy.com/wp-content/uploads/2011/01/2008-Int-Vis-Other-Senses-All-Illustrations.pdf

Further reading on visual processing:

Moody
Tufte & others (that comparison paper cited by Moody)

complex graph...

But Cockcroft: if it changes too quickly, how to capture/represent?

formalisms don't give a good sense of scale - give a visual example

arch formalisms weak on dynamics - semantics vs dynamics problem semantics gravitate to first order predicate logic, binary thinking continuous math... required... how to measure anything. systems thinking.

but visualization is valuable otherwise we would not see so much of it

Cockburn communication problem - artifacts stimulate internal mental models but not Shannon... hence the endless attention to EA metamodels


The big picture is part of the standard mindset of EA, which
everyoneimmediatelyassociateswiththeactivitiesofanenterprisearchitect.
However, many of these big pictures you meet in practice have been over-
abstracted to the point of insignificance and no longer address any relevant
question.<<Bente2012>> p16

"semantic distortions" - simple example: equal-sized boxes on an EA capability map.

the EA's role is to facilitate discussions by abstracting and visualizing powerfully so that decisions are illuminated.

usually, the resulting diagrams are only good tactically.


illustrate: diagrams vs reporting, isometric catalog/matrix/diagram
why draw boxes when a textual report is all that is needed (e.g. Bente p52)


===== The "rationalization" quest
are the economics well understood?
One core question decided by governance is how much autonomy is granted to business units or geographical regions. In case this autonomy is high, would a quest for high IT integration and standardization not be like fighting windmills? <<bente2012>> p.45 and cross ref ch 1

====== application rationalization

====== Data & info

====== TLM
****
*Bad times at Airbus*

In 2006, (Ulrich)

TLM governance

****


****
[quote, Anonymous]
A foolish consistency is the hobgoblin of little minds.

*The folly of letting TLM dominate*

Henrik Kniberg tells the story of one of his most successful projects — a system built for the Swedish police that allowed them to use laptops in the field — and what happened afterwards <<Kniberg2011>>. Because the project was extremely urgent, the group was allowed to use an agile approach and break out of the traditional organizational culture. Everything went well, the police organization viewed it as a success, and the project even won a “project of the year” award.

What came next, however, was even more interesting. A high-level decision was made to rebuild from scratch that same system police had used in the field, using Siebel. This was part of a standardization effort to reduce the complexity and number of systems. Not only was the decision made to use a technology that the development team didn’t agree with, but it was decided to use a more traditional, sequential project-management approach to development. Development took a couple years and when it finally rolled out, it was a disaster because the police found it to be slow and clumsy and basically unusable. Making the change even more difficult was that the police preferred their existing system, which worked. Kniberg estimates that this cost the Swedish police more than £1 billion.

in http://www.infoq.com/resource/minibooks/why-agile-works/en/pdf/InfoQ-Why-Agile-Works-Mini-book.pdf
****

1 billion pounds ($1.6B) would have bought a lot of support & vendor leverage for the "nonstandard" technologies.

Lifecycle management can extend to internal products/services

EA provides guidance about what technologies are a strategic fit, which ones are deprecated, and which are emerging. <<Bente2012>> p8

Case study: The version control controversy: service vs TLM

if enterprise architects claim to be the only decision-making body
in technical matters, there is a huge risk that they create a bottleneck, if decisions take ages due to pending strategic issues, imminent changes in the business model, and so forth, IT projects can be seriously delayed. The practical consequence is that projects deliberately circumvent the enterprise architects—for example, by choosing less suitable technologies not managed by the EA group.<<Bente2012>> p19

Note that we compensate developers with money AND experience. Developer pressure to use a new technology should be seen in part as a demand for increased compensation. developers seeking experience, it is in part how they are compensated. this leads to conflicts over choice of tools. (good blog as well). rational framework for deciding. might go to chapter 8, resource mgmt. intersection between that & tech lifecycle is key.

EA makes the decision to insource or outsource

===== Repositories and knowledge management

backref to ch 11?

Agile & docs "In an agile project, explicit care must be taken to ensure proper documentation—for example, by stating it as part of the condition of satisfaction of a user story or in the definition of done" <<Bente2012>> p 170

Catalogs - Need for registration process for subjective concepts - decision authority

====== The repository question

CMDBs, metadata, EA

====== DevOps assets to architecture

If you started from day 1 with source, build, & package mgmt, and have kept it clean, you have a great asset

====== Metamodels and ontologies
app v svc def'n
runs into domain driven design problems if not careful

Canon law disputes

"standard EA language and methodology is especially helpful in large, complex enterprises that are geographically dispersed, and which may have multiple social and work cultures that have promoted different ways of doing things." <<Bernard

Bernard, Scott A.. An Introduction to Enterprise Architecture: Third Edition (Kindle Locations 1147-1149). AuthorHouse. Kindle Edition.
