==== Architecture practices


===== Architecture as a manaagement program
Bernard fig 1-4: Governance, Framework, Methodology, Best Practices, Standards, Artifacts

Activities/Bernard: (loc 561)
* Management program
* analysis & design method - how to factor out?? key weakness. waterfall.

As a management program, EA provides:     Strategic Alignment: Connects goals, activities, and resources     Standardized Policy: Resource governance and implementation     Decision Support: Financial control and configuration management     Resource Oversight: Lifecycle approach to development/management As an analysis and design method, EA provides:     EA Approach: The framework, analysis/design method, and artifact set     Current Views: Views of as-is strategies, processes, and resources     Future Views: Views of to-be strategies, processes, and resources     EA Management Plan: A plan to move from the current to the future EA

Bernard, Scott A.. An Introduction to Enterprise Architecture: Third Edition (Kindle Locations 585-601). AuthorHouse. Kindle Edition.

so, without EA... all this stuff is NOT getting done?

EA as policy vehicle... how is it that policies are enforced? process gating?

without EA.. how technical standards? how is a config image determined to be gold?

risk mgmt can't do it alone

In Bernard - goals & initiatives are above products & services - showing multiple product orientation - indicative of emergence phase

Entire language/mental model around gaps brings back flower & cog

A flower is not engineered to fill a gap. A cog is.

how do we know there is a gap? We have hypotheses... need to establish that there is a valuable, usable, feasible future state, and if there is progress towards it must not be delayed by queues, cycle time, etc ... need to move with alacrity... Cost of Delay outweighs much...

===== The repository question

CMDBs, metadata, EA

===== "Coding architects?"
Primarily in SW domain
But virtualization now makes it possible for all archs to be hands-on, even w/pkgs

===== Architecture, governance, process


===== TLM
Case study: The version control controversy: service vs TLM
