==== Topics
 ===== digital strategy

anchor:complex-systems[]
 ===== complex systems



* Describe Snowden's Cynefin and its major elements
* complexity (w/r/t Burgess)
* stability, state, etc
* complex system failures (Allspaw sidebar?)
* antifragility
* Cynefin
* self-steering, autopoeisis
* post-industrial

 is EA using the right tools? systems theory, semantics vs dynamics.

 ====== EA as systems thinking
hard to argue with but evidence is limited

****
Sidebar: Introducing Burgess.
****

****
Sidebar: Introducing Snowden & Taleb.
****

* Postscript: Thought experiment on complete mainstreaming of IT

 ===== EA and design thinking

 Design thinking is encroaching on architecture. Enterprise design?
_the sheer absurdity of undertaking something so ambitious, on the one hand, and, foolhardy, on the other, as any kind of intentional design of so complex and poorly (and even mis-) understood an entity as an organization in a context of rapid change._ <<Malan2010>>

 ===== metamodels


 ===== SAFE and architecture
 Review SAFE on architecture, also Reinertsen

 ===== Sol Arch for EA


 ===== misc
 "Architecture of software is a collection of design decisions that are expensive to change." <<Ran2001>>

 [quote, Ruth Malan]
 For enduring competitive advantage, the organization needs to seek leverage across its products and/or services and to create strategic capabilities that are hard to imitate because they rely on a mix of process, technology, skills, resources, facilities, culture, and even history <<Malan2005>>




 All arch is design not all design is arch (Booch)
