==== Conclusion

===== Architecture as re-emergent
Who has the best overall understanding of your digital capabilities?

Potts - CEO as arch?

Architect as wise counselor, lore-master

Sense-making across the landscape
Guidance on key decisions
Identification of opportunities otherwise un-apparent

Stewardship of longer horizon, expensive to change... where are the constraints & degrees of freedom

CoD as inherent weakness... remediable

Conclusion placeholder

===== Discussion questions



===== Research & practice

* Compare and contrast business model versus operating model, and in the same analysis consider the distinction between enterprise architecture and business architecture. Can enterprise architecture be equated with the operating model? If business architecture is a subset of enterprise architecture, does that mean it also is primarily concerned with the operating model? Or is business architecture also concerned with the business model?

===== Further reading

Lean Enterprise, Humble

*Books*

*Articles*

https://softvis.files.wordpress.com/2010/12/gradybooch-whydontdevelopersdrawdiagrams-softvis2010.pdf

http://www.ruthmalan.com/Journal/2010/2010JournalOctober.htm#Why_Dont_Developers_Draw_Diagrams

http://www.ruthmalan.com/Journal/2010/2010JournalOctober.htm#Reworking_some_of_the_ideas:_Why_Dont_Developers_Draw_Diagrams

http://www.computer.org/csdl/mags/so/2011/01/mso2011010006-abs.html

http://www.ruthmalan.com/journal/2011/2011JournalSeptember.htm#When_Are_Diagrams_Useful

https://www.itpreneurs.com/blog/agile-togaf-and-enterprise-architecture-will-they-blend/

* http://www.forbes.com/sites/jasonbloomberg/2014/07/11/is-enterprise-architecture-completely-broken/#1febba552f30

* http://www.forbes.com/sites/jasonbloomberg/2014/07/23/agile-enterprise-architecture-finally-crosses-the-chasm/#224402cb3c77

https://www.microsoft.com/en-us/research/wp-content/uploads/2016/02/p557-cherubini.pdf[Let’s Go to the Whiteboard: How and Why Software Developers Use Drawings]

*Videos*

*Professional*
