==== Architecture practices


===== Architecture as a manaagement program
Bernard fig 1-4: Governance, Framework, Methodology, Best Practices, Standards, Artifacts

Activities/Bernard: (loc 561)
* Management program
* analysis & design method - how to factor out?? key weakness. waterfall.

As a management program, EA provides:     Strategic Alignment: Connects goals, activities, and resources     Standardized Policy: Resource governance and implementation     Decision Support: Financial control and configuration management     Resource Oversight: Lifecycle approach to development/management As an analysis and design method, EA provides:     EA Approach: The framework, analysis/design method, and artifact set     Current Views: Views of as-is strategies, processes, and resources     Future Views: Views of to-be strategies, processes, and resources     EA Management Plan: A plan to move from the current to the future EA

Bernard, Scott A.. An Introduction to Enterprise Architecture: Third Edition (Kindle Locations 585-601). AuthorHouse. Kindle Edition.

so, without EA... all this stuff is NOT getting done?

EA as policy vehicle... how is it that policies are enforced? process gating?

without EA.. how technical standards? how is a config image determined to be gold?

risk mgmt can't do it alone

In Bernard - goals & initiatives are above products & services - showing multiple product orientation - indicative of emergence phase

Entire language/mental model around gaps brings back flower & cog

A flower is not engineered to fill a gap. A cog is.

how do we know there is a gap? We have hypotheses... need to establish that there is a valuable, usable, feasible future state, and if there is progress towards it must not be delayed by queues, cycle time, etc ... need to move with alacrity... Cost of Delay outweighs much...

===== The repository question

CMDBs, metadata, EA

===== "Coding architects?"
Primarily in SW domain
But virtualization now makes it possible for all archs to be hands-on, even w/pkgs

===== Architecture, governance, process

Many EA-originated policies that appear obsolete today have not always been meaningless. Most probably they have emerged as the architecture group's overreactions to unlikely-to-recur situations that they experienced in their organization in the past. A frequent example is the uncontrolled prolif
eration of newly hyped technologies by the IT crowd, and the EA group's rigid attempt to reinstitute order. Once the technology has matured, the EA rules often appear overly strict and suppress a flexible use of the appropriate technology. <<Bente2012>> p19

Bente is correct to focus on collaborative issues. but the overall benefits of having (for example) a TLM are not usually quantified in terms of cost and risk avoidance. This can be done. TLM should route via corp governance & perf mgmt, align w/vendor mgmt... find sources on how these processes work in non IT domains... (have already discussed in book)

===== visualization
The big picture is part of the standard mindset of EA, which
everyoneimmediatelyassociateswiththeactivitiesofanenterprisearchitect.
However, many of these big pictures you meet in practice have been over-
abstracted to the point of insignificance and no longer address any relevant
question.<<Bente2012>> p16

"semantic distortions" - simple example: equal-sized boxes on an EA capability map.

===== TLM
Lifecycle management can extend to internal products/services

EA provides guidance about what technologies are a strategic fit, which ones are deprecated, and which are emerging. <<Bente2012>> p8

Case study: The version control controversy: service vs TLM

if enterprise architects claim to be the only decision-making body
in technical matters, there is a huge risk that they create a bottleneck, if decisions take ages due to pending strategic issues, imminent changes in the business model, and so forth, IT projects can be seriously delayed. The practical consequence is that projects deliberately circumvent the enterprise architects—for example, by choosing less suitable technologies not managed by the EA group.<<Bente2012>> p19

Note that we compensate developers with money AND experience. Developer pressure to use a new technology should be seen in part as a demand for increased compensation.
