ifdef::collaborator-draft[]

==== Topics


anchor:TLM-CoD-worked[]

THE KEY ARCHITECTURAL DECISIONS - smith/reinertsen
106
Setting the System Boundary
106
107
The Degree of Modularity
Locating Functions
108
Designing Interfaces
108
Maintaining Flexibility
110


===== Architecture, queues, and Cost of Delay
****
The following is an exploration of using Cost of Delay and impact mapping

worked TLM example

TLM should route via corp governance & perf mgmt, align w/vendor mgmt... find sources on how these processes work in non IT domains... (have already discussed in book)
****

 refactoring as a panacea - no, it's like stirring wet concrete (Bente? Coplien?)

 ===== digital strategy

anchor:complex-systems[]
 ===== complex systems

* Describe Snowden's Cynefin and its major elements
* complexity (w/r/t Burgess)
* stability, state, etc (Burgess)
* complex system failures (Allspaw sidebar?)
* antifragility
* Cynefin
* self-steering, autopoeisis
* post-industrial

 is EA using the right tools? systems theory, semantics vs dynamics.

 ====== EA as systems thinking
hard to argue with but evidence is limited

****
Sidebar: Introducing Burgess.
****

****
Sidebar: Introducing Snowden & Taleb.
****

****
Sidebar: IT analytics experts
Magennis, Cantor, etc
****


* Postscript: Thought experiment on complete mainstreaming of IT

arch formalisms weak on dynamics - semantics vs dynamics problem semantics gravitate to first order predicate logic, binary thinking continuous math... required... how to measure anything. systems thinking.


 ===== EA and design thinking

 Design thinking is encroaching on architecture. Enterprise design?
_the sheer absurdity of undertaking something so ambitious, on the one hand, and, foolhardy, on the other, as any kind of intentional design of so complex and poorly (and even mis-) understood an entity as an organization in a context of rapid change._ <<Malan2010>>

 ===== metamodels

 ===== tech platform as compensation

 Note that we compensate developers with money AND experience. Developer pressure to use a new technology should be seen in part as a demand for increased compensation. developers seeking experience, it is in part how they are compensated. this leads to conflicts over choice of tools. (good blog as well). rational framework for deciding. might go to chapter 8, resource mgmt. intersection between that & tech lifecycle is key.


 ===== SAFE and architecture
 Review SAFE on architecture, also Reinertsen

 ===== Sol Arch for EA


 ===== misc
 "Architecture of software is a collection of design decisions that are expensive to change." <<Ran2001>>

 [quote, Ruth Malan]
 For enduring competitive advantage, the organization needs to seek leverage across its products and/or services and to create strategic capabilities that are hard to imitate because they rely on a mix of process, technology, skills, resources, facilities, culture, and even history <<Malan2005>>

 https://structurizr.com/help/about


 All arch is design not all design is arch (Booch)


 ====== NOTES

 Cathedral / bazaar

 Bente's four perspectives & eight caricatures

 [quote, Bente et al]
 With regard to the nature of complex systems, it is not advisable to search for the "optimal enterprise architecture." Optimality is always relative to an environment, and the frame conditions are likely to change. Hence it is better to accept certain ugly spots of the IT landscape and strengthen the viability of the whole, which means developing and using capabilities such as being able to learn, solve problems, adapt, or absorb disruptions.

  critical importance of not confusing solutions with EA. Scale matters.

  from bente: Anti-patterns in EA and architecture in general can be found, for instance, in Kruchten (2008), Mar and Spacey (2011), Ambler, Nalbone. and Vizdos (2005), and Coplien and Harrison (2005).


  https://philippe.kruchten.com/2011/02/13/the-elephants-in-the-agile-room/

  http://www.mckinsey.com/business-functions/organization/our-insights/to-centralize-or-not-to-centralize?platform=hootsuite

  review "a day in the life of an enterprise architect & Integration of EA & App Portfolio" walker, Comparison of top 4 EA methods, Sessions

  on visualization and architecture by Henderson:

  Why is the importance of visual skills as cognitive skills that are applicable in math and science not acknowl edged? Why are visual skills taken for granted and hence haphazardly taught?

 I found several books helpful as I thought about these issues. Patricia Greenfield's (1984) account of how children develop visual literacy documented visual knowledge in practice. Investigating her citations, I found Eugene Ferguson's (1977) account of how technical knowledge was transferred almost solely through visual representations from the 1400s to the recent past. Viewing this as evidence of the former high status of visual knowledge, my question changed to. Why does visual knowledge have such low status today in science and engineering if it enjoyed high status in the past?
 1 soon realized that my assumption of any consistent status for visual knowledge was problematic. A debate about the reliability of the seen is ongoing....

endif::collaborator-draft[]
