anchor:Section-III-coordination[]

== Part III: Team of Teams

[quote, Online Etymology Dictionary]
coordination (n.)  co-ordination, c. 1600, "orderly combination," from French coordination (14c.) or directly from Late Latin coordinationem (nominative coordinatio), noun of action from past participle stem of Latin coordinare "to set in order, arrange," from com- "together" (see com-) + ordinatio "arrangement," from ordo "row, rank, series, arrangement" (see order (n.)). Meaning "action of setting in order" is from 1640s; that of "harmonious adjustment or action," especially of muscles and bodily movements, is from 1855.

*Scenario*

You are now a "team of teams," at a size where face to face communication is increasingly supplemented by other forms of communication and coordination. Your teams are all good, and get results, but in different ways. You need some level of coordination and not everyone can talk to everyone; people are no longer co-located and there may be different schedules involved.

You now have multiple products. As you scaled up, you had to split your products into features and components (the z-axis of the xref:AKF-cube[AKF scaling cube]). Then as you move from your first product to adding more, even more organizational evolution is required. You try to keep your products from developing unmanageable interdependencies, but this is an ongoing challenge. Tensions between various teams are starting to emerge. You are seeing more and more specialization in your organization. You see a tendency of specialists to identify more with their field than with the needs of your customers and your business. There is an increasing desire among your stakeholders and executives for control and predictability. Resources are limited and always in contention. You are considering various frameworks for managing your organization. This is where it gets hard.

New employees are bringing in their experiences, and the more experienced ones seem to assume that the company will use "projects" and "processes" to get work done. There are no shortage of contractors and consultants all advocating various flavors of process and project management, some advocating older approaches and "frameworks" and others proposing newer Agile & Lean perspectives. However, the very concepts of process and project management are occasionally called into question by both your employees and various "thought leaders," and it's all very confusing.

Welcome to the coordination problem. We need to understand where these ideas came from, how they relate to each other, and how they are evolving in a digitally transforming world.

.Team of teams
****
_Team of Teams: New Rules of Engagement for a Complex World_  is the name of a 2015 book by General Stanley McChrystal, describing his experiences as the commander of Joint Special Operations Command in the Iraq conflict.  It describes how the U.S. military was being beaten by a foe with inferior resources, and its need to shift from a focus on mechanical efficiency to more adaptable approaches. The title is appropriate for this section, as moving from "team" to "team of teams" is one of the most challenging transitions any organization can make.
****

*Chapter 7: Organization and culture*

We're getting big.  How are we formally structured? In terms of our market, or in terms of our resources? How are people grouped, and to whom do they report, with what kind of expectations? What are the unspoken assumptions that underly our daily work -- in other words, what is our culture? Does our culture support high performance, or the opposite? How can we measure and know such a thing? Finally, what is our approach to bringing new people into our organization?

*Chapter 8: Investment*

In order to keep growing, you have to divide your organization. You now have a portfolio of features, and/or products, and each one is an investment. You need a strategy for choosing among your options, and planning -- at least at a high level -- in terms of costs and benefits. Some of you may be using project management to help manage your investments. Your vendor relationships continue to expand; they are another form of strategic investment, and you need to deepen your understanding of things like Cloud contracts and software licensing.

*Chapter 9: Execution*

When is work repeatable? When is it unique? Understanding the difference is essential to your organization's success. Is variability in the work always bad? Some argue that you don't need project management at all any more. But you've seen that your most ambitious ideas require some kind of choreography, and that products and projects need certain resources and services delivered predictably. And when resources are tight (and when aren't they?) their consumption must be governed somehow.


IMPORTANT: Part III, like the other parts, needs to be understood as a unified whole. In reality, growing companies struggle with the issues in all three chapters simultaneously.
