==== Larger scale planning and estimating

===== Why plan?

Fundamentally, we plan for two reasons:

* To decide whether to make an investment
* To ensure the investment's effort progresses effectively and efficiently.

We've discussed investment decision making in terms of the overall xref:digital-context[business context], in terms of the xref:product-roadmapping[product roadmap], the  xref:backlog-estimation-prioritization[product backlog], and in terms of xref:lean-product-dev[Lean Product Development] and xref:cost-of-delay[Cost of Delay]. As we think about making larger scale, multi-team digital investments, all of these practices come together to support our decision making process. Estimating the likely time and cost of one or more larger scale digital product investments is not rocket science; doing so is based on the same techniques we have used at the single-team, single-product level.

With increasing scope of work and increasing time horizon tends to come increasing uncertainty. We know that we will use fast feedback and ongoing hypothesis-driven development to control for this uncertainty. But at some point, we either make a decision to invest in a given feature or product, and starting the hypothesis testing cycle -- or we don't.

Once we have made this decision, there are various techniques we can use to xref:backlog-estimation-prioritization[prioritize] the work so that the most significant risks and hypotheses are addressed soonest. But in any case, when large blocks of funding are at issue, there will be some expectation of monitoring and communication. In order to monitor, we have to have some kind of baseline expectation to monitor against. Longer-horizon artifacts such as the product roadmap and release plan are usually the basis for monitoring and reporting on product or initiative progress.

In planning and execution, we seek to optimize the following contradictory goals:

* Delivering maximum value (outcomes)
* Minimizing the waste of un-utilized resources (people, time, equipment, software)

Obviously, we want outcomes -- digital value -- but we want it within constraints. It has to be within a timeframe that makes economic sense. If we pay forty people to do work that a competitor or supplier can do with three, we have not produced a valuable outcome relative to the market. If we take twelve months to do something that someone else can do in five, again, our value is suspect. If we purchase software or hardware we don't need (or *before we need it*) and as a result our initiative's total costs go up relative to alternatives, we again may not be creating value.

To meet these value goals, we need to:

* estimate so that expected benefits can be compared to expected costs, ultimately to inform the investment decision (start, continue, stop)
* plan so that we understand dependencies (e.g. when one team *must* complete a task before another team can start theirs)

NOTE: Projecting expected benefits is challenging. One of the most useful references for such questions is the book _How to Measure Anything: Finding the Value of Intangibles in Business_ by Doug Hubbard <<Hubbard2010>>.

Estimation sometimes causes controversy. When a team is asked for a projected delivery date, the temptation for management is to "hold them accountable" for that date and penalize them for not delivering value by then. But product discovery is inherently uncertain, and therefore such penalties can seem arbitrary. Experiments show that when animals are penalized unpredictably, they fall into a condition known as "learned helplessness," in which they stop trying to avoid the penalties <<Wikipedia2016a>.

We discussed various xref:coord-tools[boundary-spanning] tools and techniques in Chapter 8. Developing plans for understanding dependencies is one of the best known such techniques. An example of such a planning dependency would be that the database product should be chosen and configured before any schema development takes place (this might be a xref:feature-v-component[component team working with a feature team]).

===== Planning larger efforts
[quote, Mike Cohn, Agile Estimating and Planning]
...many large projects need to announce and commit to deadlines many months in advance, and many large projects do have interteam dependencies...

Planning and managing larger efforts

Agile and adaptive techniques can be used to plan larger, multi-team programs. Again, we have covered many fundamentals of product vision, estimation, and work management in earlier chapters. Here, we are interested in the concerns that emerge at larger scale, which we can class generally into:

* Accountability
* Coordination
* Risk management

====== Accountability

With larger blocks of funding comes higher visibility and inquiries as to progress. At a program level, differentiating between estimates and commitments becomes even more essential.

====== Coordination

Mike Cohn (<<Cohn2006>>) suggests that larger efforts specifically can benefit from the following coordination techniques:

* Estimation baseline (velocity)
* Key details sooner
* Lookahead planning
* Feeding buffers

Estimating across multiple teams is difficult without a common scale, and Cohn proposes an approach for determining this in terms of team velocity. He also suggests that in larger projects, some details will require more advance planning (it is easy to see APIs as being one example), and some team members' time should be devoted to planning for the next release. Finally, where dependencies exist, buffers should be used -- that is, if Team A needs something from Team B by May 1, Team B should plan on delivering it by April 15.

====== Risk management

Finally, risk and contingency planning is essential. In developing any plan, Abbott and Fisher recommend the "5-95 rule": 5% of the time on building a good plan, and 95% of the time planning for contingencies (<<Abbott2015>> p. 105).  We'll discuss risk management in detail in Chapter 10.

Many of the techniques suggested here are familiar to formal project management. Project management has the deepest tools, and whether or not you use a formal project structure, you will find yourself facing similar thought processes as you scale.
