==== Planning and estimating

===== Why plan?

Fundamentally, we plan for two reasons:

* To decide whether to make an investment
* To ensure the investment's effort progresses effectively and efficiently.

====== The investment decision
We've discussed investment decision making in terms of the overall xref:digital-context[business context], in terms of the product xref:roadmap-backlog-estimation[backlog], and in terms of xref:lean-product-dev[Lean Product Development] and xref:cost-of-delay[Cost of Delay]. As we think about making large scale digital investments, all of these practices come together to support our decision making process, and we need furthermore to 





We seek to optimize the following contradictory goals:

* Delivering maximum value (outcomes)
* Minimizing the waste of un-utilized resources (people, time, equipment, software)

To meet these goals, we need

* estimate so that expected benefits can be compared to expected costs, ultimately to inform the investment decision (start, continue, stop)
* plan so that we understand dependencies (e.g. when one team *must* complete a task before another team can start theirs)
* identify and analyze contingencies that may affect outcomes

When planning, we need to avoid:

planning dysfunctions

===== Techniques
[quote, Mike Cohn, Agile Estimating and Planning]
...many large projects need to announce and commit to deadlines many months in advance, and many large projects do have interteam dependencies...

inputs

* Business drivers
** biz plan & revenue
** road map/release plan (deeper)
** *risk* contingency planning -- Planning under variability
 AKF 5%-95% rule for planning & execution - goes to the top of this chapter - Abbott2015 p 105, spend 5% plnning and 95% considering contingencies--forward ref to risk mgmt

techniques

Monte Carlo - uncertainty

Buffering

outputs

what about project level control/monitoring? hard to close the plan/monitor loop when we haven't planned yet...

Project has the deepest tools, and whether or not you use a formal project structure, you will find yourself in this thought process as you scale.


the choice of financial management practice can profoundly impact... (next section lead in)
