==== Planning and estimating
quotes

===== Why plan?

Fundamentally, we plan for two reasons:

* To decide whether to make an investment
* To ensure the investment's effort progresses effectively and efficiently.

We seek to optimize the following contradictory goals:

* Delivering maximum value (outcomes)
* Minimizing the waste of un-utilized resources (people, time, equipment, software)

To meet these goals, we

* estimate so that expected benefits can be compared to expected costs, ultimately to inform the investment decision (start, continue, stop)
* plan so that we understand dependencies (e.g. when one team *must* complete a task before another team can start theirs)
* identify and analyze contingencies that may affect outcomes

When planning, we need to avoid:

planning dysfunctions



===== Planning techniques

Project has the deepest tools, and whether or not you use a formal project structure, you will find yourself in this thought process as you scale.

Inputs

* biz plan & revenue,
* road map/release plan
* *risk* contingency planning -- Planning under variability
 AKF 5%-95% rule for planning & execution - goes to the top of this chapter - Abbott2015 p 105, spend 5% plnning and 95% considering contingencies





the choice of financial management practice can profoundly impact... (next section lead in)
