==== Planning and estimating



===== Planning techniques

Fundamentally, we plan so that the work progresses effectively and efficiently. We seek to optimize the following contradictory goals:

* Delivering maximum value (outcomes)
* Minimizing the waste of un-utilized resources (people, time, equipment, software)

To meet these goals, we

* estimate so that expected benefits can be compared to expected costs
* plan so that we understand dependencies (e.g. when one team *must* complete a task before another team can start theirs)
* identify and analyze contingencies that may affect outcomes

Project has the deepest tools, and whether or not you use a formal project structure, you will find yourself in this thought process as you scale.

Detailed example? Or more detailed abstract examinination?

* biz plan & revenue, road map/release plan
inputs: backlog (esp. epics) & akf scaling

contingency planning -- Planning under variability
 AKF 5%-95% rule for planning & execution - goes to the top of this chapter - Abbott2015 p 105, spend 5% plnning and 95% considering contingencies

 Cohn on investment value - 4 forms
