==== Planning and estimating

===== Why plan?

Fundamentally, we plan for two reasons:

* To decide whether to make an investment
* To ensure the investment's effort progresses effectively and efficiently.

We've discussed investment decision making in terms of the overall xref:digital-context[business context], in terms of the xref:product-roadmapping[product roadmap], the  xref:roadmap-backlog-estimation[product backlog], and in terms of xref:lean-product-dev[Lean Product Development] and xref:cost-of-delay[Cost of Delay]. As we think about making large scale digital investments, all of these practices come together to support our decision making process. Estimating the likely time and cost of one or more larger scale digital product investments is not rocket science; doing so is based on the same techniques we have used at the single-team, single-product level.

With increasing scope of work and increasing time horizon tends to come increasing uncertainty. We know that we will use fast feedback and ongoing hypothesis-driven development to control for this uncertainty. But at some point, we either make a decision to invest in a given feature or product, and starting the hypothesis testing cycle -- or we don't.

Once we have made this decision, there are various techniques we can use to prioritize the work so that the most significant risks and hypotheses are addressed soonest. But in any case, when large blocks of funding are at issue, there will be some expectation of monitoring and communication. In order to monitor, we have to have some kind of baseline expectation to monitor against. Longer-horizon artifacts such as the product roadmap and release plan are usually the basis for monitoring and reporting on product or initiative progress.

In planning and execution, we seek to optimize the following contradictory goals:

* Delivering maximum value (outcomes)
* Minimizing the waste of un-utilized resources (people, time, equipment, software)

Obviously, we want outcomes -- digital value -- but we want it within constraints. It has to be within a timeframe that makes economic sense. If we pay forty people to do work that a competitor or supplier can do with three, we have not produced a valuable outcome relative to the market. If we take twelve months to do something that someone else can do in five, again, our value is suspect. If we purchase software or hardware we don't need (or *before we need it*) and as a result our initiative's total costs go up relative to alternatives, we again may not be creating value.

To meet these value goals, we need to:

* estimate so that expected benefits can be compared to expected costs, ultimately to inform the investment decision (start, continue, stop)
* plan so that we understand dependencies (e.g. when one team *must* complete a task before another team can start theirs)
* identify and analyze contingencies that may affect outcomes

Estimation sometimes causes controversy.

When planning, we need to avoid:

planning dysfunctions

===== Techniques
[quote, Mike Cohn, Agile Estimating and Planning]
...many large projects need to announce and commit to deadlines many months in advance, and many large projects do have interteam dependencies...

inputs

* Business drivers
** biz plan & revenue
** road map/release plan (deeper)
** *risk* contingency planning -- Planning under variability
 AKF 5%-95% rule for planning & execution - goes to the top of this chapter - Abbott2015 p 105, spend 5% plnning and 95% considering contingencies--forward ref to risk mgmt

techniques

Monte Carlo - uncertainty

Buffering

outputs

what about project level control/monitoring? hard to close the plan/monitor loop when we haven't planned yet...

Project has the deepest tools, and whether or not you use a formal project structure, you will find yourself in this thought process as you scale.


the choice of financial management practice can profoundly impact... (next section lead in)
