==== Topics in IT project management and related fields

anchor:Agile-frameworks[]

===== The Agile project frameworks

As of this writing, a number of frameworks have been developed at the intersection of Agile and project management. Notable examples include:

* The Scaled Agile Framework (http://www.scaledagileframework.com/)
* Disciplined Agile Delivery (http://www.disciplinedagiledelivery.com/)

Other Agile authors are skeptical of the need for such material <<Schwaber2013>>.

ifdef::collaborator-draft[]


****
*Collaborative*

 Status: Like most topics sections, this one is in need of work, being deferred to 2nd draft for cleanup & completion.

include::../../../collab-links.adoc[]
****

[quote, Project Management Body of Knowledge, version 5]
A project is a temporary endeavor undertaken to create a unique product, service, or result.

 Investment management?


impact mapping again, at a portfolio level.cost of delay revisited... !

 Funding value streams vs funding projects
 incorporate Leybourn review

===== Controversies in PM history
PERT chart history, Mcnamara, etc

anchor:NoEstimates[]

====== The estimation controversy

http://synerzip.com/must-see-agile-tv/to-estimate-or-no-estimates-that-is-the-question/
http://www.jrothman.com/mpd/project-management/2016/06/the-case-for-and-against-estimates-part-1/
http://www.jrothman.com/mpd/project-management/2016/06/the-case-for-and-against-estimates-part-2/

====== Earned value management
EVM could be described as a "model" used for understanding the
execution of software projects. It includes mathematical formulae
which are intended to provide insights into project dynamics. However
as will be discussed, the model does not take into consideration
feedback. It is an Open-Loop system model. Kennaley p44

or translating EVM directly to the balance sheet (EVM always being a fiction and less and less useful in a digitally transforming world)

====== The systems problem
[quote, Mark Kennaley, SDLC 3.0]
When risk and uncertainty are present with ongoing demand, like in the case of architectural changes and related high-stake decisions, batching demand into a project for governance reasons makes sense...

Kennaley, above, provides some reasoning for project management. Ironically, he uses the term "batch," which is often a concept unfavorably viewed in Agile and Lean circles.

Not all problems respond to iteration. Sometimes, deeper analysis is necessary. When a system presents multiple constraints that need to be solved simultaneously, the only way to do this with confidence may be as a "batch" of thought and analysis. If one needs to balance several competing objectives, one may need to know how a given course of action will affect all of them before embarking. Solving for one constraint (even iteratively), and embarking on a plan of action, may result in not meeting the other constraints, and having to throw the whole solution away.

Dogmatic approaches to solving this are unhelpful.  Multi-constraint optimization is a known hard problem in systems engineering and cannot be wished away through merely invoking the word "Agile."

===== Project management antipatterns
* Impersonal requirements (but see Alleman)
* "nothing is real unless it's a project"
* "Water-scrum-fall"

When taken to an extreme, the PMO becomes the arbiter of ALL IT investments in some organizations. Support and operational activities are chartered as long-running "projects" and staff time is billed through them (more on this in the section on Resource Management.) Essentially, this is how a program or product management approach emerges from taking the project management paradigm to an ultimate conclusion.

===== Scrum of scrums and its critiques
 identical to a chapter-based grassroots organization
 trouble is that emergent problems at each level start to distract & take over by the time you are to level 3, how do you maintain "credibility" at the base ... old trade union problem ... the quest for "authenticity" and grassroots suspicion of "egghead" systems thinkers

The concept of "scrum of scrums" may make intuitive sense, but starts to run into issues of power, hierarchy, authority, accountability, and so forth. It is mostly presented as a bottom-up structure, and there is an implication that the representatives to the scrum of scrums are also practitioners. (There is a strong narrative of authenticity in the Agile community. The lack of respect for "non-coders" is pronounced.) But what happens when overriding systems concerns need to be communicated downwards in the face of team resistance? What of the "scrum of scrums" representative who is perceived (rightly or wrongly) as not advocating reliably for the team? What of the team who regularly rotates their delegate out of well-intentioned motives related to individual empowerment, but resulting in ineffective representation?

In these questions we see the overlap of Agile with seemingly distant fields such as political science, organizational leadership, and the like. These are old, wicked problems with no "solutions" - only satisficing techniques.

===== Notes/2nd draft followup

From project to product/service: do current service portfolio techniques have a robust time/risk dimension, like PPM? (Galleman twitter discussion 7/4)



Tengshe, Ash, and Scott Noble. 2007. Establishing the agile PMO: Managing variability
across projects and portfolios. In Proceedings of the Agile 2007 Conference, ed.Jutta Eckstein, Frank Maurer, Rachel Davies, Grigori Melnik, and Gary Pollice, 188-193. IEEE Computer Society.

Tengshe and Noble established the agile project management office at Capital One Auto Finance.This paper describes their experience doing so and provides good advice for transitioning a PMO from traditional to agile. (cited in <<Cohn2010>>)

http://www.disciplinedagiledelivery.com/agility-at-scale/geographically-distributed-agile-teams/

Investment scorecarding pseudoscience - hubbard (example in Bente p91)


The concept of last responsible moment
Systems and automation
Skills management-10x controversy
Processes within projects-risk, action, issue, etc

idea: interview St. Thomas IT staff on moving to Office 365 (resource angle).
The modern product manager: a purple squirrel? <<Cohn2010>>pp130-132

Centers of Excellence as resource governors... Allocating limited resources (money, people, etc.) across all their
possible use is an important function of CoEs. They should ensure organizations invest in the most valuable projects and create economies of scale for their
service offering. In addition, coordination across other corporate interests is needed to enable the CoE to deliver value (from  Trebec_ITAMFromTheTrenches.pdf)

How does the COE know how to prioritize?

 https://beta-get.aptage.com/wp-content/uploads/2016/04/The-Aptage-Release-Planner-V3.pdf
 http://blackswanfarming.com/fund-the-teams-not-the-project/

[quote, Mark Kennaley, SDLC 3.0]
A holistic product-oriented approach contradicts a convenient over-simplification of IT delivery where everything is treated as a project. Such an approach is not Lean, in that treating all demand (coarse/strategic demand the same as fine-grained IT demand) amounts to batching, which creates inventory, waiting and potentially over-processing types of waste.

When this chapter is refactored to Investment, forward refs to Chapter 12 Portfolio Mgmt.

anchor:portfolio-CoD[]

 ===== Portfolio Cost of Delay

 portfolio-level  xref:portfolio-CoD[Cost of Delay] as essential to defining execution management. <<Reinertsen1997>> pp.35-38.

 ===== Beneficial variability
  belongs in Ch 8 investment

  Whenever I am told that management makes decisions too
slowly, I ask to see the specific proposal that went to management.
Invariably, I discover that the cost and benefit of the decision are
either unquantified or poorly quantified. In my experience, most
managers make amazingly fast decisions when they are presented
with compelling economic arguments. <<Reinertsen2009>> p52

 JADs, ARBs, technical spikes as key part of investment process... when does investment end and execution begin... it's somewhat arbitrary

 JAD for features that "some other team would notice." <<Abbott2015>> p 237
 ARB for things "everyone else would notice"

 synch points on a cadence


endif::collaborator-draft[]
