
anchor:financial-mgmt[]

==== IT financial management

ifdef::collaborator-draft[]

****
*Collaborative*

 Status: This Part Is first draft complete as of 10 May 2016. Reviews and comments appreciated. Some minor changes may be seen as I review over next few days.

 Needs: IT financial management experts also familiar with Beyond Budgeting or Lean Accounting. All 3 of you.

include::../../../collab-links.adoc[]

****

 split between planning & execution/control??

 investment decisions - make on financial basis - important to compute benefits, not just costs - harder w/indirect benefits but Hubbard shows the way
  direct benefits = easier ROI of tech investments - easier to compute impact of outages (amazon example p 126)
 customer acquisition cost


 2nd draft: add capex/opex, capitalization in Agile

 2 approaches
 1. Capitalize after 1st MVP (conservative)
 2. capitalize all the sprints

 Feasibility is key criteria

 Story point capitalization - also as alternative to time tracking - see also youtube, slideshare for https://agile2016.sched.org/event/6ebi/agile-economics-budgets-contracts-capitalization-pavel-dabrytski?iframe=yes&w=i:0;&sidebar=yes&bg=no pavel dabrytski talk

 but traditionally requirements are not capitalized

 Dan Greening talk on capitalization, Agile 2016 - couldn't attend, find video

endif::collaborator-draft[]

[quote, Terence Quinlan, IT Financial Management Association]
Computers initially were used to automate manual operations and the benefits were relatively easy to forecast. As organizations use computers more for strategic purposes and management information enhancements, the benefits become harder to forecast. In a growing number of companies the individuals most qualified to forecast the most significant costs and benefits are product managers, financial specialists, marketing specialists, and not the I/S technical specialists . . .

Financial health is an essential dimension of business health. And digital technology has been one of the fastest-growing budget items in modern enterprises. Its relationship to enterprise financial management has been a concern since the first computers were acquired for business purposes.

IMPORTANT: Financial management is a broad, complex, and evolving topic, and its relationship to IT and digital management is even more so. This brief section can only cover a few basics. However, it is important for you to have an understanding of the intersection of Agile and Lean IT with finance, as your organization's financial management approach can determine the effectiveness of your digital strategy.  See the cited sourced for further information.

The objectives of IT finance include:

* Providing a framework for tracking and accounting for digital income and expenses
* Supporting financial analysis of digital strategies (business models and operating models, including sourcing)
* Support the digital and IT-related aspects of the corporate budgetary and reporting processes, including internal and external policy compliance
* Supporting (where appropriate) internal cost recovery from business units consuming digital services
* Support accurate and transparent comparison of IT financial performance to peers and market offerings (benchmarking)

A company scaling up today would often make different decisions from a company that scaled up 40 years ago. This is especially apparent in the matter of how to finance digital/IT systems development and operations. The intent of this Part Is to explore both the traditional approaches to IT financial management and the emerging Agile/Lean responses.

This section has the following outline:

* Historic IT financial practices
** Annual budgeting and project funding
** Cost accounting and chargeback

* Next generation IT finance
** Lean Accounting & Beyond Budgeting
** Lean Product Development
** Internal "venture" funding
** Value stream orientation
** Internal market economics
** Service brokerage

===== Historic IT financial practices

Historically, IT financial management has been defined by two major practices:

* An annual budgeting cycle, in which project funding is decided
* Cost accounting, sometimes with associated internal transfers (chargebacks) as a primary tool for understanding and controlling IT expenses

Both of these practices are being challenged by Agile and Lean IT thinking.

====== Annual budgeting & project funding
[quote, Comella-Dorda et al, An Operating Model for Company-Wide Agile Development]
IT organizations typically adhere to annual budgeting and planning cycles—which can involve painful rebalancing exercises across an entire portfolio of technology initiatives, as well as a sizable amount of rework and waste. This approach is anathema to companies that are seeking to deploy agile at scale. Some businesses in our research base are taking a different approach. Overall budgeting is still done yearly, but road maps and plans are revisited quarterly or monthly, and projects are reprioritized continually. <<Comella2016>>

In the common practice of the annual budget cycle, companies once a year embark on a detailed planning effort to forecast revenues and how they will be spent. Much emphasis is placed on the accuracy of such forecasts, despite its near-impossibility. (If estimating one large software project is challenging, how much more challenging to estimate an entire enterprise's income and expenditures?)

The annual budget has two primary components: capital expenditures and operating expenditures, commonly called CapEx and OpEx. The rules about what must go where are fairly rigid and determined by accounting standards with some leeway for the organization's preferences.

Software development can be capitalized, as it is an investment from which the company hopes to benefit from in the future. Operations is typically expensed. Capitalized activities may be accounted for over multiple years (therefore becoming a reasonable candidate for financing and multi-year amortization.) Expensed activities must be accounted for in-year.

Because one can only "go to the well" once a year, extensive planning and negotiation traditionally take place around the IT project portfolio. Business units and their IT partners debate the priorities for the capital budget, assess resources, and finalize a list of investments. Project managers are identified and tasked with marshaling the needed resources for execution.

This annual cycle receives much criticism in the Agile and Lean communities. From a Lean perspective, projects can be equated to large "batches" of work. Using annual projects as a basis for investment can result in misguided attempts to plan large batches of complex work in great detail, so that resource requirements can be known well in advance. The history of the Agile movement is in many ways a challenge and correction of this thinking, as we have discussed throughout this book.

The execution model for digital/IT acquisition adds further complexity. Traditionally, project management has been the major funding vehicle for capital investments, distinct from operational expense. But with the rise of Cloud computing and product-centric management, companies are moving away from traditional capital projects. New products are created with greater agility, in response to market need, and without the large capital investments of the past in physical hardware.

This does not mean that traditional accounting distinctions between capex and opex go away. Even with expensed Cloud infrastructure services, software development may still be capitalized, as may software licenses.


===== Next generation IT finance

[quote, Orest Fiume and Jean Cunningham, as quoted by James Huntzinger]
What accounting should do is produce an unadulterated mirror of the business — an uncompromisable truth on which everyone can rely. ... Only an informed team, after all, is truly capable of making intelligent decisions.

As digital transformation accelerates and companies turn to Agile operating models, criticisms of  traditional approaches to IT finance have increased. Rami Sirkiä and Maarit Laanti (in a paper used as the basis for the Scaled Agile Framework's financial module) describe the following shortcomings:

* Long planning horizons, detailed cost estimates that must be frequently updated
* Emphasis on planning accuracy and variance analysis
* Context-free concern over budget overruns (even if a product is succeeding in the market, variances are viewed unfavorably)
* Bureaucratic re-approval processes for project changes
* Inflexible and slow resource re-allocation  <<Sirkia2013>>

What do critics of cost accounting, allocated chargebacks, and large batch project funding suggest as alternatives to the historic approaches? There are some limitations evident in many discussions of Lean Accounting, notably an emphasis on manufactured goods. However, a variety of themes and approaches have emerged relevant to IT services, that we will discuss below:

* Beyond Budgeting
* Internal "venture" funding
* Value stream orientation
* Lean Accounting
* Lean Product Development
* Internal market economics
* Service brokerage

====== Beyond Budgeting
[quote, Jeremy Hope and Robin Fraser, Beyond Budgeting Questions and Answers]
Setting a numerical target and controlling performance against it is the foundation stone of the budget contract in today’s organization. But, as a concept, it is fundamentally flawed. It is like telling a motor racing driver to achieve an exact time for each lap . . . it cannot predict and control extraneous factors, any one of which could render the target totally meaningless. Nor does it help to build the capability to respond quickly to new situations. But, above all, *it doesn’t teach people how to win*.


_Beyond Budgeting_ is the name of a 2003 book by Jeremy Hope and Robin Fraser. It written in part as an outcome of meetings and discussions between a number of large, mostly European firms dissatisfied with traditional budgeting approaches. Beyond Budgeting's goals are described as:

_releasing capable people from the chains of the top-down performance contract and enabling them to use the knowledge resources of the organization to satisfy customers profitably and consistently beat the competition_

In particular, Beyond Budgeting critiques the concept of the "budget contract." A simple "budget" is merely a "financial view of the future . . . [a] 'most likely outcome' given known information at the time . . . " A "budget contract" by comparison is intended to "delegate the accountability for achieving agreed outcomes to divisional, functional, and departmental managers." It includes concerns and mechanisms such as

* Targets
* Rewards
* Plans
* Resources
* Coordination
* Reporting

and is intended to "*commit* a subordinate or team to achieving an agreed outcome."

Beyond Budgeting identifies various fallacies with this approach, including:

* The idea that fixed financial targets maximize profit potential
* Financial incentives build motivation and commitment (see discussion on xref:motivation[])
* Annual plans direct actions that maximize market opportunities
* Central resource allocation optimizes efficiency
* Central coordination brings coherence
* Financial reports provide relevant information for strategic decision-
making

Beyond the poor outcomes that these assumptions generate, up to 20 to 30% of senior executives' time is spent on the annual budget contract. Overall, the Beyond Budgeting view is that the budget contract is

_a relic from an earlier age. It is expensive, absorbs far too much time, adds little value, and should be replaced by a more appropriate performance management model._ <<Hope2001>>, p 4, emphasis added.

Readers of this textbook should at this point notice that many of the Beyond Budgeting concerns reflect an Agile/Lean perspective. The fallacies of efficiency and central coordination have been discussed throughout this book. However, if an organization's financial authorities remain committed to these as operating principles, digital transformation will be difficult at best.

Beyond Budgeting proposes a number of principles for understanding and enabling organizational financial performance. These include:

* Event-driven over annual planning
* On-demand resources over centrally allocated resources
* Relative targets ("beating the competition") over fixed annual targets
* Team-based rewards over individual rewards
* Multi-faceted, multi-level, forward-looking analysis over analyzing historical variances

anchor:internal-venture[]

====== Internal "venture" funding
[quote, Comella-Dorda et al, An Operating Model for Company-Wide Agile Development]
A handful of companies are even exploring a venture-capital-style budgeting model. Initial funding is provided for minimally viable products (MVPs), which can be released quickly, refined according to customer feedback, and relaunched in the marketplace . . . And subsequent funding is based on how those MVPs perform in the market. Under this model, companies can reduce the risk that a project will fail, since MVPs are continually monitored and development tasks reprioritized . . . <<Comella2016>>

As we have discussed xref:process-project-product[previously], product and project management are distinct. Product management in particular has more concern for overall business outcomes. If we take this to a logical conclusion, the product portfolio becomes a form of investment portfolio, managed not in terms of schedule and resources, but rather in terms of business results.

This implies the need for some form of internal venture funding model, to cover the initial investment in a minimum viable product. If and when this internal investment bears fruit, it may become the basis for a value stream organization, which can then serve as a vehicle for direct costs and an internal services market (see below). McKinsey reports the following case:

****
A large European insurance provider restructured its budgeting processes so that each product domain is assigned a share of the annual budget, to be utilized by chief product owners. (Part of the budget is also reserved for requisite maintenance costs.) Budget responsibilities have been divided into three categories: a development council consisting of business and IT managers meets monthly to make go/no-go decisions on initiatives. Chief product owners are charged with the tactical allocation of funds—making quick decisions in the case of a new business opportunity, for instance—and they meet continually to rebalance allocations.

Meanwhile, product owners are responsible for ensuring execution of software development tasks within 40-hour work windows and for managing maintenance tasks and backlogs; these, too, are reviewed on a rolling basis. As a result of this shift in approach, the company has increased its budgeting flexibility and significantly improved market response times. <<Comella2016>>
****

With a rolling backlog and stable funding that decouples annual allocation from ongoing execution, the venture-funded product paradigm is likely to continue growing. A product management mindset activates a variety of useful practices, as we will discuss in the next section.

anchor:options-portfolio[]

====== Options as a portfolio strategy

In governing for effectiveness and innovation, one technique is that of options. Related to the idea of options is parallel development.

In investing terms, purchasing an option gives one the right, but not the obligation, to purchase a stock (or other value) for a given price at a given time. Options are an important tool for investors to develop strategies to compensate for market uncertainty.

What does this have to do with developing digital products?

Product development is so uncertain that sometimes it makes sense to try several approaches at once. This in fact was how the program to develop the first atomic bomb was successfully managed.

Parallel development is analogous to an options strategy. Small, sustained investments in different development "options" can optimize development payoff in certain situations.

Taken to a logical conclusion, such an options strategy starts to resemble the portfolio management approaches of venture capitalists. Venture capitalists invest in a broad variety of opportunities, knowing that most in fact will not pan out. See discussion of xref:internal-venture[internal venture funding] as a business model.

It is arguable that the venture-funded model has created different attitudes and expectations towards governance in West Coast "unicorn" culture. However, it would be dangerous to assume that this model is universally applicable. A firm is more than a collection of independent sub-organizations; this is an important line of thought in management theory, starting with Coase's "The Nature of the Firm" <<Coase1937>>.

====== Lean Product Development
[quote, Don Reinertsen, Managing the Design Factory]
Because we never show it on our balance sheet, we do not think of [Design in Process] as an asset to be managed, and we do not manage it.

The xref:lean-product-dev[Lean Product Development] thought of Don Reinertsen was discussed extensively in Chapter 4. His emphasis on employing an economic framework for decisionmaking is relevant to this discussion as well. In particular, his concept of xref:cost-of-delay[Cost of Delay] is poorly addressed in much IT financial planning, with its concerns for full utilization, efficiency, and variance analysis. Other Lean accounting thinkers share this concern, e.g.:

_the cost-management system in a lean environment must be more reflective of the physical operation. It must not be confined to monetary measures but must also include nonfinancial measures, such as quality and throughput times._<<Huntzinger2007>>

Another useful Reinertsen concept is that of *design in process* or DIP. This is an explicit analog to the well-known Lean concept of *work in process* (WIP). Reinertsen  makes the following points  <<Reinertsen1997>>,  p13:

* DIP is larger and more expensive to hold than WIP
* It has much lower turn rates
* It has much higher holding costs (e.g. due to obsolescence)
* DIP's liabilities are ignored due to weaknesses in accounting standards

These concerns give powerful economic incentives for managing throughput and flow, continuously re-prioritizing for maximum economic benefit and driving towards the Lean ideal of single-piece flow.

====== Lean Accounting
[quote, Taiichi Ohno]
It was not enough to chase out the cost accountants from the plants, the problem was to chase cost accounting from my people's minds.

There are several often-cited motivations for cost accounting (<<Huntzinger2007>> p 13):

* Inventory valuation (not applicable for intangible services)
* Informing pricing strategy
* Management of production costs

NOTE: The term "cost accounting" is used here with its xref:cost-accounting-def[full implications], including allocated overhead. It is not the same as just "accounting for costs," which is always a concern for any organization.

IT service costing has long presented additional challenges to traditional cost accounting. As IT Financial Management Association president Terry Quinlan notes, "Many factors have contributed to the difficulty of planning EDP expenditures at both application and overall levels. A major factor is the difficulty of measuring fixed and variable cost." <<Quinlan2003>>, p. 6.

This begs the broader question: should traditional cost accounting be the primary accounting technique used at all? Cost accounting in Lean and Agile organizations is often controversial. Lean pioneer Taiichi Ohno of Toyota thought it was a flawed approach. Huntzinger <<Huntzinger2007>> identifies a variety of issues:

* Complexity
* Un-maintainability
* Supplies information "too late" (i.e., does not support fast feedback)
* "Overhead" allocations result in distortions

Shingo Prize winner Steve Bell observes:

****
It is usually impossible to tie  . . . abstract cost allocations and the resulting variances back to the originating activities and the value they may or may not produce; thus, they can't help you improve. But they can waste your time and distract you from the activities that produce the desired outcomes . . . <<Bell2013>>, p 110.
****

The trend in Lean Accounting has been to simplify. A guiding ideal is seen in the https://en.wikipedia.org/wiki/Lean_accounting[Wikipedia article on Lean Accounting]:

_The "ideal" for a manufacturing company is to have only two types of transactions within the production processes; the receipt of raw materials and the shipment of finished product._

Concepts such as value stream orientation, internal market economics, and service brokering all can contribute towards achieving this ideal.

====== Value stream orientation
[quote, James R. Huntzinger, Lean Cost Management]
Collecting costs into traditional financial accounting categories, like labor, material, overhead, selling, distribution, and administrative, will conceal the underlying cost structure of products . . . The alternative to traditional methods . . . is the creation of an environment that moves indirect costs and allocation into direct costs.<<Huntzinger2007>>

As discussed above, Lean thinking discourages the use of any concept of overhead, sometimes disparaged as "peanut butter" costing. Rather, direct assignment of all costs to the maximum degree is encouraged, in the interest of accounting simplicity.

We discussed a venture-funded product model above, as an alternative to project-centric approaches. Once a product has proven its viability and becomes an operational concern, it becomes the primary vehicle for those concerns previously handled through cost accounting and chargeback. The term for a product that has reached this stage is "value stream." As Huntzinger notes, "Lean principles demand that companies align their operations around products and not processes." <<Huntzinger2007>> p 19.

By combinining a value stream orientation in conjunction with organizational principles such as frugality, internal market economics, and decentralized decision-making (see e.g. <<Hope2001>> p 12), both Lean and Beyond Budgeting argue that more customer-satisfying and profitable results will ensue. The fact that the product in this case is digital (not manufactured), and the value stream centers around product development (not production) does not change the argument.


====== Service brokerage
Finally, there is the idea that digital or IT services should be aggregated and "brokered" by some party (perhaps the descendant of a traditional IT organization). In partcular, this helps with capacity management, which can be a troublesome source of internal pricing distortions. This has been seen not only in IT services, but in Lean attention to manufacturing; when unused capacity is figured into product cost accounting, distortions occur <<Huntzinger2007>>, chapter 7, "Church and Excess Capacity."

Applying Meyer's principles, excess capacity would be identified as a Subsidy or a Venture as a distinct line item.

But Cloud services can assist even further. Excess capacity often results from the available quantities in the market - e.g., one purchases hardware in large-grained capital units. But more flexibly priced, expensed compute on demand services are available, it is feasible to allocate and de-allocate capacity on demand, eliminating the need for accounting for excess capacity.

ifdef::collaborator-draft[]

 2nd draft material

  ====== Allocation of capital in large batches

  Pros and cons - sometimes, one needs to accept the fog of R&D
  This never changes
  The iconic entrepreneur asking for one more round

  entrepreneurs tell a story https://silvialisam.com/chris-sacca-s-639f0f5f3b9c#.j6sljdp0x

  VC view

  review Lean Enterprise ch13
  cite Anderson's relevant work

endif::collaborator-draft[]
