== Copyright

Published by Digital Management Academy, LLC +
14 Sidney Place +
Minneapolis, MN  55414

Copyright © 2016 by Charles T. Betz

All rights reserved, for information about permission to reproduce selections from this book, write to Permissions, Digital Management Academy LLC,
14 Sidney Place, Minneapolis, MN  55414

First Edition

Produced in the United States of America

Cover illustration by Go To Media, LLC

ISBN: 978-0-9981346-0-4

Publisher's note to readers:
Although the author and publisher have made every effort to ensure that the information in this book was correct at press time, the author and publisher do not assume and hereby disclaim any liability to any party for any loss, damage, or disruption caused by errors or omissions, whether such errors or omissions result from negligence, accident, or any other cause.

For information about special discounts for bulk purchases or for information on booking authors for an event, please visit www.dm-academy.com.


ifdef::aitm-pdf[]

<<<

endif::aitm-pdf[]
