[[Preface]]
== Preface

In 2013, I was approached by Dr. Bhabani Misra, the head of the Graduate Programs in Software at the University of St. Thomas in St. Paul. Dr. Misra asked me to teach IT Infrastructure Management (SEIS660), focusing on the Information Technology Infrastructure Library, or ITIL.

The first semester of the class was well received enough for me to be invited back. However, there were complaints from the students that it was too theoretical. I was attempting to teach using an enterprise architecture style with lots of abstractions -- that just was not engaging students effectively. I also had a team project approach that immediately started the students out as the IT leadership team of a large corporation. This generated feedback that the students wanted something more practical; they were not going to be immediately hired as senior executives!

I took this feedback seriously. I especially gave thought to a practical aspect and so started to develop a lab component. This was and is popular with the students. I also started to think about different approaches for structuring the class that would make more sense for a survey class with a wide spectrum of experience.

For three semesters I assigned my first book (_Architecture and Patterns for IT: Service Management, Resource Planning, and Governance_) as a required text for the class. However, I did not write this as a textbook, and its limitations became clear. It has a strongly architectural approach, coming at the IT management problem as a series of https://en.wikipedia.org/wiki/4%2B1_architectural_view_model[views on a model]. I do not recommend this as a pedagogical approach for a survey class.

I proposed the idea of a third edition to my publisher -- one that would pivot the existing material towards something more useful in class. They agreed to this and I started the rewrite. However, by the time I was halfway done with the first draft, I had a completely new book. Material from the previous work simply did not fit the emergence model I used to structure the narrative.

A number of factors converged at this point in time:

* My view that the “medium is the message,” which extends to the choice of authoring approach, intellectual property, digital rights management, and publisher
//I wanted to write out the acronym DRM. Is it digital rights management?
* Contacts with local and international faculty and thought leaders and a desire to openly collaborate with them on making the book as good as possible
* A desire to freely share at least a rough version of the book, both for marketing purposes and in the interests of giving back to the global IT community
* A desire to be able to rapidly update the book with as little friction as possible
* A practical realization that the book might get more uptake globally if it were available, at least in some form, as free and open source intellectual property
* The fact that I had already started to https://github.com/StThomas-SEIS660[publish my labs on GitHub] and had, in fact, developed a workable continuous delivery (“DevOps”) toolchain (the https://github.com/CharlesTBetz/Calavera[Calavera project], which has attracted collaborators from the U.S., Spain, and Israel)
//What happened after considering all the points that converged? It’s not explicitly stated. We can infer what happened, but I was waiting for you to explicitly say that you decided to self-publish.

Many have assisted with this work:

Thanks to Dr. Bhabani Misra for asking me to teach at the University of St. Thomas and providing direction at key points.

Thanks to Stephen Fralippolippi and Roger K. Williams for being the first GitHub contributors.

Thanks to Jason Baker for text and technical collaboration.

Thanks to Mark Kennaley for guidance on open versus closed loop thinking.

Thanks to Glen Alleman for guidance on modern project management practices.

Thanks to Jeff Sussna for ongoing inspiration, Twitter feedback, discussion question ideas, and sourced quotes.

Thanks to Nicole Forsgren for links to articles on performance management.

Thanks to Evan Leybourn for detailed commentary on project management in chapter eight.

Thanks to Chris Little and Jabe Bloom for quote provenance.

Thanks to Lorin Hochstein for references.

Thanks to Gene Kim for ongoing mentoring and advice on writing and publishing and unwavering support and confidence in my efforts.

Thanks to Go To Marketing Team (Will Goddard, Terry Brown, Francisco Piniero) for design assistance and invaluable partnership.

Thanks to Professor Pat Paulson for being the first adopter of the textbook, and thanks to his students for invaluable criticism and feedback.
