ifdef::collaborator-draft[]

why I handled PM the way I did. DevOps means integrating all work from the start. Chapter 5 incorporates both Lean PD and service desk, as an example of this.

endif::collaborator-draft[]


ifdef::instructor-ed[]



[[Instructor-intro]]
=== Introduction for Instructors and Trainers

Welcome to Agile IT Management: From Startup to Enterprise. So, what exactly IS this textbook, anyhow?

* It is the first general, survey-level text on IT management with a specific Agile, Lean IT, and DevOps orientation.
* It has a unique and innovative narrative structure based on the concept of organizational evolution and scaling.
* It both covers and is written using Agile, Lean, and continuous delivery techniques.
* Because it is written with continuous integration and print-on-demand techniques, it can be continually updated to reflect current industry trends.

==== The IT industry and the rise of digital
[quote, Darrell Rigby et al., Harvard Business Review]
Now agile methodologies -- which involve new values, principles, practices, and benefits and are a radical alternative to command-and-control-style management -- are spreading across a broad range of industries and functions and even into the C-suite. cite:[DRigby2016]


As an instructor, I ask you to consider the following two industry reports.

In September 2015, Minneapolis-based Target Corporation laid off 275 workers with IT skillsets such as business analysis and project management, while simultaneously hiring workers with newer “Agile” skills. As quoted by a local news site, Target stated:

_“As a part of our transition to an Agile technology development and support model, we conducted a comprehensive review of our current structure and capabilities… we are eliminating approximately 275 positions and closing an additional 35 open positions. The majority of the impact was across our technology teams and was primarily focused on areas such business analysis and project management."_ cite:[KARE2015]

Jim Fowler, Chief Information Officer at General Electric, says:

_“When I am in business meetings, I hear people talk about digital as a function or a role. It is not. Digital is a capability that needs to exist in every job. Twenty years ago, we broke ecommerce out into its own organization, and today ecommerce is just a part of the way we work. That’s where digital and IT are headed; IT will be no longer be a distinct function, it will just be the way we work. … [W]e’ve moved to a flatter organizational model with “teams of teams” who are focused on outcomes. These are co-located groups of people who own a small, minimal viable product deliverable that they can produce in 90 days. The team focuses on one piece of work that they will own through its complete lifecycle…in [the “back office”] model, the CIO controls infrastructure, the network, storage, and makes the PCs run. The CIOs who choose to play that role will not be relevant for long.”_  cite:[Heller2016]

Modern information systems (MIS) texts, especially at the undergraduate, survey level, take an “outside-in” approach to the course material, seeking to orient *all* students (whether IT/MIS specialists or not) to the role and function of information systems and their possibilities and value in the modern enterprise. This book, by contrast, is an “inside-out” book intended to prepare the student for a career in digital industry. _Industry_ is broadly defined as both those industries that offer digital products per se as well as industries that rely on digital technology instrumentally for delivering all kinds of products. A central theme of the book is that IT, considered as a component, represents an increasing proportion of *all* industrial products (both consumer and business-facing). This is known as digital transformation.

Current MIS survey texts have some common characteristics:

* They tend to focus on the largest organizations and their applications of computing. This can lead to puzzling topic choices; for example, in one text, one of the first sections is dedicated to the problem of enterprise IT asset management -- a narrow topic for the earlier sections of a survey course and increasingly irrelevant in the age of the cloud.
* Their learning progression (structure and narrative) is often arbitrary; for example, covering databases, networking, ERP systems, security, and so forth in various orderings.
* They do not (and this is a primary failing) cover Agile and its associated digital ecosystem at all well. Brief mentions of Agile may appear in sections on project management, but in general there is a lack of awareness of the fundamental characteristics of digital transformation and the critical role of Agile and related methods in accelerating digital transformation.
* Their coverage of cloud infrastructure also tends to be limited, even with new editions coming out every year.
* Finally, current texts often uncritically accept and cite “best practice” IT frameworks such as CMMI, ITIL, PMBOK, and COBIT. New digital organizations do not, in general, use such guidance, and the industry at the time of this writing is rife with controversy as to the value and future of these frameworks. This book provides a clear and objective overview of these critical issues.

IT, or the digital function, has had a history of being under-managed and poorly understood relative to peer functions in the enterprise. It struggles with a reputation for expensive inflexibility and Dilbert-esque dysfunction. The DevOps and Agile movements promise transformation but are encountering an entrenched legacy of

* enterprise architecture;
* program and project management;
* business process management;
* IT service management practices; and
* IT governance concerns.

Understanding and engaging with the challenges of this legacy are an ongoing theme throughout this introductory text. Some of the more radical voices in the Agile movement sometimes give the impression that the legacy can be simply swept away. The following cautionary message from Mike Burrows shows that, in terms of core Agile philosophy, this would be ill-advised:

_“Some will tell you that when things are this bad, you throw it all away and start again. It’s ironic: The same people who would champion incremental and evolutionary approaches to product development seem only too eager to recommend disruptive and revolutionary changes in people-based systems -- in which the outcomes are so much less certain.”_ cite:[Burrows2015] (loc. 827–829).

IT management at scale within an organization is a complex system. The IT workforce and its ongoing development (through education and training) is another complex system orders of magnitude larger. Complex systems do not respond well to dramatic perturbations. They are best changed incrementally, with careful monitoring of the consequences of each small change. (This is part of the systems theory foundation underlying the Agile movement.) This is why the book, especially in the later chapters, starts with relatively straightforward and uncritical presentations of the following topics:

* Investment, sourcing, and people
* Project and process management
* Governance, risk, security, and compliance
* Enterprise information management
* Enterprise architecture and portfolio management

While these practices, and their associated approaches and policies, have caused friction with digital and Agile practitioners, they all have their reasons for existing. The goal of this book is to understand their interaction with the new digital approaches, but in order to do this we must first understand them on their own terms. It does no good to develop a critique based on misconceptions or exaggerations about what (for example) process management or governance is all about. Instead, we try to break these large and sometimes controversial topics into smaller, more specific topics -- lowest common denominators, perhaps as follows:

* Work and effort
* Ordering of tasks
* Task dependencies
* Planned versus unplanned work
* Estimation versus commitment
* Value stream versus skill alignment
* Repeatability
* Defined versus empirical process control
* Synchronization and cadence
* Resource demand
* Shared mental models
* Mission objectives versus perimeter defense
* Technical debt
* Risk
* And so forth

By examining IT management in these more neutral, specific terms, we can develop a responsible critique of current industry best practices in content and form that will benefit students as they go out on their careers.

==== A process of emergence

[quote, Steve Blank, The Four Steps to Epiphany]
Joseph Campbell popularized the notion of an archetypal journey that recurs in the mythologies and religions of cultures around the world. From Moses and the burning bush to Luke Skywalker meeting Obi wan Kenobi, the journey always begins with a hero who hears a calling to a quest.... +
 +
The hero’s journey is an apt way to think of startups. All new companies and new products begin with an almost mythological vision -- a hope of what could be, with a goal few others can see....  +
 +
Most entrepreneurs feel their journey is unique. Yet what Campbell perceived about the mythological hero’s journey is true of startups as well: However dissimilar the stories may be in detail, their outline is always the same. cite:[Blank2013]

[quote, John Gall, The Systems Bible]
A complex system that works is invariably found to have evolved from a simple system that worked. A complex system designed from scratch never works and cannot be patched up to make it work. You have to start over, beginning with a working simple system. cite:[Gall2012]

One of the most important and distinguishing features of this book is its emergence model. In keeping with the entrepreneurial spirit of works like Ries’ http://www.amazon.com/dp/0307887898/[_The Lean Startup_,] the book adopts a progressive, evolutionary approach. The student’s journey through it reflects a process of emergence. Such processes are often associated with founding and scaling a startup. There are many helpful books on this topic, such as the following:

* _Nail It Then Scale It_ by Furr and Ahlstrom cite:[Furr2013]
* _Scaling Up_ by Harnish cite:[VHarnish2014]
* _Startup CEO_ by Blumberg cite:[Blumberg2013]
* _The Lean Startup_ by Ries cite:[Ries2011]
* _Hello, Startup_ by Brikman cite:[Brikman2016]

The emergence model and overall book structure is discussed in depth in the main introduction. Here, for the instructor, are some notes on the thought process. I have spent considerable time thinking (agonizing) about the correct ordering of the chapters within these sections. This is possibly the tenth or twelfth version of the chapter ordering. This is an area where I want critical review but also have strong opinions.

There is benefit to restricting the chapters to twelve, as a typical semester runs fourteen weeks, and the book then fits quite nicely, with one chapter per class and allowing for an introductory session and final exam. (Trying to modify the semester system is out of scope for this project.) Of course, a two-semester series, with two weeks per chapter, would also work well. Each half of the book is also a logical unit.

The governing thought experiment is, “what would I turn my attention to next as my IT-based concerns scale up?” For example, I think work management (implying rudimentary workflow, e.g., Kanban) correctly comes before formalized project and/or process management, which in turn tend to emergence before enterprise governance practices (e.g., formalized risk management).

Note that this would be a testable and falsifiable hypothesis if empirical research were done to inventory and characterize organization scaling patterns. If we found, for example, that a majority of organizations formalize governance, risk, security, and compliance practices before formalizing project management, that would indicate that those chapters should be re-ordered. In my experience, small/medium businesses may have some formal IT project management capability but governance, risk, and compliance (GRC) are still tacit, not formalized. This does not mean that GRC is not a concern, but they have not yet instituted formal policy management, internal audit, or controls.

The presence of product management at an early stage is intended to provoke. Product management is poorly addressed in most current CSci/MIS/IT education as well as the reigning industry standards. Yet formalizing it is one of the earliest concerns for a startup, and the imperatives of the product vision drive all that comes after. Evidence to this effect is seen (as of 2015) at the University of California at Berkeley I-School, which has replaced its Project Management course with http://www.ischool.berkeley.edu/courses/i290m-lapm[Lean/Agile Product Management], taught currently by the esteemed Jez Humble, author of _Continuous Delivery_.
//At an early stage in the book? And maybe we could add what is being provoked. I’m not understanding “as well as the reigning industry standards.” What are the industry standards in addition to? product management or education?
Also, you may notice that *the chapter titles don’t necessarily reflect Agile terminology*. This is also deliberate, as students are going into a diverse world of much long-established IT. Furthermore, putting _Agile_ as a qualifier on each chapter seems gratuitous (e.g., “Agile Operations Management” instead of just “Operations Management”). The first word of the book’s title is _Agile_. That declares the orientation, and the proof will be in the reading. My intent is to involve experienced Agile practitioners in contributing to the sections most relevant to them, and I anticipate a high quality end result that is recognizably supportive of the Agile movement’s goals and ambitions.

The book however is not a complete dismissal of older models of IT delivery. Wherever possible, Agile is presented as an evolutionary step relative to what has gone before. The specifics of “what’s different” are identified, in the interest of de-mystifying what can be a fraught and quasi-religious topic. In the words of Don Reinertsen, you can have “faith-based Agile or science-based Agile.” This book is strictly interested in the latter. Pointers to relevant theory are included, although this is NOT a theoretical text. That may come later.

*This emergence model can also be understood as an individual’s progression within a larger enterprise.* Even if one starts from day one at a Fortune 100 corporation, I believe the progression of one’s understanding still progresses from individual, to team, to “team of teams,” to enterprise. Of course, one may cease evolving one’s understanding at any of these stages, with corresponding implications for one’s career.

Some of you may be familiar with the idea of a minimum viable product (MVP), minimum marketable release, or similar. In these terms, it is important to understand that each *section* of the book represents an MVP but not each chapter. One can’t begin to deliver IT value without the components discussed in each of chapters one through three. The chapters of each section tend to be interdependent in other words.

Each chapter flows in a roughly top-down fashion:

. *Business* concerns (value, motivation)
. *Process* concerns (execution, flow)
. Lean, Agile, and DevOps perspectives as appropriate
. *System* concerns (information and automation)

This book does not cover specific technologies in any depth. Many examples are used, but they are carefully framed to not require previous expertise. This is about broader, longer lifecycle trends.

==== Labs

With three chapters in each section, the book can be covered in one intense semester at a chapter a week, although expanding it to a two-semester treatment would allow for more in-depth coverage and increased lab exposure. I give great credit to both my first cohort of students and Dr. Bhabani Misra for challenging me to add a practical component to the course. This required new thinking on my part. How to demonstrate IT management at scale in a lab setting? I have learned that a hands-on component is critical, as IT management discussions can be abstract and meaningless to many students. (“Incidents are different from problems!”)

Ten years ago, the best that would have been possible would be paper case studies, perhaps augmented with spreadsheets. But new options are now available. The power of modern computers (even lightweight laptops) coupled with the widespread availability of open source software makes it is now possible to expose students to industrial computing in a meaningful, experiential way. I have found great utility in the use of lightweight virtualization technologies such as Vagrant, VirtualBox, and Docker. I recommend this approach wholeheartedly. I am always interested in hearing from other instructors who are working from the same approach. At the time of this writing, I maintain my labs (table <<tbl-course-labs>>) publicly on GitHub. My syllabus and lab structure are under continual improvement.

[cols="5*", options="header"]
|====
|Lecture|Topic|Business lab |Technical lab |Team size
|Course introduction |Structure, approach |None|SSH & workstation setup |Individual
5+|Part I: FOUNDER
|Chapter 1 |IT value |Defining an IT product  --  review SaaS examples |Linux command line | 2
|Chapter 2 |IT infrastructure |Reviewing current SaaS offerings |Cloud and infrastructure as code  --  configuring a Vagrant machine manually & w/ script that is checked in to GitHub & modified | 2
|Chapter 3 |Applications||Continuous delivery pipeline | 2
5+|Part II: TEAM
|Chapter 4 |Product management |User stories; fail fast/risk mgmt |Behavior-driven development |6–8
|Chapter 5 |Work management 2+^|Scrum, ticketing, and Kanban |6–8
|Chapter 6 |Operations management |Service definition |Monitoring (Calavera + Nagios) | 6–8
5+|Part III: TEAM OF TEAMS
|Chapter 7 |Coordination|Organizational forms & communication channels (paper exercise?) |iTOP ITSM suite | > 11 (full class)
|Chapter 8 |Investment and planning | |Architecture game | > 11 (full class)
|Chapter 9 |Organization and culture | |Game or paper exercise| > 11 (full class)
5+|Part IV: ENTERPRISE
|Chapter 10 |Security, governance, risk, and compliance |  |Scanning VMs for vulnerabities with Lynis | 5
|Chapter 11 |Enterprise information management |Data and records management exercises | | 5
|Chapter 12 |Architecture and portfolio | Portfolio investment simulation exercise | |5
|====

[[tbl-course-labs]]
.Course Labs
[cols="0"]
|====
|
|====

I use a central server in teaching my classes, but even that is not necessary. This class can be taught with a zero computing budget, assuming that each team of students at least has access to a modern laptop (recommend 8 gigabytes of RAM and 1 terabyte drive) and a fast Internet connection. As of this writing, I am using free and open source versions of Chef, Jenkins, iTOP, jUnit, Ant, and other tools (see GitHub for the current approach).

Some may question the inclusion of command-line experience, but without some common technical platform, it is hard to provide a meaningful, hands-on experience in the first half of the course. I structure my class on the assumption that the students are at least willing to learn computing techniques, with no prerequisites beyond that. Not even a programming language is required; the Java currently used as a sample is minimal.

Truly beginning students will have to work at the Linux tutorials, but all they need master is basic command line navigation, and I have found this possible with a diverse student body, some with no previous direct experience. The labs for the second half of the course use games, experiential paper-based classroom exercises, GUI-based software, databases, and office productivity tools.


ifdef::collaborator-draft[]

similarity to spiral model
not a reference... some topics are split... it's a hero's journey
shu-ha-ri
scale also means longer time scales

endif::collaborator-draft[]


endif::instructor-ed[]
