ifdef::instructor-ed[]

[[Instructor-intro]]
== Introduction to the Instructor's Edition

Welcome to Agile IT Management: From Startup to Enterprise. So, what exactly IS this textbook, anyhow?

* It is the first general, survey-level text on IT management with a specific Agile, Lean IT, and DevOps orientation.
* It has a unique and innovative narrative structure based on the concept of organizational evolution and scaling.
* It both covers and is written using Agile, Lean, and continuous delivery techniques.
* Because it is written with continuous integration and print on demand techniques, it can be continually updated to reflect current industry trends.



=== This book's positioning

Modern Information Systems texts, especially at the undergraduate, survey level, take an "outside-in" approach to the course material, seeking to orient *all* students (whether IT/MIS specialists or not) as to the role and function of information systems and their possibilities and value in the modern enterprise. This book, by contrast, is an "inside-out" book, intended to prepare the student for a career in digital industry. “Industry” is broadly defined as both those industries that offer digital products _per se_, as well as industries that rely on digital technology instrumentally for delivering all kinds of products. A central theme of the book is that “IT,” considered as a component, represents an increasing proportion of ALL industrial products (both consumer and business facing). This is known as "digital transformation."

Current MIS survey texts have some common characteristics:

* They tend to focus on the largest organizations, and their applications of computing. This can lead to puzzling topic choices; for example, in one text, one of the first sections is dedicated to the problem of enterprise IT asset management - a narrow topic for the earlier sections of a survey course.
* Their learning progression (structure and narrative) is often arbitrary, e.g., covering "databases," "networking," "ERP systems," "security," and so forth in various orderings.
* They do not (and this is a primary failing) cover Agile and its associated digital ecosystem. Brief mentions of Agile may appear in sections on project management, but in general there is a lack of awareness of the fundamental characteristics of digital transformation, and the critical role of Agile and related methods to accelerating digital transformation.
* Their coverage of Cloud infrastructure also tends to be limited, even with new editions coming out every year.
* Finally, current texts often uncritically accept and cite "best practice" IT frameworks such as CMMI, ITIL, PMBOK, and COBIT. New digital organizations do not, in general, use such guidance and the industry at this writing is rife with controversy as to the value and future of these frameworks. This book provides a clear and objective overview of these critical issues.

IT, or the digital function, has had a history of being under-managed and poorly understood relative to peer functions in the enterprise. It struggles with a reputation for expensive inflexibility and Dilbert-esque dysfunction. The DevOps and Agile movements promise transformation, but are encountering an entrenched legacy of:

* enterprise architecture,
* program and project management,
* business process management,
* IT service management practices, and
* IT governance concerns

Understanding and engaging with the challenges of this legacy are an ongoing theme throughout this introductory text.

Some of the more radical voices in the Agile movement sometimes give the impression that the legacy can be simply swept away. The following cautionary message from Mike Burrows shows that, in terms of core Agile philosophy, this would be ill-advised:

_“…some will tell you that when things are this bad, you throw it all away and start again. It's ironic: The same people who would champion incremental and evolutionary approaches to product development seem only too eager to recommend disruptive and revolutionary changes in people-based systems – in which the outcomes are so much less certain.”_ <<Burrows2014>>, Kindle Locations 827-829.

IT management at scale within an organization is a complex system. Complex systems do not respond well to dramatic perturbations. They are best changed incrementally, with careful monitoring of the consequences of each small change. (This is part of the systems theory foundation underlying the Agile movement.) This is why the book, especially in the later chapters, starts with relatively straightforward and uncritical presentations of the following topics:

* Investment, sourcing, and people
* Project and process management
* Governance, risk, security, and compliance
* Enterprise information management
* Enterprise architecture and portfolio management

While these practices, and their associated approaches and policies, have caused friction with digital and Agile practitioners, they all have their reasons for existing. The goal of this book is to understand their interaction with the new digital approaches, but in order to do this we must first understand them on their own terms. It does no good to develop a critique based on misconceptions or exaggerations about what (for example) "process management" or "governance" is all about. Instead, we try to break these large and sometimes controversial topics down into smaller, more specific topics - "lowest common denominators," perhaps:

* Work
* Ordering of tasks
* Task dependencies
* Estimation vs. commitment
* Repeatability
* Defined vs. empirical process control
* Synchronization and cadence
* Resource demand
* Shared mental models
* Mission objectives vs perimeter defense
* Technical debt
* Risk

and so forth. By examining IT management in these more neutral, specific terms, we can develop a responsible critique of current industry "best practices" in content and form that will benefit students as they go out on their careers.

anchor:0.01-emergence[]

=== A process of emergence

[quote, Steve Blank, The Four Steps to Epiphany]
Joseph Campbell popularized the notion of an archetypal journey that recurs in the mythologies and religions of cultures around the world. From Moses and the burning bush to Luke Skywalker meeting Obi wan Kenobi, the journey always begins with a hero who hears a calling to a quest... +
 +
The hero’s journey is an apt way to think of startups. All new companies and new products begin with an almost mythological vision— a hope of what could be, with a goal few others can see...  +
 +
Most entrepreneurs feel their journey is unique. Yet what Campbell perceived about the mythological hero’s journey is true of startups as well: However dissimilar the stories may be in detail, their outline is always the same.

[quote, John Gall, The Systems Bible]
A complex system that works is invariably found to have evolved from a simple system that worked. A complex system designed from scratch never works and cannot be patched up to make it work. You have to start over, beginning with a working simple system.

One of the most important and distinguishing features of this book is its "emergence model." In keeping with the entrepreneurial spirit of works like Ries' http://www.amazon.com/dp/0307887898/[_The Lean Startup_,] the book adopts a progressive, evolutionary approach. The student's journey through it reflects a process of emergence. Such processes are often associated with founding and scaling a startup. There are many helpful books on this topic, such as:

* http://www.amazon.com/Nail-then-Scale-Entrepreneurs-Breakthrough/dp/0983723605[_Nail it then scale it_] by Furr and Ahlstrom
* http://www.amazon.com/Scaling-Up-Companies-Rockefeller-Habits-ebook/dp/B00O5RR7QO/[_Scaling Up_] by Harnish
* http://www.amazon.com/Startup-CEO-Scaling-Business-Website/dp/1118548361[_Startup CEO_] by Blumberg
* http://www.amazon.com/The-Lean-Startup-Entrepreneurs-Continuous/dp/0307887898/ref=pd_bxgy_14_img_y[_The Lean Startup_] by Ries

The emergence model and overall book structure is discussed in depth in the main introduction. Here are some notes on the thought process. I have spent considerable time thinking (agonizing) about the correct ordering of the chapters within these sections. This is possibly the tenth or twelfth version of the chapter ordering. This is an area where I want critical review, but also have strong opinions.

There is benefit to restricting the chapters to 12, as a typical semester runs 14 weeks and the book then fits quite nicely, with one chapter per class and allowing for an introductory session and final exam. (Trying to modfiy the semester system is out of scope for this project.) Of course, a two-semester series, with 2 weeks per chapter, would also work well; each half of the book is also a logical unit.

The governing thought experiment is, "what would I turn my attention to next as my IT-based concerns scale up?" For example, I think work management (implying rudimentary workflow, e.g. Kanban) correctly comes before formalized project management, and project management comes before fully formalized process management (including frameworks such as CMMI, COBIT and ITIL).

Note that this would be a testable and falsifiable theory, if empirical research were done to inventory and characterize organization scaling patterns. If we found (for example) that a majority of organizations formalize governance, risk, security and compliance practices before formalizing project management, that would indicate that those chapters should be re-ordered.

(In my experience, small/medium businesses may have some formal IT project management capability but security & GRC are still tacit, not formalized. This does not mean security is not a concern, but they have not yet hired a CISO, nor instituted formal controls).

The presence of Product Management at an early stage is intended to provoke. Product management is poorly addressed in most current CSci/MIS/IT education, as well as the reigning industry standards. Yet formalizing it is one of the earliest concerns for a startup, and the imperatives of the product vision drive all that comes after.

Evidence to this effect is seen (as of 2015) at the University of California at Berkeley I-School, which has replaced its Project Management course with http://www.ischool.berkeley.edu/courses/i290m-lapm[Lean/Agile Product Management], taught currently by the esteemed Jez Humble.

Also, you may notice that *the chapter titles don't necessarily reflect "Agile" terminology*. This is also deliberate, as students are going into a diverse world of much long-established IT. Furthermore, putting "Agile" as a qualifier on each chapter seems gratuitous (e.g. "Agile Operations Management" instead of just "Operations Management.")

The first word of the book's title is "Agile." That declares the orientation, and the proof will be in the reading. My intent is to involve experienced Agile practitioners in contributing to the sections most relevant to them, and I anticipate a high quality end result that is recognizably supportive of the Agile movement's goals and ambitions.

The book however is not a complete dismissal of older models of IT delivery. Wherever possible, Agile is presented as an evolutionary step relative to what has gone before. The specifics of "what's different" are identified, in the interest of de-mystifying what can be a fraught and quasi-religious topic. In the words of Don Reinertsen, you can have "faith based Agile or science based Agile." This book is strictly interested in the latter. Pointers to relevant theory are included, although this is NOT a theoretical text. That may come later.

*This emergence model can also be understood as an individual's progression within a larger enterprise.* Even if one starts from Day 1 at a Fortune 100 corporation, I believe the progression of one's understanding still progresses through individual, to team, to "team of teams," to enterprise. Of course, one may cease evolving one's understanding at any of these stages, with corresponding implications for one's career.

Some of you may be familiar with the idea of a Minimum Viable Product, Minimum Marketable Release, or similar. In these terms, it is important to understand that each *section* of the book represents an MVP, but not each chapter. One can't begin to deliver IT value without the components discussed in each of Chapters 1-3. The chapters of each section tend to be interdependent, in other words.

Structure within the structure: Each chapter flows in a roughly "top-down" fashion:

. "Business" concerns (value, motivation)
. "Process" concerns (execution, flow)
. Lean, Agile, and DevOps perspectives as appropriate
. "System" concerns (information & automation)

This book does not cover specific technologies in any depth. Many examples are used, but carefully framed to not require previous expertise. This is about broader, longer-lifecycle trends.

=== Labs
_Notes for instructors_
With three chapters in each section, the book can be covered in one intense semester at a chapter a week, although expanding it to a two-semester treatment would allow for more in-depth coverage and increased lab exposure.

I give great credit to both my students and Dr. Misra for challenging me to add a practical component to the course. This required new thinking on my part. How to demonstrate IT management at scale in a lab setting? I have learned that a hands on component is critical, as IT management discussions can be  abstract and meaningless to many students. (”Incidents are different from Problems!”)

Ten years ago, the best that would have been possible would be paper case studies, perhaps augmented with spreadsheets. But new options are now available. The power of modern computers (even lightweight laptops) coupled with the widespread availability of open source software, makes it is now possible to expose students to industrial computing in a meaningful, experiential way.

I have found great utility in the use of lightweight virtualization technologies such as Vagrant, Virtualbox and Docker.  I recommend this approach wholeheartedly. I am always interested in hearing from other instructors who are working from the same approach.

At this writing I maintain my labs publicly on Github.  My syllabus and lab structure is under continual improvement. This is my current aspirational plan.

[cols="5*", options="header"]
|====
|Lecture|Topic|Business lab |Technical lab |Team size
|Course introduction |Structure, approach |None|SSH & workstation setup |Individual
5+|SECTION I: FOUNDER
|Chapter 1 |IT value |Defining an IT product - review SaaS examples |Linux command line | 2
|Chapter 2 |IT Infrastructure |Reviewing current IaaS offerings |Cloud and infrastructure as code - configuring a Vagrant machine manually & w/script that is checked into Github & modified | 2
|Chapter 3 |Applications||Continuous delivery pipeline | 2
5+|SECTION II: TEAM
|Chapter 4 |Product management |User stories. Fail fast/risk mgmt |Behavior-driven development |6-8
|Chapter 5 |Work management 2+^|Scrum, ticketing and kanban |6-8
|Chapter 6 |Operations management |Service definition |Monitoring (Calavera + Nagios) | 6-8
5+|SECTION III: TEAM OF TEAMS
|Chapter 7 |Organizational structure |Organizational forms & communication channels (paper exercise?) |Continue Nagios | >11 (full class)
|Chapter 8 |Project & resource management | |Open-source project tool | >11 (full class)
|Chapter 9 |Process management | |Open-source ITSM suite | >11 (full class)
5+|SECTION IV: ENTERPRISE
|Chapter 10 |Security, governance, risk, and compliance |  | | 5
|Chapter 11 |Enterprise Information Management |Portfolio simulation |Porfolio simulation with R? | 5
|Chapter 12 |Architecture and portfolio | Archi (open source modeling tool) | |5
|====

I use a central server in teaching my classes, but even that is not necessary. This class can be taught with a zero computing budget, assuming that each team of students at least has access to a modern laptop and a fast Internet connection. As of this writing, I am using free and open source versions of Chef, Jenkins, iTOP, jUnit, Ant, and other tools (see github for the current approach).

Some may question the inclusion of command-line experience, but without some common technical platform it is hard to provide a meaningful “hands-on” experience in the first half of the course. I structure my class on the assumption that the students are at least willing to learn computing techniques, with no prerequisites beyond that. Not even a programming language is required; the Java currently used as a sample is minimal.

Truly beginning students will have to work at the Linux tutorials, but all they need master is basic command line navigation, and I have found this possible with a diverse student body, some with no previous direct experience. The labs for the second half of the course use games, experiential paper-based classroom exercises, GUI-based software, databases, and office productivity tools.

endif::instructor-ed[]
