anchor:chap-coordination[]

=== Chapter 7: Coordination


ifdef::collaborator-draft[]

****
*Collaborative*

 Status: Chapter 7 is rewritten to clean 1st draft as of 12/22/2016.

****

endif::collaborator-draft[]

==== Introduction

[quote, Online Etymology Dictionary]
coordination (n.)  co-ordination, c. 1600, "orderly combination," from French coordination (14c.) or directly from Late Latin coordinationem (nominative coordinatio), noun of action from past participle stem of Latin coordinare "to set in order, arrange," from com- "together" (see com-) + ordinatio "arrangement," from ordo "row, rank, series, arrangement" (see order (n.)). Meaning "action of setting in order" is from 1640s; that of "harmonious adjustment or action," especially of muscles and bodily movements, is from 1855.

[quote, Diane E. Strode et al, Coordination in co-located agile software development projects]
Agile software development methods were particularly designed to deal with change and uncertainty, yet they de-emphasize traditional coordination mechanisms such as forward planning, extensive documentation, specific coordination roles, contracts, and strict adherence to a pre-specified process cite:[Strode2012].

Growth is presenting us with many challenges. But we can't stop too long and think about how to handle it. We have to continue executing, as we scale up. The problem is like changing the tires on a moving car. It's not easy.

We've been executing since our first day in the garage. As noted xref:demand-supply-execute[above], execution is whenever we meet demand with supply. An idea for a new feature is demand. The time we spend implementing it is supply. The combination of the two is execution. Sometimes it goes well, sometimes it doesn't. Maintaining a tight xref:feedback[feedback]  loop to continually assess our execution is essential.

As we grow into multiple teams and multiple products, we have more complex execution problems, requiring coordination. The fundamental problem is the "D-word:" _dependency_. Dependencies are why we coordinate (work with no dependencies can scale nicely along the xref:AKF-cube[AKF x-axis].) But when we have dependencies (and there are various kinds) we need a wider range of techniques. Our one xref:card-wall[Kanban board] is not sufficient to the task.

We need to consider the xref:delivery-models[delivery models], as well (the "3 Ps": product, project, process, and now we've added program management.) Decades of industry practice mean that people will tend to think in terms of these models and unless we are clear in our discussions about the nature of our work we can easily get pulled into non-value-adding arguments. To help our understanding, we'll take a deeper look at process management, continuous improvement, and their challenges.

ifdef::instructor-ed[]
.Instructor's note on learning progression
****
The structure of Part III may be counter-intuitive. Usually, we think in terms of "plan, then execute." However, this can lead to waterfall and deterministic assumptions. Starting the discussion with execution reflects the fact that a scaling company does not have time to "stop and plan." Rather, planning xref:emergence-model[emerges] on top of the ongoing execution of the firm, in the interest of controlling and directing that execution across broader time frames and larger scopes of work.
****
endif::instructor-ed[]


===== Chapter overview

In this section, we will cover:

* Defining coordination
** Coordination & dependencies
** Concepts and techniques
** Coordination effectiveness
* Coordination, execution, and the delivery models
** Product management and coordination
** Project management as coordination
** Process management as coordination
* A deeper examination of process management
* Process control and continuous improvement

There is a discussion of business process modeling fundamentals in the xref:process-modeling[appendix].

===== Chapter learning objectives

* Identify and describe dependencies, coordination, and their relationship
* Describe the relationship of delivery models to coordination
* Describe process management and its strengths and weaknesses as a coordination mechanism
* Identify the problems of process proliferation with respect to execution and demand
* Identify key individuals and themes in the history of continuous improvement
* Describe the applicability of statistical process control to different kinds of processes
