ifdef::collaborator-draft[]

==== Topics in coordination and execution

===== DevOps, systems thinking, and the Change Management process


 devops CLD - goes here - discussion that optimizing for speed has counter-intuitive effects - does *not* de-optimize the other 2 necessarily - Edwards -


****
*Collaborative*

_20160609 Status: Like most topics sections, this one will remain rough until 2nd draft. Suggestions appreciated._

include::../../../collab-links.adoc[]

****

 Openspace sidebar in 3.07.01

 [recent popular press about problems of open space working, and responsive facilities with various workspace types available on reservation]

 Anderson's management cadencing

 ===== KPIs and metrics

  In the 1970s, social scientist Donald Campbell wrote that any metric of quality can become corrupted if people start prioritizing the metric itself over the traits it supposedly reflects. “We realized that his argument works even if individuals aren’t trying to maximize their metrics,” says Smaldino. [http://www.theatlantic.com/science/archive/2016/09/the-inevitable-evolution-of-bad-science/500609/?utm_source=fbia]

 ===== Tooling

BPMN, BPEL, and more

simulations:  systems dynamics & DES

ITSM tooling: process PLUS what is being acted on (portfolio)

formalisms: state charts, Petri nets

 The ERP problem, where IT management diverges from Agile

 ===== ISO 9000 http://www.iso.org/iso/pub100080.pdf

 ===== Measurement & ongoing execution
 Normalize costs to value adding activities (Abbott2015 p 112) - related to cost accounting??

 ===== Deeper theory

 "best practice"
 Cost of delay of aggregate process - research idea

 Kennelay - PID model

 formal process control
 the emergence of governance and assurance - Standards and processes are  meaningless without assurance. (chapt 10 foreshadow)

 review & incorporate more grounding from http://www.computing.dcu.ie/~mcrane/CA441/BPMLectureNotes.pdf[BPM Lecture Notes]

 http://jeffreymbradshaw.net/publications/Common_Ground_Single.pdf & allspaw commentary - the basic questions underlying various current arguments such as "DevOps v ITIL" and "No Projects"

 Cumulative flow diagrams - not important at team level? Move execution concepts to Part III - team of teams problems

 Synchronization:  I think there is a fundamental abstract model here of tasks and synch points - OS scheduling analogs? Mutexes/semaphores? emergent dependencies?

 contention for resources, alternatives to setting up queues

 Saddington 2012 IEEE paper on scaling Agile in Air Force - sent email 7/30


endif::collaborator-draft[]
