anchor:chap-process-mgmt[]

=== Chapter 7: Execution


ifdef::collaborator-draft[]

****
*Collaborative*

 Status: Part III is in major refactoring as of 12/1/2016

 chapter is in transition to new outline, project management's coordination and execution aspects will move here.

****

endif::collaborator-draft[]

==== Introduction

complete intro rewrite: defining execution management

we are expanding out from the moment of truth

instructor's note

===== Chapter overview


In this section, we will cover:

* Defining execution management
** Concepts and techniques
** Dependencies
** Coordination
** Synchronization
** Cadence
* Execution management and the delivery models
** Product and program management
** Project management
** Process management
* Execution through financial signals
* Process control and continuous improvement
* Challenges with process management
* Topics

There is a discussion of business process modeling fundamentals in the anchor:process-modeling[appendix].

===== Chapter learning objectives

* Identify differences between process and project management
* Describe a business process and how it crosses functions
* Demonstrate familiarity with basic principles of process modeling
* Understand the difference between defined and empirically controlled processes, and why this is important for digital product management
* Identify the problems of process proliferation with respect to execution and demand
* Describe the origins, purpose, and scope of IT industry frameworks
