anchor:3_07.00-Chap-7[]

=== Chapter 7: Organization and Culture

==== Introduction

In the last section, we introduced the xref:AKF-cube[AKF scaling cube], and we now start the second half of the book based on a related thought experiment. As your team-based company grew, you reached a crisis point in scaling your digital product. Your single team could no longer cope as one unit with the increasing complexity and operational demands. In AKF cube terms, you are scaling along the y-axis, the hardest but in some ways the most important dimension to know how to scale along.

You are going through a critical phase, the "team of teams" transition. You have increasingly specialized people delivering an increasingly complex product, or perhaps even several distinct products. Deep-skilled employees are great, but you've noticed they tend to lose the big picture. You are in constant discussions around the tension between functional depth versus product delivery.

You often think about how your company should be structured. There is no shortage of opinions there either. From functional centers of excellence to cross-functional product teams, and from strictly hierarchical models to radical models like holacracy, there seems to be an infinite variety of choices.

Many of your employees and consultants emphasize the role of culture, but what do they mean? Is there such a thing as a "good" culture? How is one culture better than another? How can you retain that startup feel you had previously, with things getting this big? You've always known intuitively that great hires are the basis for your company's success, but now you need to think more systematically about hiring.

Ultimately, as you move into leadership, you realize that your concern for organization and culture is all about creating the conditions for success. You can't drive success as an individual any more; that is increasingly for others to do. All you can do is set the stage for their efforts, provide overall direction and vision, and let your teams do what they do best.

===== Outline
* Why organization matters
** Product organization versus "IT" organization
Features versus components
* Product and function
** Waterfall and functional organization
** The continuum of organizational forms
* Defining the organization
* Culture
** Motivation
** Schneider and Westrum
** Toyota Kata
* IT human resource management
** Basic concerns
** Hiring
** Allocation and tracking people’s time
** Accountability and performance

===== Learning objectives

* Identify and describe the factors driving an organization's differentiation into a multiple-team structure
* Identify and describe the organizational challenges and issues that result when a multiple-team structure is instituted
* Distinguish between functional versus product organizations
* Compare and contrast various organizational forms
* Discuss various concepts and aspects of culture in digital organizations
* Describe basic issues in digital hiring and human resource management
