==== Defining the organization

[quote, Joseph Flahiff]
The traditional approach is that we have work and we bring "the right people" to the work. To be nimble -- to have organizational agility -- we have to have great teams of people and bring the work to the team.

There are many different ways we can apply these ideas of traditional functional organizing versus product-oriented organizing, and features versus components. How does one begin to decide these questions?

===== Splitting teams

fault isolation terms
* swim lane  / pod
* shard/sliver
* pool

principles:

* shared nothing
* no blocking across lanes
* tx w/in swim lanes

* segregate money maker
* segregate incidents
* "natural" boundaries (e.g. customers)

The fundamental questions of the Y-axis split - where architecture emerges (!!  insight)

inevitable

* failure domains (abbott p 49)

architects need to be able to reason about and lead conversation about such matters

retain impact mapping - impact mapping re-visited for internal purposes - build on previous impact map?


===== Hard v soft teams
Long-tenured and highly experienced teams require less overhead from management and less communication internally to perform their responsibilities. (abbott p 45)


===== Norms and standards

importance of -
increase effectiveness and efficiency
xref to architecture
