==== Conclusion

In conclusion, we have considered:

* Defining dependencies and coordination
* Principles, and techniques of coordination
* Coordination and delivery models
* Process management
* Background and history of continuous improvement

Coordination is a hard problem, and will only get more difficult as you scale up. However, it's not magic and as a problem can be defined and analyzed. Process management is one response to the coordination problem (although its value extends beyond). Like any powerful tool, it has its dangers if misused. Be wary of claims of statistical process control in creative activities, and avoid burdensome process tracking and compliance approaches. 

===== Discussion questions

* Review http://apievangelist.com/2012/01/12/the-secret-to-amazons-success-internal-apis/[The Secret to Amazons Success Internal APIs]. Discuss in terms of solving coordination problems. Where does an API-based approach reach its limits as a coordination strategy?
* Have you experienced a problem where an improved process would have helped? What about a problem where process seemed to be the cause of it?
* What processes do you experience daily? Weekly?
* Sometimes, organizations try to treat a complex process as defined, instead of managing it empirically. Sometimes, people react by calling this "Taylorism." Why? Google and discuss.

===== Research & practice

* Review the xref:strode-dependency-taxonomy[Strode dependency taxonomy] and document examples. Present to your class for discussion.
* Research BPMN notation and use it to document a process familiar to you
* Research process simulation and prepare a report. Optionally, compare process simulation with systems dynamics modeling.
* We know that completely defined processes can be placed under statistical control, and that creative processes cannot be. What about processes falling between these two extremes, such as help desk call management? What does the research say about statistical control of such processes?

===== Further reading

Coordination is a general and abstract topic and the research from <<Strode2012>> and <<Klein2005>> is a good place to start. Practical discussions of coordination are found in <<Reinertsen2009>> (especially Chapter 7-8) and also <<Reinertsen1997>> and <<Smith1998>>. From a software practitioner's perspective see <<Cohn2010>>.
The history of Scrum is relevant, in particular <<Schwaber2002>>. Critiques of statistical process control for software are found in <<Binder1997>> and <<Racynski2008>>.

The definitive BPM reference is <<Rummler1995>>. Good practical applications are found in <<Burlton2001>>, <<Harmon2003>>, and <<Sharp2009>>. Lean theory is also essential, e.g. <<Womack2003>>, <<Rother2010>>.

*Books*

* Geary Rummler and Alan Brache, https://www.goodreads.com/book/show/390829.Improving_Performance[Improving Performance: How to Manage the White Space in the Organization Chart]

* Paul Harmon, https://www.goodreads.com/book/show/1219780.Business_Process_Change[Business Process Change: A Guide for Business Managers and BPM and Six Sigma Professionals]

*Articles*


*Videos*

* https://www.youtube.com/watch?v=zGD7-lolujE[Geary Rummler in 1981]

*Professional*

* http://www.bptrends.com/[BPTrends: BPM Analysis, Opinion, and Insight]
* http://www.processrenewal.com/articles-resources/[Process Renewal Group Articles and Resources]

*Research*

* Gary Klein et al, http://jeffreymbradshaw.net/publications/Common_Ground_Single.pdf[Common Ground and Coordination in Joint Activity]

* Thomas Malone and Kevin Crowston, http://computerscience.unicam.it/merelli/Calcolo/malone.pdf[The Interdisciplinary Study of Coordination]

* Diane Strode and Sid Huff, https://dro.deakin.edu.au/eserv/DU:30049080/strode-taxonomyofdependencies-2012.pdf[A Taxonomy of Dependencies in Agile Software Development]

* Wil M.P. van der Aalst,  http://wwwis.win.tue.nl/~wvdaalst/publications/p712.pdf[Business Process Management: A Comprehensive Survey]

*Other*

* Martin Crane, http://www.computing.dcu.ie/~mcrane/CA441/BPMLectureNotes.pdf[BPM Lecture Notes]
