anchor:chap-process-mgmt[]

=== Chapter 7: Coordination and execution


ifdef::collaborator-draft[]

****
*Collaborative*

 Status: Part III is in major refactoring as of 12/1/2016

 chapter is in transition to new outline, project management's coordination and execution aspects will move here.

****

endif::collaborator-draft[]

==== Introduction

complete intro rewrite: defining execution management


===== Chapter overview

In this section, we will cover:

* Defining coordination and execution management
* Considering execution management in terms of the delivery models
** Product and program management
** Project management
** Process management
* Different techniques for coordinating and executing work across diverse teams
* Why process management matters, and is not likely to go away
* Continuous improvement and process control
* Topics in coordination, execution, and process management in digital organizations

This remains a textbook primarily aimed at digital product management (from concept to operations), and this chapter is primarily about business process *in that context.* However, one of the problems with process management in IT and digital management is that it has not been well aligned to the broader topic of business process management in general. Therefore, this chapter starts with discussion of BPM fundamentals, and then covers IT process management in that light.

===== Chapter learning objectives

* Identify differences between process and project management
* Describe a business process and how it crosses functions
* Demonstrate familiarity with basic principles of process modeling
* Understand the difference between defined and empirically controlled processes, and why this is important for digital product management
* Identify the problems of process proliferation with respect to execution and demand
* Describe the origins, purpose, and scope of IT industry frameworks
