anchor:chap-process-mgmt[]

=== Chapter 7: Execution


ifdef::collaborator-draft[]

****
*Collaborative*

 Status: Part III is in major refactoring as of 12/1/2016

 chapter is in transition to new outline, project management's coordination and execution aspects will move here.

****

endif::collaborator-draft[]

==== Introduction

Growth is presenting us with many challenges. But we can't stop too long and think about how to handle it. We have to maintain execution, as we scale up. The problem is like changing the tires on a moving car. It's not easy.

We've been executing since our first day in the garage. As noted above, execution is whenever we meet demand with supply. An idea for a new feature is demand. The time we spend implementing it is supply. The combination of the two is execution. Sometimes it goes well, sometimes it doesn't. Maintaining a tight feedback  loop to continually assess our execution is essential.

As we grow into multiple teams and multiple products, we have more complex execution problems. The fundamental problem is the "D-word:" _dependency_. Dependencies are why we coordinate (work with no dependencies can scale nicely along the xref:AKF-cube[AKF x-axis].) But when we have dependencies (and there are various kinds) we need a wider range of techniques. Our one Kanban board is not sufficient to the task.

We need to consider the xref:delivery-models[delivery models], as well (the "3 Ps": product, project, process, and now we've added program management.) People will tend to think in terms of these models and unless we are clear in our discussions about the nature of our work we can easily get pulled into non-value-adding arguments.

We discuss finances for the first time here, as financial signals can be useful for managing execution. Finally, we'll take a deeper look at process management, continuous improvement, and their challenges.

ifdef::instructor-ed[]
.Instructor's not on learning progression

The structure of Part III may be counter-intuitive. Usually, we think in terms of "plan, then execute." However, this leads to waterfall, deterministic approaches. Starting the discussion with execution reflects the fact that a scaling company does not have time to "stop and plan." Rather, planning emerges on top of the ongoing execution of the firm, in the interest of controlling and directing that execution across broader time frames and larger scopes of work.

endif::instructor-ed[]


===== Chapter overview

In this section, we will cover:

* Defining execution management
** Concepts and techniques
** Dependencies
** Coordination
** Synchronization
** Cadence
* Execution management and the delivery models
** Product and program management
** Project management
** Process management
* Execution through financial signals
* Process control and continuous improvement
* Challenges with process management
* Topics

There is a discussion of business process modeling fundamentals in the xref:process-modeling[appendix].

===== Chapter learning objectives

* Identify differences between process and project management
* Describe a business process and how it crosses functions
* Demonstrate familiarity with basic principles of process modeling
* Understand the difference between defined and empirically controlled processes, and why this is important for digital product management
* Identify the problems of process proliferation with respect to execution and demand
* Describe the origins, purpose, and scope of IT industry frameworks
