anchor:chap-process-mgmt[]

=== Chapter 7: Coordination and execution


ifdef::collaborator-draft[]

****
*Collaborative*

 Status: Part III is in major refactoring as of 12/1/2016

 chapter is in transition to new outline, project management's coordination and execution aspects will move here.

****

endif::collaborator-draft[]

==== Introduction

complete intro rewrite: defining execution management


===== Chapter overview

In this section, we will cover:

* Defining coordination and execution management
* Different techniques for coordinating and executing work across diverse teams
* Considering execution management in terms of the delivery models
** Product and program management
** Project management
** Process management
* Coordination through financial signals
* Continuous improvement and process control
* Challenges with process management
* Topics in coordination, execution, and process management in digital organizations

There is a discussion of business process modeling fundamentals in the anchor:process-modeling[appendix].


===== Chapter learning objectives

* Identify differences between process and project management
* Describe a business process and how it crosses functions
* Demonstrate familiarity with basic principles of process modeling
* Understand the difference between defined and empirically controlled processes, and why this is important for digital product management
* Identify the problems of process proliferation with respect to execution and demand
* Describe the origins, purpose, and scope of IT industry frameworks
