==== Topics in organization and culture
ifdef::collaborator-draft[]

Dojo approach!

Culture change - lighthouse projects

****
*Collaborative*

_ 20160609 Status: Like most topics sections, this one will remain rough until 2nd draft. Suggestions appreciated._

include::../../../collab-links.adoc[]

****


 The mainstreaming of IT into the business

"Rogue" IT

Convergence diagram.

 ad-hoc & governance structures, committees

 Communities of practice
originated by Wenger, McDermott, and Snyder2002.

Types of COPs

 Feature vs Component at scale

We have previously discussed xref:2.04.02-features-v-components[feature vs component teams]. As a reminder, features are functional aspects of software (things people find directly valuable) while components are how software is organized (e.g. shared services and platforms such as data management).

As an organization grows, we see both the feature and component sides scale. Feature teams start to diverge into multiple products, while component teams continue to grow in the guise of shared services and platforms. Their concerns continue to differentiate and communication friction may start to emerge between the teams. How an organization handles this is critical.
 (forward ref to chap 9 shared svcs, Part IV lifecycles)

 Adam Smith and Frederick Taylor
- Taylor & cultural antipatterns (including the 'you just don't get X' antipattern)

 Bi-modal IT, a critique

 [to be written]

reference http://www.computerweekly.com/feature/How-CIOs-can-ramp-up-their-IT-clock-speed-as-pressure-grows[How CIOs can raise their 'IT clock speed' as pressure to innovate grows]

 Solving for decisionmaking & governance
No choice but to allocate fine-grained decision rights between product lines & guilds. See Reinertsen/Smith.

 Org change management -
 ProSci/ADKAR, Lean Change Mgmt

 the limits to "you build it, you run it" - employees are not owners...

 culture leads, compliance lags

 The problem of epistemic closure

 additional material
Toyota Way quadrant as cited in <<Cohn2010>> p145

 IT and learning (Langer)

 The business within a business paradigm has failed

 Microservices.... important - how multiple services interact.

 The rise of coaching

 incentives - making across the board incentives work, Knez 2002, harvard biz review

 Etsy : designated vs dedicated - Kevin M discussion - mentioned there was talk @ DevOpsDays MSP 2015

 Training Within Industry

 Github abandoning flat structure http://www.bloomberg.com/news/articles/2016-09-06/why-github-finally-abandoned-its-bossless-workplace

  Connor:Discussing Design: Improving Communication and Collaboration through Critique

  Second draft

   include http://www.slideshare.net/meetfelipe/slides-agile2016-stop-using-agile-with-waterfall-goals-goal-agility-with-okr
   https://www.amazon.com/dp/1119252393/ref=cm_sw_r_tw_awdo_x_YQKZxb3GM0P4P

   think more about whether OKR belongs Part II or III

   allspaw on joint activity. requires common ground of understanding and a compact of joint action http://paperswelove.org/2016/video/john-allspaw-common-ground/?utm_content=buffer893c4&utm_medium=social&utm_source=twitter.com&utm_campaign=buffer

Abbot p 12:

• How easily can I add or remove people to/from this organization? Do I need to add them in groups, or can I add individual people?
• Does the organizational structure help or hinder the development of metrics that will help measure productivity?
• Does the organizational structure allow teams to own goals and feel empowered and capable of meeting them?
• Which types of conflict will arise, and will that conflict help or hinder the mis sion of the organization?
• How does this organizational structure help or hinder innovation within my company?
• Does this organizational structure help or hinder the time to market for my products?
• How does this organizational structure increase or decrease the cost per unit of value created?
• Does work flow easily through the organization, or is it easily contained within a portion of the organization?


[quote, Alan Turing, Lecture on the Automated Computing Engine -- 1947]
Roughly speaking those who work in connection with the [Automated Computing Engine] will be divided into its masters and its servants. Its masters will plan out instruction tables for it, thinking up deeper and deeper ways of using it. Its servants will feed it with cards as it calls for them. They will put right any parts that go wrong. They will assemble data that it requires. In fact the servants will take the place of limbs... +
 +
As time goes on the calculator itself will take over the functions both of masters and of servants. The servants will be replaced by mechanical and electrical limbs and sense organs… The masters are liable to get replaced because as soon as any technique becomes at all stereotyped it becomes possible to devise a set of instruction tables which will enable the electronic computer to do it for itself…”

endif::collaborator-draft[]
