==== Topics in coordination and execution

====== Critical chain

Goldratt in the above-cited book Critical Chain develops a sophisticated critique of project estimation and the dysfunctions it promotes.

In a project requiring contributions from multiple skilled resources, a common practice is to ask each person, "how long will this take you?" The project manager then works the resulting estimates into the overall project plan.

The problem with this is that most people will estimate their time conservatively; they will forecast a longer duration than they actually require. When all these "padded" estimates are added together, the project may be unacceptably long. The agreed work will tend to expand to fill the time available (Parkinson's Law). Furthermore, most people will wait until the end of their window to perform their task - a person who asks for 3 weeks to perform one week of work will often not start until week 3. (Otherwise known as Student Syndrome.)

One of the reasons that people estimate conservatively is that project managers tend to be quite concerned if committed tasks are not performed on time. Failure to make the "deliverable" by the committed date may result in negative feedback to the employee's manager and resulting poor performance reviews.

Coupled with the above-cited drive to multi-tasking, these factors result in poor project performance, despite the array of modern project management techniques.

Goldratt suggested an alternate approach, in which the idea of "critical path" is enhanced with resource awareness. That is to say, the issue of timing and dependencies (itself a complex problem) is further enriched with the availability of resources to perform the work. (In general, the availability of assigned project resources is assumed, but this is not a wise assumption in project-centric environments.)

Estimation is handled more probabilistically, and the "critical chain" is *the combination of the critical path plus the resource assigned to complete the most critical task.* The theory is that a person performing such a task must be protected from distraction, and in fact project managers must expand their tools to effectively forecast and plan the critical chain.

This leads to some complex math, in particular a known problem called the Resource-Constrained Scheduling Problem. (e.g. http://www.iste.co.uk/data/doc_dtalmanhopmh.pdf) The fact that this problem is so notoriously difficult is indicative of the need for adaptive approaches; ultimately, rigorous analytic methods fail to cope with the complexity of such problems.

Craig Larman, in Scaling Lean and Agile Development, is sympathetic to the overall insights and goals of Critical Chain. However, with respect the full blown analytical approach it implies, he states

"We have seen two very large official "project management TOC" adoption attempts (and heard of one more) in companies developing software-intensive embedded systems... The practice was clearly heavy, not agile, and not lean. In all three cases, the approach was eventually found cumbersome and not very effective, and was dropped." <<Larman2009>>

ifdef::collaborator-draft[]

****
*Collaborative*

_20160609 Status: Like most topics sections, this one will remain rough until 2nd draft. Suggestions appreciated._

include::../../../collab-links.adoc[]

****

 Openspace sidebar in 3.07.01

 [recent popular press about problems of open space working, and responsive facilities with various workspace types available on reservation]

 ===== RACI
 RACI stands for

 * Responsible
 * Accountable
 * Consulted
 * Informed

 A RACI analysis is often used when accountability must be defined for complex activities. It is used in process management, and also is seen in  project management and general organizational structure.

 everyone can work on everything - changing Is into ARs.

 Since it is a precursor of both process and project management, it's therefore appropriate to cover it as part of generic work management.

  bring in reinertsen discussion (MDF or DPHT):

  focus on specific decisions rather than abstract concepts like empowerment and strong vs. weak teams. It is much more useful for teams to know which product features they can change without outside approval than it is to find out they are "empowered."

AKF 5%-95% rule for planning & execution - goes to the top of this chapter - Abbott2015 p 105, spend 5% plnning and 95% considering contingencies

"The focus is on the customer, and there is the general belief that to pursue that principle efficiently a process-oriented approach has to be adopted" Van Bon et al ITSM guide - badly flawed... scope of relevant process is narrowing...

 commander's intent


 ===== Management cadencing - e.g. kanban - LKI & Reinertsen

 ===== ITSM core processes

- Incident, Change, etc


 ===== KPIs and metrics

  In the 1970s, social scientist Donald Campbell wrote that any metric of quality can become corrupted if people start prioritizing the metric itself over the traits it supposedly reflects. “We realized that his argument works even if individuals aren’t trying to maximize their metrics,” says Smaldino. [http://www.theatlantic.com/science/archive/2016/09/the-inevitable-evolution-of-bad-science/500609/?utm_source=fbia]

anchor:shared-services[]
 ===== The shared services problem

 Lifecycle: collaboration, internal commoditization, external commoditization
 Effectiveness, efficiency, governance

 Examples of shared services for digital teams - layered nature


 Service catalog: act, offering, system

 Infrastructure vs business

 Benchmarkable

 Deeper discussion of virtual server provisioning as example (backref to ch2, forward to ch10)

example of service-ized process dysfunction

Adapting a services model to improve flow

(Notice that the services a functional area provides can be viewed as a form of product in and of themselves.)

Degree of automation
perils of "take a number" service-ization

* SLAs and the service catalog
** Service-izing functions: pros and cons

Scenario: repetitive yet error prone work
team to team interactions that become "servicized"

 Implication in various IT governance texts that the shared services team is accountable for optimal use of the shared resource. A very dangerous guideline when multiplied by numerous  COEs/SSs.

 The folly of local process optimization... CRITICAL to look at process in context

 ===== The BPM community


 ===== Tooling

BPMN, BPEL, and more

simulations:  systems dynamics & DES

ITSM tooling: process PLUS what is being acted on (portfolio)

 ===== The ERP problem
Where IT management diverges from Agile

 ===== ISO 9000 http://www.iso.org/iso/pub100080.pdf

 ===== Digital services playbook  https://playbook.cio.gov/#play10

 ===== Measurement & ongoing execution
 Normalize costs to value adding activities (Abbott2015 p 112) - related to cost accounting??

 ===== Deeper theory

"best practice"
Cost of delay of aggregate process - research idea

formalisms
 state charts, Petri nets

  Process as a Mintzberg liaison mechanism

  http://blogs.forrester.com/jean_pierre_garbani/09-06-26-my_issue_itil

  CPRET is a mnemonic for the basic definition of process in process engineering: it stands for Constraints, Product, Resources, input Elements and Transformation which are the basic components of a process. In process engineering, a process is a suite of transformations of elements into a given output (product) given a set of constraints and resources. From this definition, we can see that technology has a strong influence on the process: the transformation part is a clear function of the technology available as input and resources in IT are strongly influenced by the technology used. As we mostly deal with information and data in IT management processes, the type of data available is either helping or impeding the transformation part.


  Kennelay - PID model

 formal process control
 the emergence of governance and assurance - Standards and processes are  meaningless without assurance. (chapt 10 foreshadow)

 ****
 Sidebar: Lessons from manufacturing, operations research, etc

 Controversy of application to IT

 Will this have been foreshadowed?
 ****

 review & incorporate more grounding from http://www.computing.dcu.ie/~mcrane/CA441/BPMLectureNotes.pdf[BPM Lecture Notes]

  Process capability is the inherent variation of the process in relation to the specification limits. The smaller the process variation, the better the process's capability. <<Kan1995>>

  http://jeffreymbradshaw.net/publications/Common_Ground_Single.pdf & allspaw commentary - the basic questions underlying various current arguments such as "DevOps v ITIL" and "No Projects"

  critical importance of self-service

   Cumulative flow diagrams - not important at team level? Move execution concepts to Part III - team of teams problems

 devops CLD - goes here - discussion that optimizing for speed has counter-intuitive effects - does *not* de-optimize the other 2 necessarily - Edwards -

   Synchronization

   I think there is a fundamental abstract model here of tasks and synch points - OS scheduling analogs? Mutexes/semaphores? emergent dependencies?


   Velocity

   contention for resources, alternatives to setting up queues

   Saddington 2012 IEEE paper on scaling Agile in Air Force - sent email 7/30


endif::collaborator-draft[]
