=== Chapter 7: Investment management
 also considering title Product Portfolio, but that impacts Ch 12.
 "From product to porfolio?"

==== Introduction

In the last section, we introduced the xref:AKF-cube[AKF scaling cube], and we now start the second half of the book based on a related thought experiment. As your team-based company grew, you reached a crisis point in scaling your digital product. Your single team could no longer cope as one unit with the increasing complexity and operational demands. In AKF cube terms, you are scaling along the z-axis, the hardest but in some ways the most important dimension to know how to scale along. You know that this is not going to be an easy transition, but you have no choice.

So, why are we starting the second half of the book with a chapter titled "Investment management"? Because at its most fundamental, your decision to break your organization into multiple teams is an investment decision. You are going to devote some of your resources to one team, and some to another team, and there will be additional spending still held at a corporate level. How do you understand and manage these separate streams of investment? What is your approach for structuring them? How do you ensure that they are returning your desired results?

People are competitive. Your multiple teams will start to compete for investment. This is unavoidable. They will want their activities adequately supported, and their understanding of "adequate" may be different from yours. They will also be watching that the other teams don't get "more than their share" and are using their share efficiently. You start to see that the teams need to be constantly reminded of the big picture, in order to keep their discussions and occasional disagreements constructive. (You've also got a cross-team coordination problem, which we'll discuss in the next chapter.)

You begin also to see your vendor relationships (e.g. your Cloud providers) as a form of investment. As your use of their products deepens, it becomes more difficult to switch from them, and so you spend more time evaluating before committing. Open source changes the software vendor relationship to some degree, but it's still a portfolio of commitments and relationships requiring management.

Finally, you now have a dedicated CFO and you are increasingly subject to standard accounting and budgeting rules. But annual budgeting seems to be opposed to how you have chosen to run your company to date. What alternatives are there? You begin to see that your approach to financial management affects every aspect of your company, including your product team effectiveness.

===== Outline

===== Learning objectives

* Identify and describe the factors driving an organization's differentiation into a multiple-team structure
* Identify and describe the organizational challenges and issues that result when a multiple-team structure is instituted
* Identify and describe basic concerns of vendor management and their application to digital organizations increasingly relying on Cloud providers and open source software.
* Identify and describe issues of financial planning and budgeting as they affect digital product delivery in an uncertain and dynamic marketplace.
