==== Information management topics

ERP systems (special section??)

Knowledge mgmt

* Metadata: data management of the digital pipeline
* Big data and digital management - each apply to the other - two sides of the coin -
* Defining "analytics"
* The enterprise information model: a failed vision that will never go away.

===== EIM applied to digital delivery

 next material is EIM applied to IT, keep but reduce scope/importance somewhat - should still be a major chapter section

Analytics and metrics are a related topic for IT management. There are many ways that metrics can be used and misused. A clear understanding of organizational goals is essential to any metrics strategy. Analytics similarly requre an overall framework of continuous improvement so that their insights lead to real actions and value.

* IT analytics
 - grounded in continuous improvement
 - Portfolio and process data
 - The IT data warehouse
 - Looking ahead: Big Data, machine learning, text analytics


  The problem of representation

  Put three people in three rooms

 - one has a pencil & paper
 - one has a box of wooden matches
 - one has two cups, one with a number of marbles in it

  Each room looks out on an arena where horses are being shown. Count the horses.
