anchor:chap-ent-info-mgmt[]

=== Chapter 11: Enterprise Information Management

ifdef::collaborator-draft[]

****
*Collaborative*

 Status: Chapter 11 is in first draft as of 5 September 2016. Comments appreciated.

include::../../../collab-links.adoc[]

****

endif::collaborator-draft[]

==== Introduction to Chapter 11

Information? That's nothing new. Like many other topics, we start by noting that you've been managing information in some way since the earliest days of your organization.

Perhaps your company started by offering a social media-oriented service. You needed to track users and their activity. Or perhaps you started off with a focus on data science and analytics; your first product was based on harvesting insights from large data sets. Just as we haven't in this book talked too much about the specifics of programming languages or technical architectures, we also leave the more technical aspects of data science and analytics to other textbooks and courses.

However, *it is at the largest scale that we see the establishment of formal governance, control, and management techniques for information as a distinct and coherent problem domain.* Before, you might have been interested in "customer data" or "sales data" or "supply chain data." Now, you are concerned with *data* in general, and how to manage it, wherever and whatever it is.

You're also concerned with information, knowledge, records, reports, and a wide variety of other overlapping, and often difficult to define, concepts.

Information is the lifeblood of business. Simple records are the foundation of survival: lose your customer's order, and you won't be in business long. Beyond such basics, the insights you can gain from your data are increasingly the best competitive advantage you have. Whether or not you started your company with a focus on data science, you probably have data scientists now.

The sheer scale of the data you have is starting to become unmanageable. It costs money to store, and how much do you need to store? Your lawyers have started questioning whether its truly necessary to keep certain data indefinitely; they seem to think there is risk there.

You're also periodically confronted with seemingly wasteful duplication of data - isn't it possible to be a bit more efficient? Quality and security concerns are also increasing. You've seen competitors go out of business due to cyberattacks, and you've also seen that pervasive data quality issues can be a serious threat to your operations and customer relationships.

Yet, when you have tried to manage for more efficient or better-governed uses of data, you've not been happy with the resulting cost and bureaucracy. Not to mention complaints of development delays and loss of business agility. It's an ongoing challenge, and as best you can see, no-one anywhere has it entirely figured out.

IMPORTANT: As with other chapters in the later part of this book, we are going to introduce this topic "on its own terms." We will then add additional context and critique in subsequent sections.


===== Chapter 11 outline
* Information and value
** The origins of digital information
** The measurable value of information
** Information, efficiency, and effectiveness
* Data management basics
** The importance of context
** Data management and the DMBOK
** Data architecture and development
* Towards enterprise information management
** Advanced data management
** Enterprise records management
** Data Governance
* Analytics
** Analytics in context
** Data warehousing and business intelligence
* Agile information management
** Software versus data
** Next generation practices in information management
* Information management topics
** Social, Mobile, Analytics, and Cloud
** Big data
** Managing the information of digital delivery
** Additional topics
* Conclusion
