==== Framework for understanding enterprise information management

===== The road to information management
Information management as we will discuss in the rest of this chapter derives first from the large scale absorption of data into highly efficient, miniaturized, automated digital infrastructures with capacity orders of magnitude greater than anything previously known.

But cuneiform and quipu, hash marks on paper, financial ledgers, punched cards, vacuum tubes, transistors, and hard disks represent a continuum, not a disconnected list. Whether we are looking at a scratch on a clay tablet, or the magnetic state of some atoms in a solid state drive, there is one essential question:

*What do we mean by that?*

Consider the state of those atoms on a solid state drive. They represent the numbers 547. But without context, that number is meaningless. It could be:

* The numeric portion of a street address
* A piece of a taxpayer identification number
* The balance on a bank account
* A piece of the data uniquely identifying DNA in a crime

The state of this data may have significant consequences. A destination address might be wrong, a tax return mis-identified. A credit card might be accepted or declined. A mortgage might be approved or denied. Or the full force of the law may be imposed on an offender, including criminal penalties resulting from a conviction on the evidence stored in the computer.

The COBIT Enabling Information guide <<ISACA2012b>> proposes a layered approach to this problem:

[cols="2*", options="header"]
|====
|Layer|Implication
|Physical|The media (paper, electronic) storing the data
|Empirical|The layer that observes the signals from the physical, and distinguishes signal from noise
|Syntactic|The layer that encodes the data into symbols (e.g. ASCII)
|Semantic|The layer providing the rules for constructing meaning from syntactical elements
|Pragmatic|The layer providing larger, linguistic structuring
|Social|The layer that provides the context and ultimately consequence of the data (e.g. legal, financial, entertainment)
|====

Without all these layers, the magnetic state of those atoms is irrelevant.

A similar but simpler hierarchy is

* Data
* Information
* Knowledge

* Data is the context-less raw material.
* Information is data + context, which makes it meaningful and actionable
* Knowledge is the situational awareness to make use of information

The physical, empirical, and syntactic layers - (the basic data layer) are  in general out of scope for this book. They are the concern of broad and deep fields of theory, research, development, market activity, and standards.  (Chapter 2 on infrastructure is the most closely related).

Semantic, pragmatic, and social concerns (information and knowledge) are fundamental to this book and chapter. At digital scale - terabytes, petabytes, exabytes - establishing the meaning and social consequence of data is a massive undertaking.  Data management and records management are two practices by which such meaning is developed and managed operationally. We will start by examining data management as a practice.

===== The practice of data management

Data management is a long established practice in larger IT organizations. As a profession, it is represented by the Data Management Association (DAMA). DAMA developed and supports the Data Management Body of Knowledge (DMBOK), which is a primary influence on this chapter section.

anchor:DMBOK[]

===== DMBOK

The Data Management Body of Knowledge is similar to other frameworks presented in this book (e.g. ITIL, COBIT, and PMBOK.) It includes ten major functions:

* Data Governance
* Data Architecture Management
* Data Development
* Data Operations Management
* Data Security Management
* Reference and Master Data Management
* Data Warehousing and Business Intelligence Management
* Document and Content Management
* Meta-data Management
* Data Quality Management

Attentive readers will notice some commonalities with general areas covered in this book: Governance, Architecture, Operations, and Security in particular. Data at scale is a significant problem area and so the DMBOK provides a data-specific interpretation of these broader concerns, as well as more specialized topics.

We won't go through each of the DMBOK functions in order, but we will be addressing most of them throughout this chapter. 

===== The ontology problem

* OPAL, BORO, etc

* ontology/concept/domain

* ontologies. Problems in developing them.

CACM 3/16 article on lightweight ontology engineering.

BoundedContext and domain-driven design

fundamential semiotics problems - universality is not possible

abstraction through supertype
abstraction through subject area (choosing a focal concept)

===== Data and process
a brief look, more later in chapter 12

===== Data solutions
[quote, Graeme Simsion, Preface to Kent's Data and Reality]
The boundaries of an entity are arbitrary, our selection of entity types is arbitrary, the
distinction between entities, attributes, and relationships is arbitrary.

[quote, William Kent, Data and Reality]
An information system (e.g., database) is a model of a small, finite subset of the real world...We expect certain correspondences between constructs inside the information system and in the real world. We expect to have one record in the employee file for each person employed by the company. If an employee works in a certain department, we expect to find that department's number in that employee's record.

https://www.kalzumeus.com/2010/06/17/falsehoods-programmers-believe-about-names/
==== Managing the information resource


===== EIM processes & practices

Data as a lifecycle

Data and the SDLC

Controlled vocabularies

Master data management & its limitations (get Kevin M to write on product?)

Slowly changing dimensions

Data quality

===== EIM functions (classic)
data management

DMBOK goals

data warehousing

===== EIM artifacts & deliverables

backref prev section

definitions/designs
conceptual/logical/physical schema
Metadata

How do you manage data? How do you manage anything? In part, through collecting data about it. Wait - "data about data"? There's a word for that: *metadata*. We'll take some time examining it, and its broader relationships to the digital delivery pipeline.

===== EIM infrastructure
engineering & operations

core DBMS

ETL & messaging

BI & analytics

control layer

* modeling
* profiling/cleansing
* MDM
* records mgmt

===== EIM Sourcing

* market data
* infrastructure


Package management, CVE, market data

===== Data infrastructure

* Pre-SQL
* SQL
* NoSQL
* Schema inference
* CAP
* Advanced analytics
