==== Governance and information management

* Security & compliance revisited
* Records management
* E-discovery

BoundedContext and records management....

 Data Governance Strategies_final.pdf

Defining ownership / stewardship - roles

===== Information related risks
We've discussed the simple 4-tier info sensitivity model (backref). A comprehensive information classification model must accommodate:

* sensitivity
* regulatory
* records

that is, data is a black box tagged with "Public" or "Top Secret" or some such
or purely instrumental like "SOX" or "HIPAA" vs understanding the MEANING - e.g. "patient history" or "audit findings"

Data quality as a control <<DeLuccia2008>>

Data leakage

====== Data quality

data warehousing

definitions/designs
conceptual/logical/physical schema
Metadata

How do you manage data? How do you manage anything? In part, through collecting data about it. Wait - "data about data"? There's a word for that: *metadata*. We'll take some time examining it, and its broader relationships to the digital delivery pipeline.

===== Enterprise content mgmt


unstructured analytics

===== Records vs data
https://en.wikipedia.org/wiki/Records_management <-decent

ARMA


===== E-Discovery & Cyberlaw

 Records holds

 Special section on cyberlaw, litigation, investigation?

 Data safe harbor

 FRCP (frcp.pdf)
 Federal Rules of Civil Procedure
