==== Information management topics

ERP systems (special section??)

Knowledge mgmt

* Metadata: data management of the digital pipeline
* Big data and digital management - each apply to the other - two sides of the coin -
* Defining "analytics"
* The enterprise information model: a failed vision that will never go away.

 ===== Data infrastructure
engineering & operations

core DBMS

ETL & messaging

BI & analytics

control layer

* modeling
* profiling/cleansing
* MDM
* records mgmt

* Pre-SQL
* SQL
* NoSQL
* Schema inference
* CAP
* Advanced analytics

 ===== Business rules management

 ===== Internet of Things

 ===== Social media

 ===== ontology engineering
 * OPAL, BORO, etc

 * ontology/concept/domain

 * ontologies. Problems in developing them.
 ontology mining

 CACM 3/16 article on lightweight ontology engineering.
 abstraction through supertype
 abstraction through subject area (choosing a focal concept)

 ===== EIM applied to digital delivery

 next material is EIM applied to IT, keep but reduce scope/importance somewhat - should still be a major chapter section


Repositories, CMDBs, IT4IT

Analytics and metrics are a related topic for IT management. There are many ways that metrics can be used and misused. A clear understanding of organizational goals is essential to any metrics strategy. Analytics similarly requre an overall framework of continuous improvement so that their insights lead to real actions and value.

* IT analytics
 - grounded in continuous improvement
 - Portfolio and process data
 - The IT data warehouse
 - Looking ahead: Big Data, machine learning, text analytics


  The problem of representation

  Put three people in three rooms

 - one has a pencil & paper
 - one has a box of wooden matches
 - one has two cups, one with a number of marbles in it

  Each room looks out on an arena where horses are being shown. Count the horses.

 ===== EIM Sourcing (the market for data)

  * market data
  * infrastructure


  Package management, CVE, market data

 ===== Metadata and metamodels

 xref:commit-as-metadata[]

 Move up to 1st topic?

  - revisit BORO
  Metadata

  How do you manage data? How do you manage anything? In part, through collecting data about it. Wait - "data about data"? There's a word for that: *metadata*. We'll take some time examining it, and its broader relationships to the digital delivery pipeline.
