==== Agile information management
[quote, Dan McCrory]
Services and Applications can have their own Gravity, but Data is the most massive and dense, therefore it has the most gravity. Data if large enough can be virtually impossible to move.
<<McCrory2010>>

Enterprise information management (including data management) has had a contentious relationship to Agile methods. There are inherent differences in perspective between those who focus on implementing software, versus those who are concerned with data and information, especially at scale.

The tendency among software engineers is to focus on the conceptual aspects of software, without concern for the physical issues of computing. (This also is the fundamental distinction at the heart of anchor:continuous-delivery[DevOps].)



* The enterprise information model: a failed vision that will never go away.

BoundedContext and domain-driven design

fundamental semiotics problems - universality is not possible


* Domain driven design
* importance of patterns and ref archs - learn data through practice and pragmatism, there is no "right" way
* ontology mining
* inferred schemas
* Data as gravity
* the monolithic schema problem
* CAP revisited
* immutability: where does the data go?

http://searchcio.techtarget.com/definition/agile-business-intelligence-BI?utm_medium=EM&asrc=EM_NLN_56914325&utm_campaign=20160510_Word%20of%20the%20Day:%20Agile%20business%20intelligence%20(BI)_kherbert&utm_source=NLN&track=NL-1823&ad=907631&src=907631

* Non-invasive data governance (Seiner)

Centralized layer teams vs microservices

Microservices as a more realistic implementation mechanism, better suited to human cognition

The test data problem - nontrivial - proven to be a precursor to org performance - see Puppet Labs survey (Humble presentation 8/2016)
