==== Framework for understanding enterprise information management

===== Data, information, knowledge

laney quote: not that useful

* Zachman framework

The problem of representation

Put three people in three rooms

- one has a pencil & paper
- one has a box of wooden matches
- one has two cups, one with a number of marbles in it

Each room looks out on an arena where horses are being shown. Count the horses.

===== From concept to data
[quote, William Kent, Data and Reality]
A message to mapmakers: Highways are not painted red, rivers don't have county lines running down the middle, and you can't see contour lines on a mountain.

* OPAL, BORO, etc

* ontology/concept/domain

* ontologies. Problems in developing them.

CACM 3/16 article on lightweight ontology engineering.

BoundedContext and domain-driven design

fundamential semiotics problems - universality is not possible

abstraction through supertype
abstraction through subject area (choosing a focal concept)

===== Data and process
a brief look, more later in chapter 12

===== Data solutions
[quote, Graeme Simsion, Preface to Kent's Data and Reality]
The boundaries of an entity are arbitrary, our selection of entity types is arbitrary, the
distinction between entities, attributes, and relationships is arbitrary.

[quote, William Kent, Data and Reality]
An information system (e.g., database) is a model of a small, finite subset of the real world...We expect certain correspondences between constructs inside the information system and in the real world. We expect to have one record in the employee file for each person employed by the company. If an employee works in a certain department, we expect to find that department's number in that employee's record.

https://www.kalzumeus.com/2010/06/17/falsehoods-programmers-believe-about-names/

===== Data infrastructure

* Pre-SQL
* SQL
* NoSQL
* Schema inference
* CAP
* Advanced analytics
