anchor:chap-ent-info-mgmt[]

=== Chapter 11: Enterprise Information Management

ifdef::collaborator-draft[]

****
*Collaborative*

 Status: Chapter 11 is in active development as of 13 July 2016. Expect volatility.

include::../../../collab-links.adoc[]

****

endif::collaborator-draft[]

==== Introduction to Chapter 11

 [todo: write EIM intro]

 [next material is EIM applied to IT, keep but reduce scope/importance somewhat - should still be a major chapter section]

 Analytics and metrics are a related topic for IT management. There are many ways that metrics can be used and misused. A clear understanding of organizational goals is essential to any metrics strategy. Analytics similarly requre an overall framework of continuous improvement so that their insights lead to real actions and value.

IMPORTANT: As with other chapters in the later part of this book, we are going to introduce this topic "on its own terms." We will then add additional context and critique in subsequent sections.

===== Chapter 11 outline


Value
* Traditional value
* Big data, data science

Framework for understanding (top-down)
* History of information
* ontology/concept/domain
* solutioning
* infra eng

Managing the information resource
* processes & practices
* artifacts & deliverables
* infrastructure
* Sourcing
** data
** platform & capacity

Governance, risk, security, compliance

* Security & compliance revisited
* Records management
* E-discovery

Agile information management
* Domain driven design
* inferred schemas
* Data as gravity
* CAP

* Topics

===== The data management technology landscape

Pre-SQL
SQL
NoSQL
* Schema inference
CAP
Advanced analytics

information valuation http://ht.ly/X1ej300XPZj


This leads us beautifully to Chapter 11.
