==== Towards enterprise information management

The previous chapter was necessary, but narrow. From those basic tools of defining controlled vocabularies and mapping them onto computing platforms, has come today's digital economy and its exabytes of data.

The relational database as represented in the previous chapter can scale, as a single unit, to surprising volumes and complexity. Perhaps the most sophisticated and large scale examples are seen in Enterprise Resource Planning (more detail on this in the Topics section.) An ERP system can manage the supply chain, financials, human resources, and manufacturing operations for a Fortune 50 corporation, and itself constitute terabytes and tens of thousands of tables.

However, ERP vendors do not sell solutions for leading edge digital transformation. They represent the commoditization side of the xref:innovation-cycle[Innovation Cycle]. One cannot base a digital go-to-market strategy on them, as everyone has them.

Competing in the market requires systems of greater originality and flexibility, and that usually means some commitment to either developing them with internal staff or partnering closely with someone who has the necessary skills.

And as these unique systems scale up, a variety of concerns emerge, requiring specialized perspectives and practices.

===== Advanced data management

====== Master data management

There are various ways to categorize data. Frequently, it is categorized by business process or functional area (Sales, Marketing, Support, etc). However, another important way to understand data is by its non-functional characteristics. Some data is transactional (e.g. Invoice and Invoice Line Item in the above example) and some is more persistent (Customer, Product).

When data is highly persistent and used for many purposes across an enterprise, we may call it "master" or "reference" data. Classic examples of master data include:

* Geographic information (cities, states, zip codes)
* Widely used "codes" in the business (medical insurance makes extensive use of these)
*

the tricky boundary between configuration and customization

====== The "System of Record"

Defining ownership / stewardship - roles


====== Data quality

data warehousing

definitions/designs
conceptual/logical/physical schema
Metadata

How do you manage data? How do you manage anything? In part, through collecting data about it. Wait - "data about data"? There's a word for that: *metadata*. We'll take some time examining it, and its broader relationships to the digital delivery pipeline.

===== Enterprise content & records mgmt

unstructured analytics

https://en.wikipedia.org/wiki/Records_management <-decent

ARMA

===== Data Governance

====== Information related risks
We've discussed the simple 4-tier info sensitivity model (backref). A comprehensive information classification model must accommodate:

* sensitivity
* regulatory
* records

that is, data is a black box tagged with "Public" or "Top Secret" or some such or purely instrumental like "SOX" or "HIPAA" vs understanding the MEANING - e.g. "patient history" or "audit findings"

Data quality as a control <<DeLuccia2008>>

Data leakage

ways of abstracting

====== Information security & privacy

* Security & compliance revisited



====== E-Discovery & Cyberlaw

 Records holds

 Special section on cyberlaw, litigation, investigation?

 Data safe harbor

 FRCP (frcp.pdf)
 Federal Rules of Civil Procedure

 Data Governance Strategies_final.pdf <- v good finish reviewing
