==== Information and value

[quote, The Data Management Body of Knowedge]
No enterprise can be effective without high quality data.


[quote, Tom Davenport and Jeanne Harris, Competing on Analytics]
At a time when companies in many industries offer similar products and use comparable technology, high-performance business processes are among the last remaining points of differentiation. Many of the previous bases for competition are no longer available. Unique geographical advantage doesn't matter in global competition, and protective regulation is largely gone. Proprietary technologies are rapidly copied, and breakthrough innovation in products or services seems increasingly difficult to achieve. What's left as a basis for competition is to execute your business with maximum efficiency and effectiveness, and to make the smartest business decisions possible. And analytical competitors wring every last drop of value from business processes and key decisions.

information valuation http://ht.ly/X1ej300XPZj

===== The origins of digital information
[quote, Doug Hubbard, How to Measure Anything]
Measurement: A quantitatively expressed reduction of uncertainty based on one or more observations.

reification

* Babylonian accounting
* Aztec ropes

* The problem of quantitative representation
* Quantification enables qualitative
* All data is structured

===== Information and efficiency

IT doesn't matter - efficiency

===== Information and effectiveness

* Big data
* Data science
