==== Product design

[quote, Herbert Simon]
Everyone designs who devises courses of action aimed at changing existing situations into preferred ones.

[quote, Jacques Murphy, Pragmatic Marketing]
 What is a Product Manager? A Product Manager is the one person in the whole organization who owns the product Requirements effort. Requirements focuses on the WHAT, which means it isn't Development, which focuses on the HOW. And Marketing traditionally talks about the WHAT, but cannot necessarily decide what the WHAT should be. At least not at any useful level of detail.

Now that we have discussed the overall concept of product management, we can turn more specifically to the topic of product design.

The presence of a section entitled "product design" in this book is a marked departure from other IT management textbooks. "Traditional" models of IT delivery focus on projects and deliverables, concepts we will not explore until chapter 8.

However, the ideas of projects and deliverables represent approaches that are more xref:2.00.1-open-loop[open loop], or at least delayed in xref:2.00.01-feedback[feedback]. Design processes do not perform well when feedback is delayed. xref:system-intent[System intent], captured as a user story or requirement, is only an hypothesis until tested via implementation and user confirmation.

There are a wide variety of techniques and even "schools" of product design; we will consider a few representatives in this chapter section.

anchor:lean-startup[]

===== Lean Startup
[quote, Eric Ries, The Lean Startup]
The goal of a startup is to figure out the right thing to build— the thing customers want and will pay for— as quickly as possible. In other words, the Lean Startup is a new way of looking at the development of innovative new products that emphasizes fast iteration and customer insight, a huge vision, and great ambition, all at the same time.

Lean Startup is a philosophy of entrepreneurship developed by Eric Ries <<Ries2011>>. It is not specific to information technology; rather, it is broadly applicable to all attempts to understand a product and its market. (Remember according to our xref:prod-mgmt-definition[definition of product management] that a workable market position is essential to any product.)

The idea of the Lean Startup has had profound influence on product design, including market-facing and even internal IT systems. It is grounded in Agile concepts such as:

"Do the simplest thing that could possibly work."

Lean Startup calls for an iterative, "Build-Measure-Learn" cycle. Repeating this cycle frequently is the essential process of building a successful startup (whatever the digital proportion).

* Develop an idea for a Minimum Viable Product (MVP)
* Measure its effectiveness in the market (internal/external)
* Learn from the experiment
* Decide to persevere or pivot (change direction while leveraging momentum)
* New idea development, evolution of MVP

===== Product discovery techniques

 technology evolution - context - Wardley, Everett Rodgers diffusion theory

 Review Steve Blank

====== Business model canvas


anchor:impact-mapping[]

====== Impact mapping
 [TBW]
 * Effectiveness/efficiency/risk
 * INVEST
 * MoSCoW
 * 5 Whys

====== Business analysis and architecture
 Foreshadow BPM


===== Product architecture

anchor:feature-v-component[]

====== Features vs. components

anchor:2.04.02-features-v-components[]
As your product evolves, you may see an increasing differentiation of concerns, between features and components.

Features are *what* your product *does*. They are what the customers perceive as valuable. “Scope as viewed by the customer” as <<Kennaley2010>> says (p. 169).

Components are *how* your product is *built*, such as database vs. Web components. In other words, they are a form of infrastructure (but infrastructure you may need to build yourself, rather than just spin up in the Cloud).

Feature teams are dedicated to a clearly defined functional scope, while component teams are defined by their technology platform. Component teams may become shared services, which need to be carefully understood and managed (more on this in Section 3).

It may be easy to say that features are more important than components, but this can easily be carried too far. Do you want each feature team choosing its own database? Not recommended. Allowing feature teams to define their own technical direction can result in brittle, fragmented architectures, technical debt, and rework.

Software product management needs to be a careful balance between these two perspectives. Some http://blog.octo.com/en/feature-team-beyond-the-buzzword/[recommend] a ratio of:

* 70-80% Feature teams to

* 20-30% Component teams

We will be revisiting this more systematically in chapter 7.

====== Three business strategies
* operational excellence
* product leadership
* customer focus

====== Product owner as boundary setter
"Boundaries are provided by the product owner and often come in the form of constraints, such as

* I need it by June.
* We need to reduce the per-unit cost by half.
* It needs to run at twice the speed.
* It can use only half the memory of the current version."" <<Cohn2010>>, p 126

====== Software and systems engineering

Some of the most contentious discussions related to IT management and Agile come at the intersection of software and systems engineering, especially when large investments are at stake.

Frequent criticisms of Lean Startup and related trends are:

* They are relevant only for non-critical Internet-based products (e.g. Facebook and Netflix)
* Some IT products must fit much tighter specifications and do not have the freedom to "pivot" (e.g. aerospace & defense systems)

anchor:flower-and-cog[]

****
*Parable: The flower and the cog*

*THUNK!*

_Hello. Where did you come from?_

*I fell. From that machine.*

_Machine?_

*Yes, that big loud thing that just passed by. And is now stopped over there.*

_Why is it stopped?_

*Because I am no longer with it. The machine needs me to function. I am called a "cog." Where did you come from?*

_I am a flower. I grew from a seed._

*You ... grew?*

_Yes._

*You mean, no-one planned or designed you?*

_Not that I know of. What does it mean to be "designed" or "planned"?_

*I am part of a greater whole. The need for me was understood when that greater whole was conceived. I was designed to fit a very particular place. +
 +
 They had to try making me out of different metals, and different ways to build me. This took some time and effort -- longer than was planned, in fact. But it was always understood that there would need to be a cog in a certain place in the machine.*

_Interesting. So you will never be more than you are?_

*No. I will always be a cog. They might make a different machine, with different cogs, but they will not be me. Are you part of a machine?*

_No. I grew here because it suited me. I have continued to grow for a couple years. Eventually I may turn into a tree, if the conditions remain good. I can adapt to other trees, and find my way around them to the sunlight and the water I need. Or I may stay smaller, if I can't get the sunlight I need. Or I may die._

*Aren't you part of a system that defines your purpose?*

_Not that I know of. Sometimes I think I am a system myself, made up of my roots, stem, leaves, and flower. There are insects living on me who rely on me for food and shelter.  And I have the freedom to grow into one of the largest trees in this area.  That is worth it to me._

*Interesting. Well, it is good you are growing where you are, and not twenty feet further in that direction.*

_Why?_

*Because when they find me, or replace me and fix the machine, it will continue to clear all the land over there.*

_Oh._

VOICES: "Hey Joe, here's that gear the tractor must have thrown."

"Good, grab it and I'll see if I can't get it back in place at least temporarily until we can figure out why it happened."

*Bye.*

_Goodbye. Nice talking to you. Good luck._

*Thanks. You too.*

****

The above parable is meant to illustrate two very different product development worlds. Some product development is constrained by the overall system it takes place within. Other product development has more freedom to grow in different directions.

The cog represents the world of classic systems engineering -- a larger objective frames the effort, and the component occupies a certain defined place within it. And yet, it may still be challenging to design and build the component, which can be understood as a product in and of itself.

The flower represents the market-facing digital product that may "pivot," grow and adapt according to conditions. It also is constrained, by available space and energy, but within certain boundaries has greater adaptability.

Neither is better than the other, but they do require different approaches. In general, we are coming from a world that saw digital systems strictly as cogs, and moving towards a world in which digital systems are more flexible, dynamic, and adaptable.
