anchor:product-mgmt-chap[]

=== Chapter 4: Product Management

ifdef::collaborator-draft[]

****
*Collaborative*

 Status: This chapter is in active development from 2016-09-14 through 2016-09-18. Expect volatility.

include::../../../collab-links.adoc[]

****

endif::collaborator-draft[]

==== Introduction to Chapter 4

****
*Product Management?*

"Product management?" In a book on IT management? Those of you with industry experience, especially backgrounds in project-based enterprise software development, may be unfamiliar with the term. However, a focus on product development is one of the distinguishing features of Agile development, even if that development is taking place in a larger enterprise context.
****

As you grow your company, you are bringing more people in. You become concerned that they need to share the same vision that inspired you to create this company. This is the goal of product management.

Product strategy was largely tacit in Section I. Now you need more formalized approaches to discovering, defining, designing, communicating, and executing.

Furthermore, while we covered Agile principles and practices in some detail last chapter, we did not discuss *why* they work. In this chapter, we will cover the Lean theory of product management that provides a basis for Agile practices, in particular the work of Don Reinertsen.

===== Chapter 4 outline

* Why product management?
** The product vision
** Defining Product Management
** Process, project, and product management
** Productization as a strategy at Amazon
* Organizing the product team
** The concept of collaboration
** Lean UX
** Scrum
** More on product team roles
* Product discovery
** Formalizing product discovery
** Product discovery techniques
** Discovery and design
** Design
* Assorted topics in Product Management

===== Chapter 4 learning objectives

* Define and distinguish product versus project and process management
* Identify the key concerns of forming a collaborative product team
* Describe current product-oriented practices, such as Lean UX and Scrum
* Describe product design and discovery practices and concerns
