anchor:product-mgmt-chap[]

=== Chapter 4: Product Management

ifdef::collaborator-draft[]

****
*Collaborative*

 Status: This chapter is in "draft 1.5" - improved from original first draft completed in 2015.

include::../../../collab-links.adoc[]

****

endif::collaborator-draft[]

==== Introduction

****
*Product Management?*

"Product management?" In a book on IT management? Those of you with industry experience, especially backgrounds in project-based enterprise software development, may be unfamiliar with the term. However, a focus on product development is one of the distinguishing features of Agile development, even if that development is taking place in a larger enterprise context.
****

As you grow your company, you are bringing more people in. You become concerned that they need to share the same vision that inspired you to create this company. This is the goal of product management as a formalized practice.

Product strategy was largely tacit in Section I. As the founder, you used product management and discovery practices, and may well be familiar with the ideas here, but the assumption is that you did not explicitly *formalize* your approach to them. Now you need a more prescriptive and consistent approach to discovering, defining, designing, communicating, and executing a product vision across a diverse team.

In this chapter, we will define and discuss product management, and distinguish it from project and process management. We will cover how product teams are formed and what practices and attitudes you should establish quickly.

We will discuss a number of specific schools of thought and practices, including Gothelf's Lean UX, Scrum, and more specific techniques for product "discovery." Finally, we will discuss the concepts of design and design thinking.

===== Chapter 4 outline

* Why product management?
** The product vision
** Defining Product Management
** Process, project, and product management
** Productization as a strategy at Amazon
* Organizing the product team
** The concept of collaboration
** Lean UX
** Scrum
** More on product team roles
* Product discovery
** Formalizing product discovery
** Product discovery techniques
** Discovery and design
** Design
* Assorted topics in Product Management

===== Chapter 4 learning objectives

* Define and distinguish product versus project and process management
* Identify the key concerns of forming a collaborative product team
* Describe current product-oriented practices, such as Lean UX and Scrum
* Describe product design and discovery practices and concerns
