==== Product discovery

[quote, Herbert Simon]
Everyone designs who devises courses of action aimed at changing existing situations into preferred ones <<Simon1988>>.

[quote, Jacques Murphy, Pragmatic Marketing]
 What is a Product Manager? A Product Manager is the one person in the whole organization who owns the product Requirements effort. Requirements focuses on the WHAT, which means it isn't Development, which focuses on the HOW. And Marketing traditionally talks about the WHAT, but cannot necessarily decide what the WHAT should be. At least not at any useful level of detail. <<Murphy2007>>

Now that we have discussed the overall concept of product management, we can turn more specifically to the topic of product discovery and design.

NOTE: In this book, we favor the idea that products are "discovered" as much or more than they are "designed." But you will see both terms used throughout this chapter. See the parable xref:flower-and-cog[the Flower and the Cog] for an illustration of the difference.

The presence of a section entitled "product discovery" in this book is a  departure from other IT management textbooks. "Traditional" models of IT delivery focus on projects and deliverables, concepts we touched on in the  xref:2.04.01-process-project-product[last chapter section] but that we will not explore in depth until later in the book.

However, the idea of "product discovery" *within* the large company is receiving more and more attention. Even large companies xref:fowler-quote[benefit] when products are developed with tight-knit teams using fast feedback.

NOTE: The term "intrapreneurship" means "entrepreneurship inside a large company."

For our discussion here, the challege with the ideas of projects and deliverables is that they represent approaches that are more xref:2.00.1-open-loop[open loop], or at least delayed in xref:2.00.01-feedback[feedback]. Design processes do not perform well when feedback is delayed. xref:system-intent[System intent], captured as a user story or requirement, is only an hypothesis until tested via implementation and user confirmation.

===== Product context
 move this section to Chapter 1 after  10/1/2016

As you start to think about digital value, you must think about the context for your startup or product idea. A well known approach for this is the idea of the "diffusion theory," first researched by Everett Rogers <<Rogers2003>> and popularized by Geoffrey Moore <<Moore2014>> in his bestseller _Crossing the Chasm_.



The best known vis

technology evolution - context - Wardley, Everett Rodgers diffusion theory

you can't fully understand the context without feedback

Startups that are entering an existing market
Startups that are creating an entirely new market
Startups that want to resegment an existing market as a low-cost entrant Startups that want to resegment an existing market as a niche player

Blank, Steve (2013-10-02). The Four Steps to the Epiphany (p. 31). K&S Ranch. Kindle Edition.

====== Discovery versus design

Some of the most contentious discussions related to IT management and Agile come at the intersection of software and systems engineering, especially when large investments are at stake. We call this the "discovery versus design" problem.

Frequent criticisms of Lean Startup and related trends are:

* They are relevant only for non-critical Internet-based products (e.g. Facebook and Netflix)
* Some IT products must fit much tighter specifications and do not have the freedom to "pivot" (e.g. aerospace & defense systems)

anchor:flower-and-cog[]

****
*Parable: The flower and the cog*

*THUNK!*

_Hello. Where did you come from?_

*I fell. From that machine.*

_Machine?_

*Yes, that big loud thing that just passed by. And is now stopped over there.*

_Why is it stopped?_

*Because I am no longer with it. The machine needs me to function. I am called a "cog." Where did you come from?*

_I am a flower. I grew from a seed._

*You ... grew?*

_Yes._

*You mean, no-one planned or designed you?*

_Not that I know of. What does it mean to be "designed" or "planned"?_

*I am part of a greater whole. The need for me was understood when that greater whole was conceived. I was designed to fit a very particular place. +
 +
 They had to try making me out of different metals, and different ways to make me. This took some time and effort -- longer than was planned, in fact. But it was always understood that there would need to be a cog in a certain place in the machine.*

_Interesting. So you will never be more than you are?_

*No. I will always be a cog. They might make a different machine, with different cogs, but they will not be me. Are you part of a machine?*

_No. I grew here because it suited me. I have continued to grow for a couple years. Eventually I may grow 20 feet tall, if the conditions remain good. I can adapt to other plants, and find my way around them to the sunlight and the water I need. Or I may stay smaller, if I can't get the sunlight I need. Or I may die._

*Aren't you part of a system that defines your purpose?*

_Not that I know of. Sometimes I think I am a system myself, made up of my roots, stem, leaves, and flower. There are insects living on me who rely on me for food and shelter.  And I have the freedom to grow into one of the largest trees in this area.  That is worth it to me._

*Interesting. Well, it is good you are growing where you are, and not twenty feet further in that direction.*

_Why?_

*Because when they find me, or replace me and fix the machine, it will continue to clear all the land over there.*

_Oh._

VOICES: "Hey Joe, here's that gear the tractor must have thrown."

"Good, grab it and I'll see if I can't get it back in place at least temporarily until we can figure out why it happened."

*Bye.*

_Goodbye. Nice talking to you. Good luck._

*Thanks. You too.*

****

The above parable is meant to illustrate two very different product development worlds. Some product development is constrained by the overall system it takes place within. Other product development has more freedom to grow in different directions.

The cog represents the world of classic systems engineering -- a larger objective frames the effort, and the component occupies a certain defined place within it. And yet, it may still be challenging to design and build the component, which can be understood as a product in and of itself. Fast feedback is still required for the design and development process, even when the product is only a small component with a very specific set of requirements.

The flower represents the market-facing digital product that may "pivot," grow and adapt according to conditions. It also is constrained, by available space and energy, but within certain boundaries has greater adaptability.

Neither is better than the other, but they do require different approaches. In general, we are coming from a world that saw digital systems strictly as cogs, and moving towards a world in which digital systems are more flexible, dynamic, and adaptable.

And, when digital components have very well understood requirements, usually we purchase them from specialist providers (increasingly "as a service"). This results in increasing attention to the "flowers" of digital product design, as acquiring the "cogs" is relatively straightforward (more on this in the chapter 8 section on sourcing.).

====== Business model canvas

anchor:impact-mapping[]


====== Business strategy

 can you PIVOT to/from these

 * operational excellence
 * product leadership
 * customer focus

====== Impact mapping


====== Business analysis and architecture
  Foreshadow BPM

===== Product discovery techniques
[quote, Steve Blank, The Four Steps to Epiphany]
Startups that survive the first few tough years do not follow the traditional product-centric launch model espoused by product managers or the venture capital community...In particular, the winners invent and live by a process of customer learning and discovery. I call this process “Customer Development,” a sibling to “Product Development,” and each and every startup that succeeds recapitulates it, knowingly or not.

There are a wide variety of techniques and even "schools" of product discovery and design; we will consider a few representatives in this chapter section.
anchor:lean-startup[]


====== Lean Startup
[quote, Eric Ries, The Lean Startup]
The goal of a startup is to figure out the right thing to build— the thing customers want and will pay for— as quickly as possible. In other words, the Lean Startup is a new way of looking at the development of innovative new products that emphasizes fast iteration and customer insight, a huge vision, and great ambition, all at the same time.

Lean Startup is a philosophy of entrepreneurship developed by Eric Ries <<Ries2011>>. It is not specific to information technology; rather, it is broadly applicable to all attempts to understand a product and its market. (Remember according to our xref:prod-mgmt-definition[definition of product management] that a workable market position is essential to any product.)

The idea of the Lean Startup has had profound influence on product design, including market-facing and even internal IT systems. It is grounded in Agile concepts such as:

"Do the simplest thing that could possibly work."

Lean Startup calls for an iterative, "Build-Measure-Learn" cycle. Repeating this cycle frequently is the essential process of building a successful startup (whatever the digital proportion).

* Develop an idea for a Minimum Viable Product (MVP)
* Measure its effectiveness in the market (internal/external)
* Learn from the experiment
* Decide to persevere or pivot (change direction while leveraging momentum)
* New idea development, evolution of MVP

====== Others



 [TBW]
 * Effectiveness/efficiency/risk
 * INVEST
 * MoSCoW
 * 5 Whys
 * JTBD

===== Product architecture

 a little more architecture

anchor:feature-v-component[]

====== Features vs. components

anchor:2.04.02-features-v-components[]
As your product evolves, you may see an increasing differentiation of concerns, between features and components.

Features are *what* your product *does*. They are what the customers perceive as valuable. “Scope as viewed by the customer” as <<Kennaley2010>> says (p. 169).

Components are *how* your product is *built*, such as database vs. Web components. In other words, they are a form of infrastructure (but infrastructure you may need to build yourself, rather than just spin up in the Cloud).

Feature teams are dedicated to a clearly defined functional scope, while component teams are defined by their technology platform. Component teams may become shared services, which need to be carefully understood and managed (more on this in Section 3).

It may be easy to say that features are more important than components, but this can easily be carried too far. Do you want each feature team choosing its own database? Not recommended. Allowing feature teams to define their own technical direction can result in brittle, fragmented architectures, technical debt, and rework.

Software product management needs to be a careful balance between these two perspectives. Some http://blog.octo.com/en/feature-team-beyond-the-buzzword/[recommend] a ratio of:

* 70-80% Feature teams to

* 20-30% Component teams

We will be revisiting this more systematically in chapter 7.
