
anchor:chapter-app-deliv[]
anchor:chapter-3[]

=== Chapter 3: Application Delivery

ifdef::collaborator-draft[]

****
*Collaborative*

 Status 11/2016: This chapter is in "draft 1.5" - improved from original first draft completed in 2015.

include::../../../collab-links.adoc[]

****

endif::collaborator-draft[]


ifdef::instructor-ed[]

.Instructor's note
****
I have opted to defer the "theory" of Agile to Chapters 4 and 5. So, this chapter presents Agile and related concepts like iterative development without examining the underlying principles.

I do this because I have discovered that theory sometimes works better in retrospect. Many students increasingly come in with some exposure to Cloud and Agile methods at least, and Chapters 2 and 3 will seem comfortable and familiar. In Chapters 4 and on we challenge them with *why* Agile works.
****
endif::instructor-ed[]

==== Introduction
Now that we have some idea of IT value (and how we might turn it into a product), and have decided on some infrastructure, we can start building.

IT systems that directly create value for non-technical users are usually called "applications," or sometimes "services." As discussed in chapter 1, they enable value experiences in areas as diverse as consumer banking, entertainment and hospitality, and personal transportation. In fact it is difficult to think of any aspect of modern life untouched by applications. (This overall trend is sometimes called digital transformation.)

Applications are built from software, the development of which is a core concern for any IT-centric product strategy. Software development is a well established career, and a fast-moving field with new technologies, frameworks, and schools of thought emerging weekly, it seems. This chapter will cover applications and the software lifecycle, from requirements through construction, testing, building, and deployment into modern production environments. It also discusses earlier approaches to software development, the rise of the Agile movement, and its current manifestation in the practice of DevOps.

===== Chapter outline

* Introduction
* Learning objectives
* Basics of applications and their development
** Defining "Application"
** History of applications and application software
** Applications and infrastructure: the old way
** Applications and infrastructure today
* From waterfall to Agile
* The DevOps challenge
* Describing system intent
* Test-driven development and refactoring
** Test-driven development
** Refactoring
* Continuous integration
* Continuous deployment
* Application development topics
* Conclusion
** Discussion questions
** Research & practice
** Further reading

===== Learning objectives

* Understand history and importance of "application" concept
* Define "Agile" in terms of software development
* Identify key Agile practices
* Identify the major components of an end-to-end DevOps delivery pipeline.
