ifdef::collaborator-draft[]

==== Topics in Product Management


****
*Collaborative*

 Status: Like most topics sections, work in progress that will probably not be completed until 2nd or later drafts.

include::../../../collab-links.adoc[]

****

_Second draft ideas_


 more on QA, especially design & code reviews - big miss


 [more]

 ===== the "efficiency" fallacy
 Managed services are not 3 truck rolls: The screwdriver truck, the wire cutters truck, the conduit truck... efficiency


 Data-driven product discovery (foreshadow ch 11)

 ===== misc
 Poppendieck wastes as cited by Cobb, p177

  https://medium.com/@cwodtke/the-myths-of-ux-design-product-design-whatever-they-call-it-this-week-ef37a39cac6b#.7uj1khbdh - product mgmt, design, engineering - good breakdown


 https://twitter.com/johncutlefish/status/754389401728188416

 unused software: information generation (Standish revised understanding)

 what makes a good business analyst?

  Lean Enterprise "Turn central IT into a product development organization."


  ===== 2nd draft notes
   Incorporate insights from The-Nerdery_Product-Development_ebook.pdf

   entrepreneurs tell a story https://silvialisam.com/chris-sacca-s-639f0f5f3b9c#.j6sljdp0x (first section??)

   Cynevin. Complicated vs complex, what is computable.

   "double diamond" of design thinking




 https://www.amazon.com/Inspired-Create-Products-Customers-Love/dp/0981690408

 https://www.intercom.io/books/product-management

 review following deck for inclusions here
 * http://www.slideshare.net/Innolution/agile-isriskmanagementkenrubininnolution

endif::collaborator-draft[]
