==== Topics in organization and culture
ifdef::collaborator-draft[]

****
*Collaborative*

_ 20160609 Status: Like most topics sections, this one will remain rough until 2nd draft. Suggestions appreciated._

include::../../../collab-links.adoc[]

****

endif::collaborator-draft[]

 The mainstreaming of IT into the business

"Rogue" IT

Convergence diagram.

 ad-hoc & governance structures, committees

 Communities of practice
originated by Wenger, McDermott, and Snyder2002.

Types of COPs

 Feature vs Component at scale

We have previously discussed xref:2.04.02-features-v-components[feature vs component teams]. As a reminder, features are functional aspects of software (things people find directly valuable) while components are how software is organized (e.g. shared services and platforms such as data management).

As an organization grows, we see both the feature and component sides scale. Feature teams start to diverge into multiple products, while component teams continue to grow in the guise of shared services and platforms. Their concerns continue to differentiate and communication friction may start to emerge between the teams. How an organization handles this is critical.
 (forward ref to chap 9 shared svcs, section IV lifecycles)

 Adam Smith and Frederick Taylor
- Taylor & cultural antipatterns (including the 'you just don't get X' antipattern)

 Bi-modal IT, a critique

 [to be written]

reference http://www.computerweekly.com/feature/How-CIOs-can-ramp-up-their-IT-clock-speed-as-pressure-grows[How CIOs can raise their 'IT clock speed' as pressure to innovate grows]

 Solving for decisionmaking & governance
No choice but to allocate fine-grained decision rights between product lines & guilds. See Reinertsen/Smith.

 Org change management -
 ProSci/ADKAR, Lean Change Mgmt

 the limits to "you build it, you run it" - employees are not owners...

 culture leads, compliance lags

 The problem of epistemic closure

 additional material
Toyota Way quadrant as cited in <<Cohn2010>> p145

 IT and learning (Langer)

 The business within a business paradigm has failed

 Microservices.... important - how multiple services interact.

 The rise of coaching

 incentives - making across the board incentives work, Knez 2002, harvard biz review

 Etsy : designated vs dedicated - Kevin M discussion - mentioned there was talk @ DevOpsDays MSP 2015

 Training Within Industry

 Github abandoning flat structure http://www.bloomberg.com/news/articles/2016-09-06/why-github-finally-abandoned-its-bossless-workplace

  Connor:Discussing Design: Improving Communication and Collaboration through Critique

  Second draft

   include http://www.slideshare.net/meetfelipe/slides-agile2016-stop-using-agile-with-waterfall-goals-goal-agility-with-okr
   https://www.amazon.com/dp/1119252393/ref=cm_sw_r_tw_awdo_x_YQKZxb3GM0P4P

   think more about whether OKR belongs section II or III

   allspaw on joint activity. requires common ground of understanding and a compact of joint action http://paperswelove.org/2016/video/john-allspaw-common-ground/?utm_content=buffer893c4&utm_medium=social&utm_source=twitter.com&utm_campaign=buffer
