==== Topics in IT infrastructure

This and following chapters in this book will end with a "topics" section, in which current and specialized developments will be discussed.

anchor:commit-as-metadata[]

===== Configuration management, version control, and metadata
Version control, in particular source control, is where we start to see the emergence of an _architecture of IT management_. It is in the source control system that we first start to see _metadata_ emerge as an independent concern. Metadata is a tricky term, that tends to generate confusion. The term “meta” implies a concept that is somehow self-referential, and/or operating at a higher level of abstraction. So,

* the term meta-discussion is a discussion about the discussion;
* meta-cognition is cognition about cognition, and
* meta-data (aka metadata) is data about data.

Some examples:

* In traditional data management, metadata is the description of the data structures, especially from a business point of view. A database column might be named “CUST_L_NM,” but the business description or metadata would be “The last, family, or surname of the customer.”
* In document management, the document metadata is the record of who created the document and when, when it was last updated, and so forth. Failure to properly sanitize document metadata has led to various privacy and data security related issues.
* In telephony,  “data” is the actual call signal — the audio of the phone conversation, nowadays usually digitally encoded. Metadata on the other hand is all the information about the call: from who to who, when, how long, and so forth.

In computer systems, metadata can be difficult to isolate. Sometimes, computing professionals will speak of a “metadata” layer that may define physical database structures, data extracts, business process behavior, even file locations. The trouble is, from a computer’s point of view, a processing instruction is an instruction, and the prefix “meta” has no real meaning.

Because of this, this book favors a principle that *metadata is by definition non-runtime.* It is documentation, usually represented as structured or semi-structured data, but not usually a primary processing input or output. It might be “digital exhaust” - log files are a form of metadata. It is not executable. If it’s  executable (directly or indirectly), it’s digital logic or configuration, plain and simple.

So what about our infrastructure as code example? The artifact - the configuration file, the script - is NOT metadata, because it is executable. But the source repository commit IS metadata. It has no meaning for the script. The dependency is one way - without the artifact, the commit ID is meaningless, but the artifact is completely ignorant of the commit. The commit may become an essential data point for human beings trying to make sense of the state of a resource defined by that artifact. However, the version control system ...

_doesn’t care why files are changing. That is, the content of the changes doesn’t matter. As the developer, you might move a function from here to there and expect this to be handled as one unitary move. But you could, alternatively, commit the removal and then later commit the addition. Git doesn’t care. It has nothing to do with the semantics of what is in the files_ <<Loeliger2009>>.

*In this microcosm, we see the origins of IT management.*
It is not always easy to apply this approach in practice. There can be edge cases. Documentation stored in version control needs to be seen as "executable" in the context of the business process. But it too does not require or "know about" the comit. Ultimately *the concept of metadata provides a basis for distinguishing the _management_ of information technology from the actual _practice_ of information technology.*

ifdef::collaborator-draft[]

 ===== Operations basics
 Just enough Operations for the startup
 Prep chap 6


 ===== Web-scale IT

This section as of fall 2015 is yet to be written. Will summarize key insights from the site reliability community, including Allspaw and Limoncelli.

anchor:CAP-theorem[]

 ===== CAP theorem
 to be written

 ===== Technology lifecycle management

 [to be written]


 ===== additional material

 http://12factor.net/build-release-run

 Releases are an append-only ledger and a release cannot be mutated once it is created. Any change must create a new release.

 In the old world, environments were accepted to be different except where they needed to be consistent. In the new world, environments are assumed to be the same except where they need to be different.

 what makes a good infrastructure engineer

 ==== more on policy & config

 define idempotence
 
 Two important concepts have emerged in the past decade: policy-based management and promise theory. In brief, policy-based management and promise theory focus on “what,” not “how.” This may also be described as “declarative,” not “imperative” (see Sidebar).

 For example, the following shell script and Chef recipe do the same thing:

  create example - can’t find anything decent on web
  Use directory creation example with failure of script b/c not idempotent

 Increasingly, as operational performance is defined in code (the trend to Infrastructure as Code), operational issues are equivalent to development defects.

 ===== Cloud transition

 http://jpmorgenthal.com/2016/08/24/a-reality-check-on-everyones-moving-everything-to-the-cloud/ excellent

 choreography & orchestration - John Willis convo

  risk management & infrastructure choices (Charity Majors talk 7/21/2016 DevOpsDays MSP)

 ===== Architecture of IT management

 The concept of a version control system (variously known as source control, revision control, software configuration management, and other terms) is our first major software system for the “business of IT.” (The virtualized system previously discussed is what is *under management*; the source control system is part of the *management architecture*.)

 _describe modern infra managers, policy management, auto-scaling as an example, provide an example Chef script.._

endif::collaborator-draft[]
