==== Advanced topics

anchor:multi-tasking[]

 ===== Multi-tasking

 Context switching and multi-tasking
 [Human factors discussion]


Need to allocate between chapters 5, 8, 9 - or touch on & elaborate later?


 Relationship between features and tasks

 Decision rules
 Reinertsen Boeing case

 Rule engines


 Synchronization

 I think there is a fundamental abstract model here of tasks and synch points - OS scheduling analogs? Mutexes/semaphores? emergent dependencies?

anchor:cadence[cadence]

 Cadence

 Cadence is an important form of synchronization. [more]

 Velocity

Stories are meant to be independent and valuable. Tasks aren’t. By earning velocity at the level of tasks, it is possible to be 70% dev-complete for a release without a single story being dev-complete. <<Narayan2015>>



 A look ahead to project and process

Projects: fixed time/duration/scope, not repeatable.

Processes: repeatable...

 deferrable commitments

 [Dan Pink, Drive: Task, time, technique, and team]

 High priority: incorporate Common Ground paper http://jeffreymbradshaw.net/publications/Common_Ground_Single.pdf
