

=== Chapter 10: Governance, Risk, Security, and Compliance

ifdef::collaborator-draft[]

****
*Collaborative*

 Status: Chapter 10 is in first draft as of 13 July 2016. Comments appreciated.

include::../../../collab-links.adoc[]

****

endif::collaborator-draft[]

==== Introduction to Chapter 10

Operating at scale requires a different mindset. When you were starting out, the horizon seemed bounded only by your imagination, will, and talent.

At enterprise scale, it's a different world. You find yourself constrained by indifferent forces and  hostile adversaries, some of them competing fairly, and others seeking to attack by any means.

Whether or not you are a for-profit, publicly traded company, you are now large enough that audits are required; you also likely have directors of some nature. Like it or not, the concept of "controls" has entered your awareness.

As a team of teams, you needed to understand resource management, finance, the basics of multiple product management and coordination, and cross-functional processes. Now that you are an enterprise, you need also to consider questions of corporate governance. Your stakeholders have become more numerous and their demands have multiplied, so the well-established practice of establishing a governing body has been applied.

Security threats increase proportionally to the company's size. The talent and persistence of these adversaries is remarkable. Other challenging players are, on paper, "on the same side," but auditors are never to be taken for granted. Why are they investigating IT systems? What are their motivations and responsibilities? Finally, what laws and regulations are relevant to IT?

IMPORTANT: As with other chapters in the later part of this book, we are going to some degree introduce this topic "on its own terms." We will then add additional context and critique in subsequent sections.

More than any other chapter, the location of this chapter (and especially its Security subsection) in Section 4 draws attention. Again, any topic in any chapter may be a matter of concern at any stage in an organization's evolution.

You've been doing security since your company started, otherwise you would not have gotten this big. But now, you have a Chief Information Security Officer, formal risk management processes, a standing director-level security steering committee, auditors, and compliance specialists. That kind of formalization does not usually happen until an organization grows to a certain size.

We needed the content in Section 3 to get this far. We had to understand our structure, how we were organizing our strategic investments, and how we were engaging in operational activities. In particular *it's difficult for an organization to govern itself without some ability to define and execute processes, as processes often support governance controls and security protocols.*

This chapter covers "Governance, Risk, Security, and Compliance" because there are clear relationships between these concerns. They have important dimensions of independence as well. It is interesting that the popular Guide to the CISSP starts its discussion of security with a chapter titled "Information Security Governance and Risk Management." Governance leads to a concern for risk, and security specializes in certain important classes of risk. Security requires grounding in governance and risk management.

Compliance is also related but again distinct, as the concern for adherence to laws and regulations, and secondarily internal policy. Compliance is covered *prior* to risk, as some forms of compliance are not only about managing risk.

===== Chapter 10 outline

* Governance
* Enablers
* Risk management
* Compliance
* Assurance and audit
* Security
* Digital Governance


===== Chapter 10 learning objectives

* Define governance versus management
* Describe key objectives of governance according to major frameworks
* Define risk management and its components
* Describe and distinguish assurance and audit, and describe their importance to digital operations
* Discuss digital security concerns and practices
* Identify common regulatory compliance issues
* Describe how governance is retaining its core concerns while evolving in light of digital transformation
* Describe automation techniques relevant to supporting governance objectives throughout the digital delivery pipeline
