==== Conclusion

Conclusion placeholder

===== Discussion questions

Research further and discuss one of these
* http://www.zdnet.com/article/the-top-10-it-disasters-of-all-time-5000177729/[The top 10 IT disasters of all time]

===== Research & practice

* Beyond the brief discussion in this chapter, research how venture capital firms govern their portfolios of startup investments. Compare and contrast to public company governance.



===== Further reading

*Books*
* CISSP Guide

*Articles*
* Wikipedia on https://en.wikipedia.org/wiki/Corporate_governance[Corporate governance]
*
* http://www.zdnet.com/article/the-top-10-it-disasters-of-all-time-5000177729/[The top 10 IT disasters of all time]
* https://technet.microsoft.com/en-us/magazine/2006.09.businessofit.aspx
* http://searchdatamanagement.techtarget.com/definition/compliance
* http://continuousdelivery.com/2013/08/risk-management-theatre/
* http://www.sonatype.org/nexus/2015/11/13/did-you-wake-up-to-an-alert-about-the-java-deserialization-vulnerability

*http://www.slideshare.net/realgenekim/keeping-the-auditor-away[Keeping the Auditor Away: DevOps Audit Compliance Case Studies]

*Videos*

*Professional*

* http://www.corporatecompliance.org/

 revise/edit below from <<ISACA2012b>>

• The Business Model for Information Security (BMIS), ISACA, USA, 2010
• The 2011 Standard of Good Practice for Information Security, Information Security Forum (ISF), UK, 2011
• Common Security Framework (CSF), Health Information Trust Alliance (HITRUST), USA, 2009
• Extended Basic Input/Output System (EBIOS), Direction Centrale de la Sécurité des Systèmes d’Information
(DCSSI), Ministry of Defense, France, 2000
• Health Insurance Portability and Accountability Act (HIPAA)/Health Information Technology for Economic and
Clinical Health (HITECH), USA, 1996 and 2009, respectively
• ISO/IEC 27000 series, Switzerland, 2009-2012
• National Institute of Standards and Technology (NIST) Special Publication (SP) 800-53A, Guide for Assessing
the Information Security Controls in Federal Information Systems and Organizations, Building Effective Security
Assessment Plans, Department of Commerce, USA, 2010
• Operationally Critical Threat, Asset, and Vulnerability Evaluation SM (OCTAVE ® ), Carnegie Mellon Software
Engineering Institute (SEI), USA, 2001
• Payment Card Industry Data Security Standards (PCI DSS) v2.0, PCI Security Standards Council, USA, 2010
