

=== Chapter 10: Governance, Risk, Security, and Compliance

==== Introduction to Chapter 10
[quote, Shon Harris, Guide to the CISSP]
In reality, organizations have many other things to do than practice security.

Operating at scale requires a different mindset. When you were starting out, the horizon seemed bounded only by your imagination, will, and talent.

At enterprise scale, it's a different world. You find yourself constrained by...

Whether or not you are a for-profit, publicly traded company, you are now large enough that external audits are required; you also likely have directors of some nature... 

GRC, GRSC, why the chapter is named this way, relationships between...

Security threats increase proportionally to the company's size. The talent and persistence of these adversaries is remarkable. Other challenging players are, on paper, "on the same side," but auditors are never to be taken for granted. Why are they investigating IT systems? What are their motivations and responsibilities? Finally, what laws and regulations are relevant to IT? Data protection, retention, ?

IMPORTANT: As with other chapters in the later part of this book, we are going to introduce this topic "on its own terms." We will then add additional context and critique in subsequent sections.

More than any other chapter, the location of this chapter in Section 4 draws attention. Again, any topic in any chapter may be a matter of concern at any stage in an organization's evolution. But it is difficult to formalize security before certain organizational maturity steps have occurred, in particular formalization of process management.

You've been doing security since your company started, otherwise you would not have gotten this big. But now, you have a Chief Information Security Officer, formal risk management processes, auditors, and compliance specialists. That kind of formalization does not usually happen until an organization grows to a certain size.

 circle back to chapter 9 and mention importance of formal process for governance objectives.


===== Chapter 10 outline

 (write last)

===== Chapter 10 learning objectives

* Define governance vs. management
* Define risk management
* Discuss basic security concerns and practices
* Identify common regulatory compliance issues
** Data privacy (pointer to next chapter?)

 more
