==== Governance
[quote, Gorans in Scott Ambler, Disciplined Agile Delivery]
transforming to an agile delivery approach is difficult. Companies or government agencies that have been in existence for decades have built up layers of deep and wide waste, many of them around governance. +
 +
 Business or IT governance constructs and processes that do not support new technology-centric go-to-market models and products must be either replaced or substantially evolved; otherwise, they increase risk on the agile projects.”


****
Sidebar: Introducing ISACA
****

===== Governance and sourcing
We have already covered contracting in terms of software and Cloud. But in terms of the emergence model, it is typical that companies enter into contracts before having a fully mature sourcing and contract management capability with input from the governance, risk, and compliance perspective.


===== Governance and IT operating model
*  "Rogue" IT

===== IT Audit
[quote, Scott Ambler, Disciplined Agile Delivery]
Agile or not, a team ultimately has to meet legal and essential organizational needs, and audits help to ensure this.

 ask Patrick Stachenko to write sidebar on how audit moved into IT_

Phoenix project

===== Governance & process
importance of having the demand/execution framework in place to manage governance demand

===== When governance frameworks attack
Are they suited to define execution models?

organizational scar tissue
