
==== Risk
[quote, Committee of Sponsoring Organizations of the Treadway Commission, Internal Control - Integrated Framework]
Risk is defined as the possibility that an event will occur and adversely affect the achievement of objectives.

According to Treadway, control & risk are distinct but overlap

Define vulnerability, threat agent, threat, risk, control, exposure


"risk" does not include upside.

relationship to security - security requires a risk assessment, so we know what to secure

* Internal environment
* Objectives
* Event Identification
* Risk Assessment
* Risk Response
** Analysis
** avoidance
** acceptance
** transference
* Control Activities
** Understand
** Develop tests
** Perform tests
** Improve
* Information & Communication
* Monitoring

The enterprise can also consider evaluating scenarios that have a chance of occurring simultaneously. This is frequently
referred to as ‘stress’ testing

Management



Use COSO outline

risk architecture/flows - visual

Risk impacts some asset:

Assets/resources include:
– People and skills
– Organisational structures
– IT processes, e.g., modelled as COBIT 5 processes, or business processes
– Physical infrastructure, facilities, equipment, etc.
– IT infrastructure, including computing hardware, network infrastructure, middleware
– Other enterprise architecture components, including information, applications <<ISACA2013>> p32

loss, threat, vulnerability event types <<ISACA2013>> p32

risk appetite, risk tolerance, risk capacity <<ISACA2013>> p79

OCEG

Primary concepts: Risk and Control, M:M

Lines of defence (COBIT for Risk)

COBIT prefers to no longer use term "control"

===== Assurance
[quote, Max Ehrmann, "Desiderata"]
Exercise caution in your business affairs;
for the world is full of trickery.

[quote, James DeLuccia, "Successfully Establishing and Representing DevOps in an Audit"]
Businesses must find a level of trust between each other  . . .  3rd party reports provide that confidence. Those issuing the reports stake their name & liability with each issuance.

3-party


All audit is assurance, but not all assurance is audit.



external

Data center evaluations of cloud providers are a form of *assurance*.
SAS 70

IaaS assurance
SaaS assurance

Data safe harbor -to be discussed in next section

"Dynamic certification of Cloud services: Trust, but verify!" Lins et al, computing edge,

===== Benchmarking

===== Availability
foreshadow Simian Army

===== Continuity and recovery

A large class of risk that often results in projects or ongoing organizations

The nightmare of a cold standby failure in a legacy heterogeneous environment

Infrastructure as code can be a significant mitigator - investments can justify themselves



===== Security as a risk
(segue)

===== Risk management antipatterns
hubbard failure of risk management - review
