
==== Security
[quote, ISACA, Cobit 5 for Security]
ISACA defines information security as something that: Ensures that within the enterprise, information is protected against disclosure to unauthorised users
(confidentiality), improper modification (integrity) and non-access when required (availability).

[quote, Shon Harris, Guide to the CISSP]
In reality, organizations have many other things to do than practice security.

Security is a significant and well-known domain in and of itself. Ultimtely, however, *security is an _application_ of the governance principles discussed in the previous sections*. Deriving ultimately from the stakeholder's desire to sustain and protect the enterprise, security relies on accurate risk assessment, a clear enabling strategy (i.e. controls), and effective assurance practices (e.g. security audits). In fact, much of the previous material on controls was derived from the CISSP guide, because the concepts are generally applicable to risk management, not only security risks.

You have been practicing security since you first selected your initial choice of development platform in Chapter 2.

attack vs defense

CIA

Should align to principles/policy/process framework (draw picture)

===== Information classification
[quote, ISACA, Cobit 5 for Security]
At a time when the significance of information and related technologies is increasing in every aspect of business and public life, the need to mitigate information risk, which includes protecting information and related IT assets from ever-changing threats, is constantly intensifying.

Simple 4-tier

Foreshadow compliance and EIM sections

Foreshadow IT portfolio (rats, we do need that special section)

===== Security engineering
2-axis view

====== Security architecture

Authentication & authorization

Endless topic: encryption, network architectures, ... much published. Get a CISSP.

====== Sourcing and security
NIST CVE & other sources
Zero day - segue to SecOps

===== Security operations
Altered states -> events

Backref to Ch 6, state/config management

Event management

====== Functional
SOC overview

====== Process
Detection
Response
Forensics

Relationship to other IT processes

===== Security and assurance
Relationship to GRC

What *is* that auditor doing anyways? Are they security? Or governance?

Frameworks from a security perspective

ISO 27002
CISSP
(good overview in Moeller)
