
==== Digital Governance
[quote, Gorans/Ambler, Disciplined Agile Delivery]
transforming to an agile delivery approach is difficult. Companies or government agencies that have been in existence for decades have built up layers of deep and wide waste, many of them around governance. +
 +
Business or IT governance constructs and processes that do not support new technology-centric go-to-market models and products must be either replaced or substantially evolved; otherwise, they increase risk on the agile projects.

===== Historic IT governance: controlling the "order taker"

CIO-centric "order taking" organizational form is assumed through ISO 38500, Selig, Moeller

===== Governance and product centricity
Whether enterprise IT governance processes have grown unin
tentionally through evolving process improvements or grown intentionally through a
deliberate project, the questions a senior manager should ask include: "How good are my IT governance processes at effectively delivering strategic business value year after year?" and "Are my processes repeatable, predictable, and scalable, and are they truly meeting the needs of my business (outside of IT) and my customers?"
[an example of what is wrong - this fixation with repeatability]
 (MoellerXXXX)


===== A new class of risks

From an IT governance perspective, what is the role of IT risk management in the new digital world? It's not that risk management goes away. But there are significant new classes of risk that need to be better understood and managed:

 * Unmanaged demand leading to multi-tasking
 * High queue wait states
 * Slow feedback due to large batch sizes
 * Failure to incorporate cost of delay in resource allocation and work prioritization decisions
 * Cultural dynamics destructive of high team performance

(not to mention more technical risks)

re: principal-agent - one technique mentioned by <<Eisenhardt1989>> is to align interests through cultural intervention  - "relax the assumption
 of goal conflict between the principal and agent" p62 cites Demski/Ouchi/Perrow.
