
==== Topics

 ===== Antipatterns
 ====== Use of governance concerns to further agendas (Phoenix project John)

 "segregation of duties" as positional defense

 ===== Culture & GRC?

 ===== Implementation

 Benchmarking

 Trusted supply chain

 Promise Theory

 Cyberlaw (more discussion of legal in next chapter)

 Hotline / whistleblowing
 Social media

 Industry verticals

 More on cybernetics (Wiener)

 Weill approach - governance as decision rights - contrast w/Kanban, ongoing iterative self-organization -
 ====== Architecture and governance

  Technical policies - foreshadow Chapter 12

  Affect E, E, R (draw here or later)

  Reality on tech product: successful digital firms strongly govern tech portfolio, do not allow experimentation that could expand base tech footprint. See chapter 12.

Globalizaton: Whether intentional or accidental, globalization brings business operations into foreign markets with new oversight requirements. These requirements are unique to the region and may involve controls and safeguards not necessary in other regions. <<DeLuccia2008>> p 14

 https://en.wikipedia.org/wiki/Transactive_memory
