==== Governance

* Defining governance

transforming to an agile delivery approach is difficult. Companies or government agencies that have been in existence for decades have built up layers of deep and wide waste, many of them around governance. Business or IT governance constructs and processes that do not support new technology-centric go-to-market models and products must be either replaced or substantially evolved; otherwise, they increase risk on the agile projects.” (Paul Gorans as quoted in ...)

Ambler, Scott W.; Lines, Mark (2012-05-31). Disciplined Agile Delivery: A Practitioner's Guide to Agile Software Delivery in the Enterprise (IBM Press) (Kindle Locations 8081-8084). Pearson Education. Kindle Edition.

organizational scar tissue

We have already covered contracting in terms of software and Cloud. But in terms of the emergence model, it is typical that companies enter into contracts before having a fully mature sourcing and contract management capability with input from the governance, risk, and compliance perspective.

*  "Rogue" IT

****
Sidebar: Introducing ISACA
ask Patrick Stachenko to write sidebar on how audit moved into IT_

****

===== IT Audit
[quote, Scott Ambler, Disciplined Agile Delivery]
Agile or not, a team ultimately has to meet legal and essential organizational needs, and audits help to ensure this.

===== Governance & process
importance of having the demand/execution framework in place to manage governance demand

===== When governance frameworks attack
Are they suited to define execution models?
