==== Audit and compliance


===== Audit
[quote, Scott Ambler, Disciplined Agile Delivery]
Agile or not, a team ultimately has to meet legal and essential organizational needs, and audits help to ensure this.

Types of audit

* External
* Internal


Scope and bounds

* Finance
* IT

Recipient is key

controls vs enablers

====== External audit

"The Committee therefore recommends that all listed companies should establish an audit committee."  <<Cadbury1992>>, 4.35

An external auditor is chartered by a regulatory authority to visit an
enterprise or entity and to review and independently report the results of that review. <<Moeller2013>> p 319

Phoenix project example

====== Internal audit
[quote, Institute of Internal Auditors]
Internal auditing is an independent appraisal function established within an organization to examine and evaluate its activities as a service to the organization.

Usually reports to audit committee

"The function of the internal auditors is complementary to, but different from, that of the outside auditors." <<Cadbury1992>>, 4.39

the typical internal audit process requires scheduling a review, perform
ing a risk assessment and necessary audit procedures, and then reporting the results
of an audit to management and the audit committee.<<Moeller2013>> p 324

Institute of Internal Auditors

Auditing of areas other than security e.g. performance reporting

====== Audit practices
derived from <<ISACA2013a>>

Lifecycle

Scoping
* ID users of report (e.g. board audit committee)
* ID accountable/responsible parties
* ID Objectives
* ID controls/enablers

Performance

Fundamental: expected vs actual

* Enquire/confirm
Documentation, interviews, transactional validation

* Inspect
Process flows - trace tx thru system
Physical inspection/walkthroughs

* Observe

Attempt what is prevented

Embedded tooling/modules
Inspect the security protocols around them

 DevOps Audit Defense Toolkit discussion
 Evidence p 17


===== Compliance


discuss how they play out in terms of GRC

 Policy is not just about risk. That's why risk comes later. Policy is also about effectiveness, e.g. understanding cost of delay, not overburdening ... we understand risk as risk of loss, not ineffectiveness... but we still control for our policies that are intended to promote effectiveness...

 governance & innovation

 governance & efficiency

 governance & risk

 Overlaps with enablers

 Contracts - vendor & customer

 ====== Regulations of note
 * HIPAA
 * SOX
 * FERPA
 * PCI DSS
 * GLBA PII (NIST)

 (summarize each of these)

 Note that some of these regulations call for policy management.

 NOTE: Some companies need to institute formal policies quite early. Even a startup may need written policies, if it is concerned with regulations such as HIPAA. However, this may be done on an ad-hoc basis, perhaps outsourced to a consultant. (A startup cannot afford a dedicated VP of Policy and Compliance.) This topic is covered in detail in this section because at enterprise scale, ongoing policy management and compliance must be formalized.
