
==== Risk management
[quote, Committee of Sponsoring Organizations of the Treadway Commission, Internal Control - Integrated Framework]
Risk is defined as the possibility that an event will occur and adversely affect the achievement of objectives.

Primary concepts: Risk and Control, M:M

===== Risk management fundamentals

sometimes termed "ORM" for good reason

====== Loss aversion

In practice, governance practices often center on the management of risk and the quest for efficiency.

One explanation for this may be loss aversion.
Define vulnerability, threat agent, threat, risk, control, exposure, safeguard/control/enabler
(CISSP)

"risk" does not include upside.

relationship to security - security requires a risk assessment, so we know what to secure

* Internal environment
* Objectives
* Event Identification
* Risk Assessment
* Risk Response
** Analysis
** avoidance
** acceptance
** transference
* Control Activities
** Understand
** Develop tests
** Perform tests
** Improve
* Information & Communication
* Monitoring

The enterprise can also consider evaluating scenarios that have a chance of occurring simultaneously. This is frequently referred to as ‘stress’ testing

Management

Use COSO outline

risk architecture/flows - visual

Risk impacts some asset:

Assets/resources include:
– People and skills
– Organisational structures
– IT processes, e.g., modelled as COBIT 5 processes, or business processes
– Physical infrastructure, facilities, equipment, etc.
– IT infrastructure, including computing hardware, network infrastructure, middleware
– Other enterprise architecture components, including information, applications <<ISACA2013>> p32

loss, threat, vulnerability event types <<ISACA2013>> p32

risk appetite, risk tolerance, risk capacity <<ISACA2013>> p79

OCEG

Hubbard cautions on aggregating risk

single loss expectancy, annualized rate of occurrence, annualized loss expectancy



===== IT-related risks
Prominent issues - Barclay's, Target, etc
risk of learning wrong lessons w/r/t complex systems - more "rigor" is not necessarily the answer - impossibility of testing all outcomes (cite relevant SEng) -- THE FUNDAMENTAL ISSUE

defenses covered in subsequent section

principles: antifragility, defense in depth, fast feedback, automation (2-edged sword), analytics & pattern recognition - pointer back to chapter 6

====== Availability

importance of antifragility techniques

foreshadow Simian Army

====== Continuity and recovery

A large class of risk that often results in projects or ongoing organizations

The nightmare of a cold standby failure in a legacy heterogeneous environment

Infrastructure as code can be a significant mitigator - investments can justify themselves

====== Security as a risk
foreward ref

===== Controls
Management controls are the organization, policies, and procedures used by
agencies to reasonably ensure that
• programs achieve their intended results;
• resources are used consistent with agency mission;
• programs and resources are protected from waste, fraud, and misman
agement;
• laws and regulations are followed; and
• reliable and timely information is obtained, maintained, reported and used
for decision making.-'


===== Controls and enablers
[quote, Committee of Sponsoring Organizations of the Treadway Commission, Internal Control - Integrated Framework]
Internal control is a process, effected by an entity's board of directors, management, and other personnel, designed to provide reasonable assurance regarding the achievement of objectives relating to operations, reporting, and compliance.

****
Sidebar: Introducing ISACA
****

[quote, ISACA, COBIT 5 for Assurance]
The term 'control objective' is no longer a mainstream term used in COBIT 5, and the word 'control' is used only rarely. Instead, COBIT 5 uses the concepts of process practices and process activities.

Have existed from ancient times


****
The loaded term "control"
Controls language can be a barrier - it's a technical term of art

A "controlling" relationship

The technical term from control theory - error deliberately introduced to a function to move it in a desired direction (check Tunde)

COBIT no longer uses term. "" <<ISACA2013a>> p. 57.
****



====== COSO

Because it is so essential, official statements defining control carry much influence. The leading definition of internal control and its related practices is published by the Council of Sponsoring Organizations of the Treadway Commission (COSO).

*What is COSO?*

The Council of Sponsoring Organizations of the Treadway Commission (COSO) has a non-intuitive name, especially given its global influence.

COSO is a "private sector initiative," funded by:

* Institute of Certified Public Accountants (AICPA),
* American Accounting Association (AAA),
* Financial Executives International (FEI),
* Institute of Internal Auditors (IIA)
* Institute of Management Accountants (IMA).

It was founded in 1985 to support the National Commission on Fraudulent Financial Reporting, and has published various reports and guidance mostly concerned with the topic of internal control.

****
Control activities are the actions established through policies and procedures that help ensure that management's directives to mitigate risks to the achievement of objectives are carried out. Control activities are performed at all levels of the entity, at various stages within business processes, and over the technology environment. They may be preventive or detective in nature and may encompass a range of manual and automated activities such as authorizations and approvals, verifications, reconciliations, and business performance reviews.

Ongoing evaluations, separate evaluations, or some combination of the two are used to ascertain whether each of the five components of internal control, including controls to effect the principles within each component, is present and functioning. Ongoing evaluations, built into business processes at different levels of the entity, provide timely information. Separate evaluations, conducted periodically, will vary in scope and frequency depending on assessment of risks, effectiveness of ongoing evaluations, and other management considerations. Findings are evaluated against criteria established by regulators, recognized standard-setting bodies or management and the board of directors, and deficiencies are communicated to management and the board of directors as appropriate.
<<COSO2013>>

Concern: "recognized standard-setting bodies" - who? ISACA? Axelos?

****

====== Control categories
In this section we'll continue to use the generic term control as ultimately COBIT did not provide a good, terse substitute. "Testing enablers" is not how auditors talk.

Ultimately, controls are Lines of defence (COBIT for Risk)

Control functions (CISSP)
Deterrent
Preventive
Corrective
Recovery
Detective
Compensating

Typical general control types

* Separation of duties
* Audit trails
* Confidentiality and integrity
* Documentation

"Separation of duties" is very general and might be specified by activity type, e.g.

* Purchasing
* System development
* Sales revenue recognition

All of these would require distinct approaches to separation of duties. Some of this may be explicitly defined; if there is no policy or control specific to a given activity, an auditor may identify this as a deficiency.

Policies may set overall control objectives, but typically not at an operational level.


****
audit reports on the status of internal controls have been an ongoing issue between external auditors, the SEC, and other interested parties going back to at least 1974.

Under SOx, a separate and independent function within the enterprise—often internal or IT audit—reviews and documents the internal controls covering key processes, identifies key control points, and then tests those identified controls. External audit would then review that work and attest to their adequacy. For many enterprises, IT audit can be a key resource for performing these internal controls reviews for technology-based processes.

Internal and external auditors have historically been separate and independent resources. External auditors were responsible for assessing the fairness of an enter prise's internal control systems and the resultant published financial reports, while internal auditors served management in a wide variety of other areas.

Understanding Control Selection Processes
An enterprise needs to understand the costs and implications of various controls that it may establish as a response to various identified risks

While there have been many definitions of internal controls in past years,a good general definition for IT governance is that internal control is a process, effectedby an entity's board of directors, management, and other personnel, and designed toprovide reasonable assurance regarding the achievement of objectives in the effectiveness and efficiency of operations, the reliability of an enterprise's financial reporting, andan enterprise's IT systems and processes, all in compliance with laws and regulations.

An enterprise unit or process has good Internal controls If It (1) accomplishes Its statedmission In an ethical manner, (2) produces accurate and reliable data, (3) complies withapplicable laws and enterprise policies, (4) provides for the economical and efficient usesof Its resources, and (5) provides for appropriate safeguarding of assets. All members ofan enterprise are responsible for the Internal controls In their area of operation and foroperating them effectively.

That is. if a standard says that "management should monitor" some process or activity, the enterprise group supporting this area should be in a posi tion to demonstrate this monitoring activity through some level of documentation. [or automated event stream that is actionable]  <<Moelle2013>>
****


"Working to rule" - when they proliferate - demand implications

controls theater - cargo cult controls


==== Compliance

===== Compliance fundamentals
discuss how they play out in terms of GRC

 Policy is not just about risk. That's why risk comes later. Policy is also about effectiveness, e.g. understanding cost of delay, not overburdening ... we understand risk as risk of loss, not ineffectiveness... but we still control for our policies that are intended to promote effectiveness...

 governance & innovation

 governance & efficiency

 governance & risk

 Overlaps with enablers

 Contracts - vendor & customer

===== Regulations of note
 * HIPAA
 * SOX
 * FERPA
 * PCI DSS
 * GLBA PII (NIST)

 (summarize each of these)

 Note that some of these regulations call for policy management.

 NOTE: Some companies need to institute formal policies quite early. Even a startup may need written policies, if it is concerned with regulations such as HIPAA. However, this may be done on an ad-hoc basis, perhaps outsourced to a consultant. (A startup cannot afford a dedicated VP of Policy and Compliance.) This topic is covered in detail in this section because at enterprise scale, ongoing policy management and compliance must be formalized.

===== Ethics
