
==== Digital Governance
[quote, Gorans/Ambler, Disciplined Agile Delivery]
transforming to an agile delivery approach is difficult. Companies or government agencies that have been in existence for decades have built up layers of deep and wide waste, many of them around governance. +
 +
Business or IT governance constructs and processes that do not support new technology-centric go-to-market models and products must be either replaced or substantially evolved; otherwise, they increase risk on the agile projects.


===== A new class of risks


From an IT governance perspective, what is the role of IT risk management in the new digital world? It's not that risk management goes away. But there are significant new classes of risk that need to be better understood and managed:

 * Unmanaged demand leading to multi-tasking
 * High queue wait states
 * Slow feedback due to large batch sizes
 * Poor team cohesion, psychologically hostile environments
 * Failure to account for cost of delay

(not to mention more technical risks)
