
==== Policy, assurance and audit

===== Policy management

ifdef::collaborator-draft[]

****
*Collaborative*

 Status: This section is first draft as of 27 June 2016. Comments appreciated.

include::../../../collab-links.adoc[]

****

endif::collaborator-draft[]

anchor:how-pollicy-begins[]

****
*How policy begins*

Your company was incorporated long ago, but "board" was always a bit of a joke. The three people who started the company were the directors of record, and they would have an annual "meeting" at the local bar where enough paperwork would be done to satisfy the company lawyer.

Your company did well, and accumulated enough cash to purchase another company, run in much the same way. The people who owned the company being acquired were good, and your company didn't want to lose them, so in addition to senior management positions, they were offered equity -- a share of ownership in the new combined firm.

This raised the topic, "how is the new firm directed?" One of the incoming shareholders wanted a seat on the "board," even though neither company had done much with board-level governance.

The lawyer and accountant hired to assist with the merger also recommended that as part of the acquisition, a formal audit be conducted of both firms (which had never been done).

This audit came back generally clean, but shone a light on differences in how the companies had operated, and unearthed some irregularities.

For example, your company had started to purchase phones for all employees, while the acquired company was pure BYOD (Bring Your Own Device). One company had corporate credit cards, while the other was requiring people to carry their own expenses for reimbursement. One company had an informal "understanding" that first class travel was OK for Asian trips at least, while the other didn't, but neither had written anything down. And so on.

The lawyer said, "I think you need some policies," and everybody groaned. One person said, "I just read about Nordstrom. All they say is "Use Good Judgment." Why do we need anything more?"

The lawyer said, "Um, that's an urban legend. The actual Nordstrom Code of Business Conduct and Ethics, while it starts off with that, runs about 8,000 words and covers a variety of topics such as handling customer information, using technology, social media, and so forth."

And the new CFO said, "Look, I get that we want to stay agile, and keep our informal culture. I'm no fan of policy for the sake of policy. But I need those policies to keep *my* staff costs down. Two different expense approaches alone is going to kill me, and that's only one of twenty issues we've uncovered here. \'Do the right thing' doesn't cut it. We've got to have some means for establishing a baseline with new employees, someplace people can turn to when they don't know what the expectation is."

The HR director chimed in. "If we don't document our official position on things like  harassment we are going to have problems. We could fire someone who has done something really bad, and they (or their victims) could sue us for wrongful termination. That could cost us real money." The lawyer nodded and the company owners looked thoughtful.

Another person spoke up. "I came from a company that had a 500-page policy manual. It went down into way too much detail and was always out of date. No-one could find anything in it, and there would be stuff that was just wrong because the revision process was broken."

The lawyer said, "That's bad policy management. You need to keep your policies light and on the general side (like Nordstrom), and cover more detailed topics elsewhere. For example, the exact approach on how to reimburse employee expenses probably doesn't belong in the policy manual. Of course, that means that somewhere you need to lay out how your principles inform your policies which are implemented by processes, procedures, guidelines, and so forth. Your actual employee handbook will probably be thirty or forty pages - sorry."

Another said, "This is all getting complicated."

"Yes, complexity is to some extent unavoidable as you move to this new scale. I'm a big fan of sunset dates on policies and supporting materials, so you are periodically questioning whether something is still needed. Of course, this drives demand for someone to analyze and update policies - please don't forget that.

Overall, you need to always keep your outcomes in mind, and continue to push as much decision making down to individuals as you can. COBIT recognizes that culture is one of the critical enablers for governance, and so \'use good judgment' is still a great place to start -- IF you can hire people with good judgment, and continually reinforce them in using it."

see <<Nordstrom2015>>
****


ifdef::collaborator-draft[]

****
*Collaborative*

 Status: This section is in active development as of Jun 27 2016. Expect volatility.

include::../../../collab-links.adoc[]

****

endif::collaborator-draft[]


Board-level concern

Draw pic & restate for compliance and security

Principles
Policies
Processes

Don't overcomplicate

Lifecycle/sunset!

Example?Variety of policies:

* Information security
* Human resources
* Fraud risk
* Compliance

In a non-IT example, a compliance policy might identify the Foreign Corrupt Practices act and make it clear that bribery of foreign officials is unacceptable. Similarly, an HR policy might spell out acceptable and unacceptable side jobs (e.g., someone in the banking industry might be forbidden from also being a mortgage broker on their own account).

Policies
Master vs issue
Standards
Baselines
Guidelines
Procedures (check CISSP as source)

===== Assurance
[quote, Max Ehrmann, "Desiderata"]
Exercise caution in your business affairs;
for the world is full of trickery.

[quote, Latin for "Who watches the watchers?"]
Quis custodiet ipsos custodes?

intro

All audit is assurance, but not all assurance is audit. (Blurry boundary in practice, as an assurance engagement may be undertaken by auditors, and might be casually called an "audit" by the parties involved)

We can understand audit through understanding the general principles of assurance first.


[quote, Cobit 5 for Assurance]
Assurance means that, pursuant to an accountability relationship between two or more parties, an IT audit and assurance professional may be engaged to issue a written communication expressing a conclusion about the subject matters to the
accountable party.

====== Three party foundation

re-draw p15 cobit5 assurance


====== Examples (non-audit)
[quote, James DeLuccia, "Successfully Establishing and Representing DevOps in an Audit"]
Businesses must find a level of trust between each other  . . .  3rd party reports provide that confidence. Those issuing the reports stake their name & liability with each issuance.

Assurance and industry standards
manufacturing tolerance examples

Data center evaluations of cloud providers are a form of *assurance*.
SAS 70

IaaS assurance
SaaS assurance

Data safe harbor -to be discussed in next section

"Dynamic certification of Cloud services: Trust, but verify!" Lins et al, computing edge

===== Audit
[quote, Scott Ambler, Disciplined Agile Delivery]
Agile or not, a team ultimately has to meet legal and essential organizational needs, and audits help to ensure this.

Types of audit

* External
* Internal


Scope and bounds

* Finance
* IT

Recipient is key

controls vs enablers

====== External audit

"The Committee therefore recommends that all listed companies should establish an audit committee."  <<Cadbury1992>>, 4.35

An external auditor is chartered by a regulatory authority to visit an
enterprise or entity and to review and independently report the results of that review. <<Moeller2013>> p 319

Phoenix project example

====== Internal audit
[quote, Institute of Internal Auditors]
Internal auditing is an independent appraisal function established within an organization to examine and evaluate its activities as a service to the organization.

Usually reports to audit committee

"The function of the internal auditors is complementary to, but different from, that of the outside auditors." <<Cadbury1992>>, 4.39

the typical internal audit process requires scheduling a review, perform
ing a risk assessment and necessary audit procedures, and then reporting the results
of an audit to management and the audit committee.<<Moeller2013>> p 324

Institute of Internal Auditors

Auditing of areas other than security e.g. performance reporting

====== Audit practices
derived from <<ISACA2013a>>

Lifecycle

Scoping
* ID users of report (e.g. board audit committee)
* ID accountable/responsible parties
* ID Objectives
* ID controls/enablers

Performance

Fundamental: expected vs actual

* Enquire/confirm
Documentation, interviews, transactional validation

* Inspect
Process flows - trace tx thru system
Physical inspection/walkthroughs

* Observe

Attempt what is prevented

Embedded tooling/modules
Inspect the security protocols around them

 DevOps Audit Defense Toolkit discussion
 Evidence p 17
