

=== Chapter 10: Governance, Risk, Security, and Compliance

ifdef::collaborator-draft[]

****
*Collaborative*

 Status: This section is in active development as of Jun 24 2016. Expect volatility.

include::../../../collab-links.adoc[]

****

endif::collaborator-draft[]

==== Introduction to Chapter 10
[quote, Latin for "Who watches the watchers?"]
Quis custodiet ipsos custodes?

Operating at scale requires a different mindset. When you were starting out, the horizon seemed bounded only by your imagination, will, and talent.

At enterprise scale, it's a different world. You find yourself constrained by indifferent forces and  hostile adversaries, some of them competing fairly, and others seeking to attack by any means.

Whether or not you are a for-profit, publicly traded company, you are now large enough that external audits are required; you also likely have directors of some nature. Like it or not, the concept of "controls" has entered your awareness.

Security threats increase proportionally to the company's size. The talent and persistence of these adversaries is remarkable. Other challenging players are, on paper, "on the same side," but auditors are never to be taken for granted. Why are they investigating IT systems? What are their motivations and responsibilities? Finally, what laws and regulations are relevant to IT? Data protection, retention, ?

IMPORTANT: As with other chapters in the later part of this book, we are going to introduce this topic "on its own terms." We will then add additional context and critique in subsequent sections.

More than any other chapter, the location of this chapter in Section 4 draws attention. Again, any topic in any chapter may be a matter of concern at any stage in an organization's evolution. But it is difficult to formalize security before other organizational maturity steps have occurred, in particular process management. (Following process is a big part of  being secure.)

You've been doing security since your company started, otherwise you would not have gotten this big. But now, you have a Chief Information Security Officer, formal risk management processes, auditors, and compliance specialists. That kind of formalization does not usually happen until an organization grows to a certain size.

We needed the content in Section 3 to get this far. We had to understand our structure, how we were organizing our strategic investments, and how we were engaging in operational activities. In particular it is difficult to see how any organization can govern itself without some ability to define and execute processes, as processes often support governance controls and security protocols.

This chapter covers "Governance, Risk, Security, and Compliance" because there are clear relationships between these concerns. They have important dimensions of independence as well. It is interesting that the popular Guide to the CISSP starts its discussion of security with a chapter titled "Information Security Governance and Risk Management." Governance leads to a concern for risk, and security specializes in certain important classes of risk. Security requires grounding in governance and risk management.

Compliance is also related but again distinct, as the concern for adherence to laws and regulations, and secondarily internal policy.


===== Chapter 10 outline

 (write last)

===== Chapter 10 learning objectives

* Define governance vs. management
* Define risk management
* Discuss basic security concerns and practices
* Identify common regulatory compliance issues
** Data privacy (pointer to next chapter?)

 more
