
==== Security
[quote, Shon Harris, Guide to the CISSP]
In reality, organizations have many other things to do than practice security.

Security is a significant and well-known domain in and of itself. Ultimtely, however, *security is an _application_ of the governance principles discussed in the previous sections*. Deriving ultimately from the stakeholder's desire to sustain and protect the enterprise, security relies on accurate risk assessment, a clear enabling strategy (i.e. controls), and effective assurance practices (e.g. security audits). In fact, much of the previous material on controls was derived from the CISSP guide, because the concepts are generally applicable to risk management, not only security risks.

You have been practicing security

attack vs defense

CIA

===== Information classification
Simple 4-tier
Foreshadow compliance and EIM sections

===== Security engineering
2-axis view

====== Security architecture

Authentication & authorization
Endless topic: encryption, network architectures, ... much published. Get a CISSP.

====== Sourcing and security
NIST CVE & other sources
Zero day - segue to SecOps

===== Security operations
====== Functional
SOC overview

====== Process
Detection
Response
Forensics

Relationship to other IT processes

===== Security and GRC in general

Relationship to GRC

What *is* that auditor doing anyways? Are they security? Or governance?

Frameworks from a security perspective

ISO 27002
CISSP
(good overview in Moeller)
