
==== Risk
[quote, Committee of Sponsoring Organizations of the Treadway Commission, Internal Control - Integrated Framework]
Risk is defined as the possibility that an event will occur and adversely affect the achievement of objectives.

According to Treadway, control & risk are distinct but overlap

Define vulnerability, threat agent, threat, risk, control, exposure

hubbard failure of risk management - review

"risk" does not include upside.

relationship to security - security requires a risk assessment, so we know what to secure

* Internal environment
* Objectives
* Event Identification
* Risk Assessment
* Risk Response
* Control Activities
* Information & Communication
* Monitoring

Management

* Analysis
* avoidance
* acceptance
* transference

Use COSO outline

===== Assurance
[quote, Max Ehrmann, "Desiderata"]
Exercise caution in your business affairs;
for the world is full of trickery.

[quote, James DeLuccia, "Successfully Establishing and Representing DevOps in an Audit"]
Businesses must find a level of trust between each other  . . .  3rd party reports provide that confidence. Those issuing the reports stake their name & liability with each issuance.

3-party


All audit is assurance, but not all assurance is audit.



external

Data center evaluations of cloud providers are a form of *assurance*.

===== Benchmarking

===== Availability
foreshadow Simian Army

===== Continuity and recovery

A large class of risk that often results in projects or ongoing organizations

The nightmare of a cold standby failure in a legacy heterogeneous environment

Infrastructure as code can be a significant mitigator - investments can justify themselves



===== Security as a risk
(segue)
