
==== Digital Governance
[quote, Gorans/Ambler, Disciplined Agile Delivery]
transforming to an agile delivery approach is difficult. Companies or government agencies that have been in existence for decades have built up layers of deep and wide waste, many of them around governance. +
 +
Business or IT governance constructs and processes that do not support new technology-centric go-to-market models and products must be either replaced or substantially evolved; otherwise, they increase risk on the agile projects.

===== Historic IT governance: controlling the "order taker"

CIO-centric "order taking" organizational form is assumed through ISO 38500, Selig, Moeller

"The business" defines the audit plan

Now, the digital product org needs to define its own plan - proactively define the control objectives - <<Moeller2013>>

Yearly batch cycle, may not change anytime soon

===== Agile meets IT governance

"The wall" is embedded in ISO 38500... product-centric management is not supported

Are governance frameworks suited to define execution models?

organizational scar tissue

Project governance is transitioning to product governance

If policies become requirements, how can we remove waste processing between the policy and its implementation?

====== Allocation of capital in large batches

Pros and cons - sometimes, one needs to accept the fog of R&D
This never changes
The iconic entrepreneur asking for one more round

entrepreneurs tell a story https://silvialisam.com/chris-sacca-s-639f0f5f3b9c#.j6sljdp0x

VC view

====== Governance and product centricity
Whether enterprise IT governance processes have grown unin
tentionally through evolving process improvements or grown intentionally through a
deliberate project, the questions a senior manager should ask include: "How good are my IT governance processes at effectively delivering strategic business value year after year?" and "Are my processes repeatable, predictable, and scalable, and are they truly meeting the needs of my business (outside of IT) and my customers?"
 an example of what is wrong - this fixation with repeatability
 (MoellerXXXX)

The importance of a portfolio view

How do the VCs do it? Can this scale down into the enterprise?
Additional concerns within the boundary of a firm: higher leverage points because of sharing, reducing transaction costs
Reality on tech product: successful digital firms strongly govern tech portfolio, do not allow experimentation that could expand base tech footprint. See chapter 12.

===== A new class of organizational risks

bring back d/e/m e/e/r matrix

we can come back to this in digital - new classes/approaches to effectiveness risk

From an IT governance perspective, what is the role of IT risk management in the new digital world? It's not that risk management goes away. But there are significant new classes of risk that need to be better understood and managed:

 * Unmanaged demand leading to multi-tasking, destructive of value & results
 * High queue wait states
 * Slow feedback due to large batch sizes, reducing effectiveness
 * Failure to incorporate cost of delay in resource allocation and work prioritization decisions
 * Cultural dynamics destructive of high team performance

We now have better math & understanding

as Agile engages with traditional frameworks, this is the major transformation

more on the effectiveness level, less on the efficiency

but these effectiveness concerns consitute risk

(not to mention more technical risks)


====== SIAM/Cloud risks

Cloud (also mentioned in risk section)

Access
Compliance
Data location
Multi-tenancy
Recovery
investigation
Viability (assurance)


===== Governance as demand

Governance programs, projects, tasks

It's all just work

See governance as a class of NFRs for operational services
Embed, automate, iterate

Challenge separate programs, processes, systems - how can objectives be met as a part of existing?

Speculation: risks & controls documented as BDD, risk/control repository may still be needed... but how are these not just ongoing requirements/stories, with particular privileges for editing?

Unacceptability of out of band governance demands

working to rule (backref)

Technical policies - foreshadow Chapter 12

===== Automating digital governance
Standalone systems

* Risk repository - needs to be integrated with subject inventories (portfolio & processes)
* Issue tracking & workflow
* Document mgmt systems


Embedding

Risk, control, compliance (and subsets like security and continuity) are always with respect TO something

What are the things?

* Products/services
** ongoing delivery
** changes & transformations (Releases)
** revenues

* Customers
* People & positions
* Assets
* Vendors
* Information

Some level of automation is essential ... ERP for the digital age

automated code reviews - previously a good idea, now required
discussion in DevOps Audit Defense Toolkit

Separation of duties was always an ineffective control for the risk of backdoors ... !!

Package management, CVE, market data

This leads us beautifully to Chapter 11.

===== Antifragility, continuous delivery, and security
DevSecOps, RuggedDevOps, etc

Simian Army
