
==== Policy, assurance and audit


ifdef::collaborator-draft[]

****
*Collaborative*

 Status: This intro section is in active development as of Jun 27 2016. Expect volatility.

include::../../../collab-links.adoc[]

****

endif::collaborator-draft[]

===== Policy management
Board-level concern

Draw pic & restate for compliance and security

Principles
Policies
Processes

Don't overcomplicate

Lifecycle/sunset!

Example?


Variety of policies:

* Information security
* Human resources
* Fraud risk
* Compliance

In a non-IT example, a compliance policy might identify the Foreign Corrupt Practices act and make it clear that bribery of foreign officials is unacceptable. Similarly, an HR policy might spell out acceptable and unacceptable side jobs (e.g., someone in the banking industry might be forbidden from also being a mortgage broker on their own account).

Policies
Master vs issue
Standards
Baselines
Guidelines
Procedures (check CISSP as source)


====== Governance & process
 mentioned in previous chapter
 committee structures - cross-org - mentioned in Ch 7

====== Decision rights as governance
We have covered previously. Many governance sources include discussion of organizational structure; this however is more on the management side of the spectrum

====== Governance demand
Watt's governor imposed a certain burden on the engine (what % of energy did it consume?)

importance of having the demand/execution framework in place to manage governance demand

====== Governance and sourcing
We have already covered contracting in terms of software and Cloud. But in terms of the emergence model, it is typical that companies enter into contracts before having a fully mature sourcing and contract management capability with input from the governance, risk, and compliance perspective.

===== Assurance
[quote, Max Ehrmann, "Desiderata"]
Exercise caution in your business affairs;
for the world is full of trickery.

[quote, Latin for "Who watches the watchers?"]
Quis custodiet ipsos custodes?

intro

 All audit is assurance, but not all assurance is audit. (Blurry boundary in practice, as an assurance engagement may be undertaken by auditors, and might be casually called an "audit" by the parties involved)

We can understand audit through understanding the general principles of assurance first.


[quote, Cobit 5 for Assurance]
Assurance means that, pursuant to an accountability relationship between two or more parties, an IT audit and assurance professional may be engaged to issue a written communication expressing a conclusion about the subject matters to the
accountable party.

====== Three party foundation

re-draw p15 cobit5 assurance


====== Examples (non-audit)
[quote, James DeLuccia, "Successfully Establishing and Representing DevOps in an Audit"]
Businesses must find a level of trust between each other  . . .  3rd party reports provide that confidence. Those issuing the reports stake their name & liability with each issuance.

Assurance and industry standards
manufacturing tolerance examples

Data center evaluations of cloud providers are a form of *assurance*.
SAS 70

IaaS assurance
SaaS assurance

Data safe harbor -to be discussed in next section

"Dynamic certification of Cloud services: Trust, but verify!" Lins et al, computing edge

===== Audit
[quote, Scott Ambler, Disciplined Agile Delivery]
Agile or not, a team ultimately has to meet legal and essential organizational needs, and audits help to ensure this.

Types of audit

* External
* Internal


Scope and bounds

* Finance
* IT

Recipient is key

====== External audit

"The Committee therefore recommends that all listed companies should establish an audit committee."  <<Cadbury1992>>, 4.35

An external auditor is chartered by a regulatory authority to visit an
enterprise or entity and to review and independently report the results of that review. <<Moeller2013>> p 319

Phoenix project example

====== Internal audit
[quote, Institute of Internal Auditors]
Internal auditing is an independent appraisal function established within an organization to examine and evaluate its activities as a service to the organization.

Usually reports to audit committee

"The function of the internal auditors is complementary to, but different from, that of the outside auditors." <<Cadbury1992>>, 4.39

the typical internal audit process requires scheduling a review, perform
ing a risk assessment and necessary audit procedures, and then reporting the results
of an audit to management and the audit committee.<<Moeller2013>> p 324

Institute of Internal Auditors

Auditing of areas other than security e.g. performance reporting

====== Assurance practices
derived from <<ISACA2013a>>

Lifecycle

Scoping
* ID users of report (e.g. board audit committee)
* ID accountable/responsible parties
* ID Objectives
* ID controls/enablers

Performance

Fundamental: expected vs actual

* Enquire/confirm
Documentation, interviews, transactional validation

* Inspect
Process flows - trace tx thru system
Physical inspection/walkthroughs

* Observe

Attempt what is prevented

Embedded tooling/modules
Inspect the security protocols around them

 DevOps Audit Defense Toolkit discussion
 Evidence p 17
