
==== Digital Governance
[quote, Gorans/Ambler, Disciplined Agile Delivery]
...transforming to an agile delivery approach is difficult. Companies or government agencies that have been in existence for decades have built up layers of deep and wide waste, many of them around governance. +
 +
Business or IT governance constructs and processes that do not support new technology-centric go-to-market models and products must be either replaced or substantially evolved; otherwise, they increase risk on the agile projects.

====== Failings of IT governance
"The wall" is embedded in ISO 38500...

CIO-centric "order taking" organizational form is assumed through ISO 38500, Selig, Moeller

As with other chapters, we have presented the material defining this chapter's topic "on its own terms." Certainly, there is little chance that the core principles of governance will cease to have importance, even in the new digital economy.

However, as Ambler and Gorans note above, the legacy of IT governance is wide, deep, and often wasteful. Approaches based on mis-applied xref:taylorism[Taylorism] and misguided, CMM-inspired xref:problem-statisical-process[statistical process control] have resulted in the creation of ineffective, large-scale xref:what-is-IT[IT bureaucracies] whose sole mission seems to be the creation and exchange of non-value-add xref:secondary-artifacts[secondary artifacts], while lacking any clear concept of an xref:lack-execution-model[execution model].

The answer is not, however, to attempt something like #NoGovernance. We'll leave that exercise for the anarchists, who will continue to fail as anarchists always have.

Instead, this book argues the most effective answer lies in a re-examination of the true concerns of governance:

* sustaining innovation and effective value delivery
* maintaining efficiency
* optimizing risk

These fundamental principles ("top-line," "bottom-line," "risk") define value for organizations around the world, whether for-profit, non-profit, or governmental.

We'll re-examine through these objectives and come up with different answers:

* governance & innovation
* governance & efficiency
* governance & risk


====== Governance and product centricity

 product-centric management is not supported

Project governance is transitioning to product governance

Whether enterprise IT governance processes have grown unintentionally through evolving process improvements or grown intentionally through a
deliberate project, the questions a senior manager should ask include: "How good are my IT governance processes at effectively delivering strategic business value year after year?" and "Are my processes repeatable, predictable, and scalable, and are they truly meeting the needs of my business (outside of IT) and my customers?"

 an example of what is wrong - this fixation with repeatability
 (MoellerXXXX)

The importance of a portfolio view

====== The fundamental lesson of product-centric digital transformation

Finally, consider the "programmability" criteria above. A highly "programmable" position is one where the responsibilities can be specified in terms of their activities. *And what is the fundamental dynamic of digital transformation?* It is no accident that such positions are called "programmable." In fact, they *are* being "programmed away" or "eaten by software"- leaving only higher-skill positions that are best managed by objective, and which are more sensitive to cultural dynamics.

Preoccupation with "efficiency" fades as a result of the decreasingly "programmable" component of work. The term "efficiency" signals a process that has been well defined (is "programmable") to the point where it is repeatable and scalable. Such processes are ripe for automation, commoditization, and outsourcing, and this is in fact happening. And when such repetitive concerns become a matter of sourcing rather than execution, the emphasis shifts to risk management and governance of the supplier.

risk of learning wrong lessons w/r/t complex systems - more "rigor" is not necessarily the answer - impossibility of testing all outcomes (cite relevant SEng) -- THE FUNDAMENTAL ISSUE

principles: antifragility, defense in depth, fast feedback, automation (2-edged sword), analytics & pattern recognition - pointer back to chapter 6


===== Governance and digital efficiency

get stuff into a common pipeline
stop the transaction costs
secondary deliverables
all this theater that is doing nothing to reduce risk


====== Execution models

Are governance frameworks suited to define execution models?

organizational scar tissue

====== Governance as demand
Watt's governor imposed a certain burden on the engine (what % of energy did it consume?)

importance of having the demand/execution framework in place to manage governance demand
Governance programs, projects, tasks

It's all just work

distributed vs centralized model

See governance as a class of NFRs for operational services
Embed, automate, iterate

Challenge separate programs, processes, systems - how can objectives be met as a part of existing?

Speculation: risks & controls documented as BDD, risk/control repository may still be needed... but how are these not just ongoing requirements/stories, with particular privileges for editing?

Unacceptability of out of band governance demands

working to rule (backref)
"Working to rule" - when they proliferate - demand implications

controls theater - cargo cult controls

====== Leveraging the digital pipeline

If policies become requirements, how can we remove waste processing between the policy and its implementation?


"The business" defines the audit plan

Now, the digital product org needs to define its own plan - proactively define the control objectives - <<Moeller2013>>

Yearly batch cycle, may not change anytime soon

If "corporate governance" is "The system by which organizations are directed and controlled," then it is reasonable that "corporate governance of IT" is "The system by which the *current and future use of IT is directed and controlled*." This is how ISO 38500, the IT Governance standard, defines it <<ISO2008>>.

====== Governing the venture portfolio

as opposed to PMO?

Has created different attitudes & expectations towards governance in West Coast "unicorn" culture. Compare/contrast.

How do the VCs do it? Can this scale down into the enterprise?
Additional concerns within the boundary of a firm: higher leverage points because of sharing, reducing transaction costs
====== Allocation of capital in large batches

Pros and cons - sometimes, one needs to accept the fog of R&D
This never changes
The iconic entrepreneur asking for one more round

entrepreneurs tell a story https://silvialisam.com/chris-sacca-s-639f0f5f3b9c#.j6sljdp0x

VC view

====== Next gen risk mgmt

From an IT governance perspective, what is the role of IT risk management in the new digital world? It's not that risk management goes away. But there are significant new classes of risk that need to be better understood and managed:

bring back d/e/m e/e/r matrix

the risk of failing to deliver "Poorly governed and managed information and technology will destroy value or fail to deliver benefits...[such as] Unrealised or reduced business value" <<ISACA2013>>, p18

but how to "govern" this?? - the most effective way is empowerment... !!

we can come back to this in digital - new classes/approaches to effectiveness risk

* Unmanaged demand leading to multi-tasking, destructive of value & results
* High queue wait states
* Slow feedback due to large batch sizes, reducing effectiveness
* Failure to incorporate cost of delay in resource allocation and work prioritization decisions
* Cultural dynamics destructive of high team performance

We now have better math & understanding

as Agile engages with traditional frameworks, this is the major transformation: more on the effectiveness level, less on the efficiency...these effectiveness concerns constitute risk

(not to mention more technical risks)

====== Cost of delay as risk

Policy is not just about risk. Policy is also about effectiveness, e.g. understanding cost of delay, not overburdening ... we understand risk as risk of loss, not ineffectiveness... but we still control for our policies that are intended to promote effectiveness...

In today's digital governance there is a greater concern for outcome and effectiveness, especially in terms of time to market (minimizing xref:cost-of-delay[Cost of Delay]). Previously, concerns for efficiency might lead a company to overburden its staff, resulting in queuing gridlock, too much work in process, destructive multitasking, and ultimately failure to deliver timely results (or deliver at all).

Such failure to deliver was tolerated because it seemed to be a common problem across most IT departments, and because digital transformation had not taken hold yet. IT systems were often back office and delays in delivering them (or significant issues in their operation) were not *quite* as damaging.

Now, effectiveness of delivery is essential. The interesting, and to some degree unexpected result, is that both efficiency and risk seem to be benefiting as well. Cross-functional, focused teams are both more effective and more efficient, and able to manage risk better as well. Systems are being built with both increased rapidity as well as improved stability, and the automation enabling this provides robust audit support.


====== Architecture and governance

Technical policies - foreshadow Chapter 12

Affect E, E, R (draw here or later)

Reality on tech product: successful digital firms strongly govern tech portfolio, do not allow experimentation that could expand base tech footprint. See chapter 12.

===== Cloud, SIAM, and governance

Deeper look at duPreez2015 - actually, due diligence did not save them -- so secondary controls such as asset (both HAM and SAM), config... IaC has great potential... open source becomes a key risk mitigator...

Cloud (also mentioned in risk section)

Access
Compliance
Data location
Multi-tenancy
Recovery
investigation
Viability (assurance)
Escrow

We have already covered contracting in terms of software and Cloud. But in terms of the emergence model, it is typical that companies enter into contracts before having a fully mature sourcing and contract management capability with input from the governance, risk, and compliance perspective.

 "Dynamic certification of Cloud services: Trust, but verify!" Lins et al, computing edge (advanced)

===== Automating digital governance

****

*The DevOps Audit Toolkit*

The DevOps Audit Toolkit <<DeLuccia2015>> provides an important set of examples demonstrating how modern DevOps toolchain automation can fulfill audit objectives as well or better than "traditional" approaches.

****

Standalone systems

* Risk repository - needs to be integrated with subject inventories (portfolio & processes)

http://www.aicpa.org/interestareas/frc/assuranceadvisoryservices/downloadabledocuments/asec_whitepapers/risk_technology.pdf

* Issue tracking & workflow
* Document mgmt systems


Embedding

Risk, control, compliance (and subsets like security and continuity) are always with respect TO something

What are the things?

* Products/services
** ongoing delivery
** changes & transformations (Releases)
** revenues

* Customers
* People & positions
* Assets
* Vendors
* Information

Some level of automation is essential ... ERP for the digital age

automated code reviews - previously a good idea, now required
discussion in DevOps Audit Defense Toolkit

Separation of duties was always an ineffective control for the risk of backdoors ... !!

Package management, CVE, market data

This leads us beautifully to Chapter 11.

====== Antifragility, continuous delivery, and security
DevSecOps, RuggedDevOps, etc

Simian Army
