==== Topics in IT infrastructure

 ===== Operations basics
 Just enough Operations for the startup
 Prep chap 6


 ===== Web-scale IT

This section as of fall 2015 is yet to be written. Will summarize key insights from the site reliability community, including Allspaw and Limoncelli.

anchor:CAP-theorem[]

 ===== CAP theorem
 to be written

 ===== Technology lifecycle management

 [to be written]


 ===== additional material

 http://12factor.net/build-release-run

 Releases are an append-only ledger and a release cannot be mutated once it is created. Any change must create a new release.

 In the old world, environments were accepted to be different except where they needed to be consistent. In the new world, environments are assumed to be the same except where they need to be different.


 what makes a good infrastructure engineer

 http://jpmorgenthal.com/2016/08/24/a-reality-check-on-everyones-moving-everything-to-the-cloud/ excellent

 choreography & orchestration - John Willis convo

 The concept of a version control system (variously known as source control, revision control, software configuration management, and other terms) is our first major software system for the “business of IT.” (The virtualized system previously discussed is what is *under management*; the source control system is part of the *management architecture*.)
