anchor:policy-config[]

==== Policy-based approaches

Before we turned to source control, we looked at a simple script that changed the configuration of a computer. It did so in an _imperative_ fashion.

===== Imperative and Declarative

Imperative and declarative are two important terms from computer science. In an imperative approach, we tell the computer specifically how we want to accomplish a task. Many traditional programming languages take an imperative approach. Whereas with a declarative approach, we tell the computer the task we want to accomplish and let the computer figure out the best way to do it. Structured Query Language (SQL) statements are a good example of a declarative approach. We can provide a database system with a set of SQL statements, and the database will generate an execution plan to provide us with the data we are seeking. Functional languages such as Lisp and Erlang are considered declarative.

A script such as iac.sh is executed line by line, i.e., it is imperative. But in policy-based approaches, the object is to define the desired end state of the resource, not the steps needed to get there.

Chef, Puppet, Salt Stack, and Ansible are all declarative to some degree.

This is a complex topic and there are advantages and disadvantages to each approach. (See http://markburgess.org/blog_order.html["When and Where Order Matters"] by Mark Burgess for an advanced discussion.) But policy-based approaches seem to have the upper hand for now.


_describe modern infra managers, policy management, auto-scaling as an example, provide an example Chef script.._
