==== Topics in process management
ifdef::collaborator-draft[]

****
*Collaborative*

_20160609 Status: Like most topics sections, this one will remain rough until 2nd draft. Suggestions appreciated._

include::../../../collab-links.adoc[]

****

endif::collaborator-draft[]

===== The shared services problem



 Lifecycle: collaboration, internal commoditization, external commoditization
 Effectiveness, efficiency, governance

 Examples of shared services for digital teams - layered nature

 Service catalog: act, offering, system

 Infrastructure vs business

 Benchmarkable

 Deeper discussion of virtual server provisioning as example (backref to ch2, forward to ch10)

example of service-ized process dysfunction

Adapting a services model to improve flow

(Notice that the services a functional area provides can be viewed as a form of product in and of themselves.)

Degree of automation
perils of "take a number" service-ization

* SLAs and the service catalog
** Service-izing functions: pros and cons

Scenario: repetitive yet error prone work
team to team interactions that become "servicized"

 Implication in various IT governance texts that the shared services team is accountable for optimal use of the shared resource. A very dangerous guideline when multiplied by numerous  COEs/SSs.

 ===== The BPM community


 ===== Tooling

BPMN, BPEL, and more

simulations:  systems dynamics & DES

ITSM tooling: process PLUS what is being acted on (portfolio)

 ===== The ERP problem
Where IT management diverges from Agile

===== Deeper theory
 Cynefin
"best practice"
Cost of delay of aggregate process - research idea

formalisms
 state charts, Petri nets

  Process as a Mintzberg liaison mechanism

  http://blogs.forrester.com/jean_pierre_garbani/09-06-26-my_issue_itil

  CPRET is a mnemonic for the basic definition of process in process engineering: it stands for Constraints, Product, Resources, input Elements and Transformation which are the basic components of a process. In process engineering, a process is a suite of transformations of elements into a given output (product) given a set of constraints and resources. From this definition, we can see that technology has a strong influence on the process: the transformation part is a clear function of the technology available as input and resources in IT are strongly influenced by the technology used. As we mostly deal with information and data in IT management processes, the type of data available is either helping or impeding the transformation part.

  Schwaber process author - chem e guy

  Kennelay - PID model

 formal process control

 ****
 Sidebar: Lessons from manufacturing, operations research, etc

 Controversy of application to IT

 Will this have been foreshadowed?
 ****

 review & incorporate more grounding from http://www.computing.dcu.ie/~mcrane/CA441/BPMLectureNotes.pdf[BPM Lecture Notes]
