==== Advanced topics

===== Essay: Kanban, process, and respect for people

* Processes cross functions.
* Processes (e.g. Quote to Cash, Idea to Production) are what actually deliver value.
* We need both process and function; we can’t organize solely around either.
* Therefore, get used to matrix management.

The above statements are the management dogma I grew up with. Considered to be innovative at the time, originated by the likes of Michael Hammer and (more rigorously) Geary Rummler. (See Paul Harmon's http://www.bptrends.com/publicationfiles/advisor20081209.pdf[excellent obituary of Geary Rummler].)

But consider a day in the life in the modern corporation: dozens or hundreds of cross functional processes that have become a daily barrage of work on the people housed in the functional areas. Driven by back end automation, front ended by automated (or even manual) email notifications, these required activities include:

* service requests,
* compliance certifications,
* asset validations,
* provisioning requests,
* capacity assessments,
* change approvals,
* training obligations,
* performance assessments,
* audit responses,
* expense reporting,
* travel approvals,

and more - infinitely more. This is the modern, “process"-centric enterprise.

True, any one of these processes is (often) a relatively small burden to perform. Taken together, however, it’s the nightmare of http://www.waywordradio.org/adminisdribble_1/[Adminisdribble]: The daily death by a thousand cuts of required, cross-functional process.

Continual context switching. End to end flow in concept across functions, but little experienced by the multitasking individual. Invisible, unmanaged demand. A thousand channels for flow, but no throughput, because of gridlock.

What drives this? The combination of permanent downsizing, continually increasing governance & compliance burdens, and the assumption that the enterprise can always tolerate another process. Overall organizational capacity is rarely considered, especially for “supporting" processes. And there is no appreciation for the emergent behavior when these myriads of processes interact in unexpected ways.

This is why kanban is so radical. Within a limited scope, it is starting to challenge the IT management dogma at least. User stories, incidents, defects, service requests, changes… they are all “just work.” Just another sticky note on the board. Someone has to perform the work; someone has to allocate time and attention to it. A simple but utterly profound change in orientation. Kanban is the labor movement of the 21st century.

It seems to me that true “respect for people” (as advocated by Lean) of course must start with the recognition that work takes people’s time. I think the modern, process centric enterprise has lost sight of that reality. Is Kanban the answer?

_originally posted at http://www.lean4it.com/2014/08/kanban-vs-process.html_

ifdef::collaborator-draft[]

****
*Collaborative*

 Status: Like most topics sections, work in progress that will probably not be completed until 2nd or later drafts.

include::../../../collab-links.adoc[]

****
_Second draft ideas_


Get Anderson & some Scrum person to write sidebars.

 ===== Intersection of product and work management: story branches

 Because the intent leads to the artifact, and the artifact leads to the commit, it makes sense to associate the requirement with a branch in the version control system. This is not required, but makes it easier to trace the requirement to the actual work by which it was fulfilled. This will be discussed further in Part II and its associated labs. This is a continuously evolving problem area, with practices changing rapidly.

 anchor:multi-tasking[]

 ===== Multi-tasking

 Context switching and multi-tasking
 [Human factors discussion]


Need to allocate between chapters 5, 8, 9 - or touch on & elaborate later?


 Relationship between features and tasks

 Decision rules
 Reinertsen Boeing case

 Rule engines

 

Stories are meant to be independent and valuable. Tasks aren’t. By earning velocity at the level of tasks, it is possible to be 70% dev-complete for a release without a single story being dev-complete. <<Narayan2015>>


 A look ahead to project and process

 ===== RACI
 RACI stands for

 * Responsible
 * Accountable
 * Consulted
 * Informed

 A RACI analysis is often used when accountability must be defined for complex activities. It is used in process management, and also is seen in  project management and general organizational structure.

 Since it is a precursor of both process and project management, it's therefore appropriate to cover it as part of generic work management.

  bring in reinertsen discussion (MDF or DPHT):

  focus on specific decisions rather than abstract concepts like empowerment and strong vs. weak teams. It is much more useful for teams to know which product features they can change without outside approval than it is to find out they are "empowered."

Projects: fixed time/duration/scope, not repeatable.

Processes: repeatable...

 deferrable commitments

 [Dan Pink, Drive: Task, time, technique, and team]

 High priority: incorporate Common Ground paper http://jeffreymbradshaw.net/publications/Common_Ground_Single.pdf

endif::collaborator-draft[]
