
anchor:2_05.00-work-management[]

=== Chapter 5: Work Management

==== Introduction

[quote, Henry Mintzberg, Structure in Fives]
As two more assistants were added, however, coordination problems did arise. One day, Miss Bisque tripped over a pail of glaze and broke five pots; another day, Ms. Raku opened the kiln to find that the hanging planters had all been glazed fuchsia by mistake. At this point, she realized that seven people in a small pottery studio could not coordinate all their work through the simple mechanism of informal communication.

You're now a team. You need to get work done. When your startup hired its first employees, and you went from two people to three or four, you had to think about this. You are now getting feedback from both your users and your product team calling for prioritization, the allocation of resources, and the tracking of effort and completion. These are the critical day to day questions for any business larger than a couple of co-founders:

* What do we need to do?
* In what order?
* Who is doing it?
* Do they need help?
* Do they need direction?
* When will they be done?
* What do we mean by done?

People have different responsibilities and specialties, yet there is a common vision for delivering an IT-based product of some value. How do you keep track of the work? Mostly, you are in the same location, but people sometimes are off-site or keeping different hours. Beyond your product strategy, you have support calls increasingly coming in that result in fixes and new features, and it's all getting complicated.

You already have a product owner. You now institute xref:Scrum[Scrum] practices of a managed backlog, daily standups and sprints. You may also use Kanban-style task boards or card walls (to be described in this chapter), which are essential for things like support-driven work. The relationship of these to your Scrum practices is a matter of some ongoing debate. You don't think you need full-blown project management -- yet. You also may become aware of the idea of "ticketing," if you have people with previous service desk experience. How this relates to your Scrum/Kanban approach is a question.

Furthermore, while we covered Agile principles and practices in some detail in chapters 3 and 4, we did not discuss *why* they work. In this chapter, we will cover the Lean theory of product management that provides a basis for Agile practices, in particular the work of Don Reinertsen.

The chapter title "Work Management" reflects earlier stages of organizational growth. At this point, neither formal project management, nor a fully realized process framework are needed, and the organization may not see a need to distinguish precisely between types of work processes. "It's all just work" at this stage.

===== Chapter 5 outline

* Introduction
* Task management
* Learning from manufacturing
** Kanban and its Lean origins
** The Theory of Constraints
** Queues and limiting work in process
** Scrum, Kanban, or both?
* The shared mental model of the work to be done
** Visualization
** Andon, and the Andon Cord
** Definition of done
** Time and space shifting
* The service desk and related tools
* Lean product development and Don Reinertsen
** Lean product development
** Cost of Delay
* Advanced topics
** Essay: Kanban, process, and respect for people
* Conclusion


===== Chapter 5 learning objectives

* Understand the basic concept of task management
* Describe how to correctly apply insights from manufacturing to digital product management
* Define Kanban and identify its key practices
* Compare and contrast Scrum and Kanban
* Understand concepts from Lean Product Management
