==== Conclusion
"Work management" may seem like an oddly general title, but it's important to distinguish the fundamental problem from more elaborate constructs such as process and project management. At the end of the day, "it's all just work."

Understanding work requires understanding tasks and their lifecycle, the characteristics of queues and work in progress, and the Cost of Delay.

===== Discussion questions

. When have you been on a team that needed to have a shared mental model? How did you achieve this?
. Where do you see queues in your daily life? Are they frequently in high-queue states? What could be done to improve them?
. How do you keep track of tasks? Compare approaches with your group.
. Do you choose Scrum, Kanban, both, or neither?

===== Research & practice

. Think of a queue you encounter on a regular basis. How can you understand its cost of delay?
. Research an automated, online Kanban tool (Trello, LeanKit, or similar). Compare it to a physical whiteboard, ideally as a team. Which do you prefer and why?
. Recall your product ideas from earlier discussions. How would you estimate its Cost of Delay? Can you estimate Cost of Delay by feature?
. (Advanced) Read some of Reinertsen's _The Principles of Product Development Flow_ and write up or present 2-3 key insights you gained.

===== Further reading
*Books*

* David Anderson, http://www.goodreads.com/book/show/8086552-kanban[_Kanban: Successful Evolutionary Change for Your Technology Business_]
* Mike Burrows, http://www.goodreads.com/book/show/23162381-kanban-from-the-inside[_Kanban from the Inside: Understand the Kanban Method, connect it to what you already know, introduce it with impact_]
* Eli Goldratt, Jeff Cox https://www.goodreads.com/book/show/113934.The_Goal[_The Goal: A Process of Ongoing Improvement_]
* Gene Kim et al, https://www.goodreads.com/book/show/17255186-the-phoenix-project[_The Phoenix Project: A Novel About IT, DevOps, and Helping Your Business Win_]
* Donald Reinertsen, http://www.goodreads.com/book/show/6278270-the-principles-of-product-development-flow[_Principles of Product Development Flow: Second Generation Lean Product Development_]

*Articles*

* Josh Arnold, http://blackswanfarming.com/workshop-quantifying-the-cost-of-delay/[Quantifying the Cost of Delay]

* Josh Arnold, http://blackswanfarming.com/cost-of-delay/[Cost of Delay definition]

* Alex Salazar, https://stormpath.com/blog/so-long-scrum-hello-kanban/[So Long Scrum, Hello Kanban]

*Videos*

* Don Reinertsen, http://www.infoq.com/presentations/Economic-Models[The Tactical and Strategic Art of Economic Models] Excellent discussion of Cost of Delay.
