
==== Introducing Kanban


.Author's note: what can we learn from manufacturing?
****
Between 2005 and 2012, I was a lead enterprise architect at Wells Fargo Bank, primarily concerned with IT delivery capabilities such as portfolio and service management. One day around 2007, I arrived at my office to find an envelope from my friend Gene Kim, then CTO of Tripwire. Gene and I had been corresponding for some years on high-performing IT, IT processes, and related topics. In the envelope was a copy of a book called _The Goal_, by Eli Goldratt. I was a little mystified, but after reading the book I began to understand its potential.

Eliyahu Moshe Goldratt was an Israeli physicist and management consultant, best known for his pioneering work in management theory, including  _The Goal_, which is a best-selling business novel frequently assigned in MBA programs. It and Goldratt's other novels have had a tremendous effect on industrial theory, and now, digital management. One of the best known stories in _The Goal_ centers around a Boy Scout march. Alex, the protagonist struggling to save his manufacturing plant, takes a troop of Scouts on a ten mile hike. The troop has hikers of various speeds, yet the goal is to arrive simultaneously. As Alex tries to keep the Scouts together, he discovers that the slowest, most overweight scout (Herbie) also has packed an unusually heavy backpack. The contents of Herbie's pack are redistributed, speeding up both Herbie and the troop.

This story summarizes the Goldratt approach: finding the "constraint" to production (his work as a whole is called the Theory of Constraints). In Goldratt's view, a system is only as productive as its constraint. At Alex's factory, it's found that the "constraint" to the overall productivity issues is the newest computer-controlled machine tool -- one that could (in theory) do the work of several older models but was now jeopardizing the entire plant's survival. This novelization parallels in important regards actual Lean case studies on the often-negative impact of such capital-intensive approaches to production.

There is a tremendous wealth of material available on Lean history and theory, and the IT student is urged to become familiar with it. Historically, there has been resistance in IT and digital circles to learning lessons derived from manufacturing, due to misperceptions that manufacturing is too “repetitive” compared to IT systems development.

Gene Kim however saw the potential of the Theory of Constraints in understanding certain aspects of information technology management, and used it as a template to write another remarkable and influential book, _The Phoenix Project_. Rather than a manufacturing plant, the Phoenix Project centers on the struggles of the IT team at a medium-sized automotive parts manufacturer and retailer. From a state of chaos, uncontrolled work in process and resource constraints, the team applies Lean, Agile, and DevOps techniques to great effect. In my view, _The Phoenix Project_ is one of the most important works in the history of IT and digital management, and is also an enjoyable novel. If you are considering a career in IT or digital, it is essential reading.
****

anchor:2.05.02-kanban[]

To understand Kanban let's discuss Lean briefly.

Lean is a term invented by American researchers into Japanese industrial processes and their success in the 20th century. Certainly, after the end of World War II, no-one expected the Japanese economy to recover the way it did. While of course Japanese hard work is a major factor, credit is also given to U.S. thinkers such as W.E. Deming, Peter Juran, and the theorists behind the Training Within Industry methodology. To understand Lean, you can start with _The Machine that Changed the World_ <<Womack1990>>, _The Toyota Way_ <<Liker2004>>, and _Toyota Kata_ <<Rother2010>>.

Kanban is a term originating from Lean and the Toyota Production System. Originally, it signified a “pull” technique in which materials would only be transferred to a given workstation on a definite signal that the workstation required the materials. This was in contrast to “push” approaches where work was allowed to accumulate on the shop floor, on the (now discredited) idea that it was more “efficient” to operate workstations at maximum capacity.

Factories operating on a "push" model found themselves with massive amounts of inventory (work in process) in their facilities. This tied up operating capital and resulted in long delays to shipment, because of the queueing issues. Japanese companies did not have the luxury of large amounts of operating capital, so they started experimenting with "single-piece flow." This led to a number of related innovations, such as the ability to re-configure manufacturing machinery much more quickly than U.S. factories were capable of. 

David J. Anderson was a product manager at Microsoft who was seeking a more effective approach to managing software development. In consultation with Don Reinertsen (introduced in the xref:queuing[previous section]) he applied the original concept of Kanban to his software development activities <<Anderson2010>>.

Scrum is based on a rhythm with its scheduled sprints, for example every two weeks. In contrast, Kanban is a continuous process with no specified rhythm (also known as _cadence_). Work is “pulled” from backlog into active attention as resources are freed from previous work. This is perhaps the most important aspect of Kanban - the idea that *work is not accepted until there is capacity to perform it.*

You may have a white board covered with sticky notes, but if they are stacked on top of each other with no concern for worker availability, you are not doing Kanban. You are accepting too much work in process and you are likely to encounter a "high-queue state" in which work becomes slower and slower to get done.

There are deeper philosophical and cultural qualities to Kanban beyond workflow and capacity. Anderson and his colleagues continue to evolve Kanban into a more ambitious framework. Mike Burrows <<Burrows2014>> identifies the following key principles

* Start with what you do now.
* Agree to pursue evolutionary change.
* Initially, respect current processes, roles, responsibilities, and job titles.
* Encourage acts of leadership at every level in your organization —from individual contributor to senior management.
* Visualize.
* Limit Work-in-Progress (WIP).
* Manage flow.
* Make policies explicit.
* Implement feedback loops.
* Improve collaboratively, evolve experimentally (using models and the scientific method).

 [Reinertsen 204-205 on kanban]

===== Scrum, Kanban, or both?

So, do you choose Scrum, Kanban, both, or neither?

We can see in comparing Scrum and Kanban that their areas of focus are somewhat different.

* Scrum has achieved widespread success and formalization, which is why Scrum training is widespread and generally consistent in content.
* Kanban is seen as more flexible but this comes at a cost of more management overhead. It requires more interpretation to translate to a given organization’s culture and practices.
* “Scrum is not well suited to highly interrupt-driven work.” <<Rubin2012>>. (But if your company is too small, it may be difficult to segregate out interrupt-driven work! We will discuss the issues around interrupt-driven work further in Chapter 6.)
* Finally, hybrids exist (Ladas' “Scrumban,” <<Ladas2009>>).
