==== Conclusion

Governance and its related topics are a broad and complex domain, one that represents a career path as you gain experience and seniority in your organization. It is critical to understand the motivations and objectives of governance-driven initiatives. While it can be tempting to dismiss governance-related activities as "bureaucracy," hopefully after this chapter you have a more complete understanding, and will be able to engage with governance in a constructive manner.

The following principles may be useful:

* Treat governance objectives, as much as possible, as simply a form of digital requirement to be handled through the delivery pipeline
* Consider the new classes of risk to digital effectiveness and innovation: overburden, multi-tasking, overloaded queues, and toxic culture
* Automate governance objectives throughout the pipeline. Avoid manual processing wherever possible.
* Understand that poorly conceived governance strategies and tactics can themselves constitute a risk to effective digital delivery.


===== Discussion questions

. Research further and discuss one of these http://www.zdnet.com/article/the-top-10-it-disasters-of-all-time-5000177729/[IT disasters].

. Propose how the disaster could have been avoided or mitigated using the goverance concepts presented in this chapter.

. Does the term "governance" bother you? Why or why not? What about the term "control"?

. Debate, as a team, the proposition that "There is no realistic way to distinguish between governance and management." One side of the team to argue for, the other to argue against. Present your best arguments to the rest of the class.

===== Research & practice

* Beyond the brief discussion in this chapter, research how venture capital firms govern their portfolios of startup investments. Compare and contrast to public company governance.

* Find a copy of the classic William Gibson short story, "Burning Chrome." Write an analysis of it using the concepts described in this chapter.

* Find a brief discussion of the human immune system, and compare and contrast it with the Netflix Simian Army.

* Compare some well known technologies you use against the NIST National Vulnerability Database. Are there any issues? How would you fix them?

* Using infrastructure as code, develop a demonstration environment employing some member of the xref:simian-army[Simian Army].


===== Further reading

*Books*

* Shon Harris, https://www.goodreads.com/book/show/671038.CISSP_All_in_One_Exam_Guide[CISSP All-in-One Exam Guide]
*  Robert Moeller, https://www.goodreads.com/book/show/19611256-executive-s-guide-to-it-governance[Executive's Guide to IT Governance: Improving Systems Processes with Service Management, COBIT, and ITIL]
* ISACA, https://www.goodreads.com/book/show/19435104-cobit-5-framework[COBIT 5 Framework]
* Gene Kim et al, https://www.goodreads.com/book/show/17255186-the-phoenix-project[The Phoenix Project]
* Scott Ambler and Mark Lines, https://www.goodreads.com/book/show/18910257-disciplined-agile-delivery?from_search=true[Disciplined Agile Delivery: A Practitioner's Guide to Agile Software Delivery in the Enterprise], Chapter 20: Governing Disciplined Agile Teams

*Articles*

* Wikipedia on https://en.wikipedia.org/wiki/Corporate_governance[Corporate governance]
* http://www.zdnet.com/article/the-top-10-it-disasters-of-all-time-5000177729/[The top 10 IT disasters of all time]
* https://technet.microsoft.com/en-us/magazine/2006_09.businessofit.aspx
* http://searchdatamanagement.techtarget.com/definition/compliance
* http://continuousdelivery.com/2013/08/risk-management-theatre/
* http://www.sonatype.org/nexus/2015/11/13/did-you-wake-up-to-an-alert-about-the-java-deserialization-vulnerability[Did you wake up to an alert about the Java deserialization vulnerability]

* http://www.slideshare.net/realgenekim/keeping-the-auditor-away[Keeping the Auditor Away: DevOps Audit Compliance Case Studies]

* http://www.aicpa.org/interestareas/frc/assuranceadvisoryservices/downloadabledocuments/asec_whitepapers/risk_technology.pdf[Technology in Risk Management]

*Videos*

* https://www.youtube.com/watch?v=_r67ZvMC3d8[Brian Barnier, What Works When Monitoring Risk]

*Professional*

* http://www.coso.org/documents/990025P_Executive_Summary_final_may20_e.pdf[COSO (Treadway Commission) Internal Control — Integrated Framework (Executive Summary)]
* http://www.isaca.org[ISACA - producer of COBIT]
* http://www.corporatecompliance.org/[Compliance and Ethics Association]
