==== Coordination

*** Trad PM
*** clinical terminology (Reinertsen)
*** protecting team (pigs & chickens)
*** release train??
*** Flow & variability
*** chatops / common ground
*** RACI
*** risk


shared resources and services
global CoD - process eval


** internal market econ
** the cost accounting problem




===== Cost accounting and chargeback
IT is often consumed as a "shared service" which requires internal financial transfers. What does this mean?

Here is a traditional example. An IT group purchases a mainframe computer for $1,000,000. This mainframe is made available to various departments who are charged for it. Because the mainframe is a shared resource, it can run multiple workloads simultaneously. For the year, we see the following usage:

* 30% Accounting
* 40% Sales operations
* 30% Supply chain

In the simplest direct allocation model, the departments would pay for the portion of the mainframe that they used. But things always are more complex than that.

* What if the mainframe has excess capacity? Who pays for that?
* What if Sales Operations stops using the mainframe? Do Accounting and Supply Chain have to make up the loss? What if Accounting decides to stop using it because of the price increase? (In public utilities, this is known as a http://www.greentechmedia.com/articles/read/this-is-what-the-utility-death-spiral-looks-like["death spiral."])
* The mainframe requires power, floor space, and cooling. How are these incorporated into the departmental charges?
* Ultimately, the Accounting organization (and perhaps Supply Chain) are back office cost centers as well. Does it make sense for them to be allocated revenues from company income, only to have those revenues then re-directed to the IT department?

Historically, *cost accounting* has been the basis for much IT financial management (see e.g. ITIL Service Strategy, <<TSO2011a>>, p.202; <<Quinlan2003>>). Such approaches traditionally seek _full absorption_ of unit costs; that is, each "unit" of inventory ideally represents the total cost of all its inputs: materials, labor, and overhead such as machinery and buildings.

anchor:cost-accounting-def[]

NOTE: *Cost accounting* is defined as "the techniques for determining the costs of products, processes, projects, etc. in order to report the correct amounts on the financial statements, and assisting management in making decisions and in the planning and control of an organization  . . . For example, cost accounting is used to compute the unit cost of a manufacturer's products in order to report the cost of inventory on its balance sheet and the cost of goods sold on its income statement. This is achieved with techniques such as the allocation of manufacturing overhead costs and through the use of process costing, operations costing, and job-order costing systems. <<Accounting2016>>

In IT/digital service organizations, there are three basic sources of cost: "cells, atoms, and bits." That is:

* People (i.e. their time)
* Hardware
* Software

However, these are "direct" costs - costs that for example a product or project manager can see in their full amount.

Another class of cost is "indirect." The IT service might be charged $300 per square foot for data center space. This provides access to rackspace, power, cooling, security, and so forth.  This charge represents the bills the Facilities organization in turn receives from power companies, mechanicals vendors, security services, and so forth - not to mention the mortgage!

Finally, the service may depend on other services. Perhaps instead of a dedicated database server, the service subscribes to a database *service* that gives them a high-performance relational database, but where they do not pay directly for the hardware, software, and support services the database is based on. Just to make things more complicated, the services might be external (public Cloud) or internal (private Cloud or other offerings).

Those are the major classes of cost. But how do we understand the "unit of inventory" in an IT services context? A variety of concepts can be used, depending on the service in question:

* Transactions
* Users
* Network ports
* Storage (e.g. gigabytes of disk)

In internal IT organizations (see xref:consumer-customer-sponsor["Defining consumer, customer, and sponsor"]) this cost accounting is then used to transfer funds from the budgets of consuming organizations to the IT budget. Sometimes this is done via simple allocations (Marketing pays 30%, Sales pays 25%, etc) and sometimes this is done through more sophisticated approaches, such as defining unit costs for services.

For example, the fully absorbed unit cost for a customer account transaction might be determined to be $0_25; this ideally represents the total cost of the hardware, software, and staff divided by the expected transactions. Establishing the models for such costs, and then tracking them, can be a complex undertaking, requiring correspondingly complex systems.

IT managers have known for years that overly detailed cost accounting approaches can result in consuming large fractions of IT resources. As AT&T financial manager John McAdam noted:

"Utilizing an excessive amount of resources to capture data takes away resources that could be used more productively to meet other customer needs. Internal processing for IT is typically 30-40% of the workload. Excessive data capturing only adds to this overhead cost." <<McAdam2003>>

There is also the problem that unit costing of this nature creates false expectations. Establishing an internal service pricing scheme implies that if the utilization of the service declines, so should the related billings. But if

. the hardware, software, and staff costs are already sunk, or relatively inflexible and
. the IT organization is seeking to fully recover costs

the per-transaction cost will simply have to increase if the number of transactions goes down. James R. Huntzinger discusses the problem of excess capacity distorting unit costs, and states "it is an absolutely necessary element of accurate representation of the facts of production that some provisions be made for keeping the cost of wasted time and resources separate from normal costs" <<Huntzinger2007>>. Approaches for doing this will be discussed below.


===== Internal market economics
[quote, Womack and Jones, Lean Thinking]
value stream and product line managers, like so much in the lean world, are "fractal."
[quote, Jeremy Hope and Robin Fraser, Beyond Budgeting Questions and Answers]
Coordinate cross-company interactions through “market-like” forces.

IT has long been viewed as a "business within a business." In the internal market model, services consume other services, ad infinitum <<Meyer2013>>. Sometimes the relationship is hierarchical (an application team consuming infrastructure services) and sometimes it is peer to peer (an application team consuming another's services, or a network support team consuming email services, which in turn require network services.)

The increasing sourcing options including various Cloud options make it more and important that internal digital services be comparable to external markets. This in turn puts constraints on traditional IT cost recovery approaches, which often result in charges with no seeming relationship to reasonable market prices.

There are several reasons for this. One commonly cited reason is that internal IT costs include support services, and therefore cannot fairly be compared to simple retail prices (e.g. for a computer as a good.)

Another, more insidious reason is the rolling in of unrelated IT overhead to product prices. We have quoted James Huntzinger's work above in various places on this topic. Dean Meyer has elaborated this topic in greater depth from an IT financial management perspective, calling for some organzational "goods" to be funded as either Ventures (similar to above discussion) or "subsidies" (for enterprise-wide benefits such as technical standardization) <<Meyer2013>>, p.92.

As discussed above, a particularly challenging form of IT overhead is excess capacity. The saying "the first person on the bus has to buy the bus" is often used in IT shared services, but is problematic. A new, venture-funded startup cannot operate this way - expecting the first few customers to fully fund the investment! Nor can this work in an internal market, unless heavy handed political pressure is brought to bear. This is where internal venture funding is required.

Meyer presents a sophisticated framework for understanding and managing an internal market of digital services. This is not a simple undertaking; for example, correctly setting service prices can be surprisingly complex.
