==== Defining the organization

There are many different ways we can apply these ideas of traditional functional organizing versus product-oriented organizing, and features versus components. How does one begin to decide these questions? As a digital professional in a scaling organization, you need to be able to lead these conversations. The cross-functional, diverse, collaborative team is a key unit of value in the digital enterprise, and its performance needs to be nurtured and protected.

.Pigs versus chickens in Scrum
****
A well known theme from Scrum is the idea of "pigs versus chickens." It comes from a (not very funny) joke:

_A chicken says to a pig, "Hey pig, let's start a restaurant."_

_Pig: "I'm not sure, what would we call it?"_

_Chicken: "How about, 'Ham and Eggs'?"_

_Pig: "No thanks, I'd be committed, but you'd only be involved."_

Regardless of the humor, there's an important point here: when teams are fully committed, fully accountable for delivering value, the value they deliver increases. When work is xref:org-continuum[flowing across functional areas], each area is just "involved" and only the project manager may be "committed" (if he or she even is). When we flip the organization to a value-centric model, xref:multi-tasking[multi-tasking] decreases and commitment increases.

We discuss this here in the team of teams section, as the assumption in Part I and Part II is that everyone was committed because it was a small, single-team organization.
****

Abbott and Fisher  suggest the following criteria when considering organizational structures <<Abbott2015>>, p 12:

• How easily can I add or remove people to/from this organization? Do I need to add them in groups, or can I add individual people?
• Does the organizational structure help or hinder the development of metrics that will help measure productivity?
• Does the organizational structure allow teams to own goals and feel empowered and capable of meeting them?
• Which types of conflict will arise, and will that conflict help or hinder the mission of the organization?
• How does this organizational structure help or hinder innovation within my company?
• Does this organizational structure help or hinder the time to market for my products?
• How does this organizational structure increase or decrease the cost per unit of value created?
• Does work flow easily through the organization, or is it easily contained within a portion of the organization?

===== Team persistence

[quote, Joseph Flahiff]
The traditional approach is that we have work and we bring "the right people" to the work. To be nimble -- to have organizational agility -- we have to have great teams of people and bring the work to the team <<Flahiff2016>>.

Team persistence is a key question. The practice in project-centric organizations has been temporary teams, that are created and broken down on an annual or more frequent basis. People "rolled on" and "rolled off" of projects regularly in the common xref:heavyweight-pm[heavyweight project management] model. Often, contention for resources resulted in project fractional allocation, as in "you are 50% on Project A and 25% on Project B" which could be challenging for individual contributors to manage. With team members constantly coming and going, developing a deep, collective understanding of the work was difficult. Hard problems benefit from team stability. Teams develop both a deeper rational understanding of the problem, as well as emotional assets such as xref:psych-safety[psychological safety]. Both are disrupted when even one person on a team changes. Persistent teams of committed individuals also (in theory) reduce destructive xref:multi-tasking[multi-tasking]. 

.Author's note
****
As of fall 2016, the trend towards persistent, product-centric teams and away from continually changing project-based teams is noticeable in the Minneapolis/St. Paul area. A related phenomenon is multiple anecdotes of companies abandoning Project Management Offices. More on project management in Chapter 8.
****
