
==== Defining Information Technology

anchor:what-is-IT[]

===== What is IT, anyways?

We’ve started this book in the previous section by providing an example of digital or IT value, without much discussion of how it is delivered. This is deliberate. But what is IT (Information Technology), anyways?

* The computers? The networks?
* The people who run them?
* That organization under a Chief Information Officer that loves to say “no” and is always slow and expensive?

None of these are how this book defines “IT.” Although this is not a technical book on computer science or software engineering, the intent is that it reflects and is compatible with foundational principles.

“Information technology” is ultimately based on the work of https://en.wikipedia.org/wiki/Claude_Shannon[Claude Shannon], https://en.wikipedia.org/wiki/Alan_Turing[Alan Turing], https://en.wikipedia.org/wiki/Alonzo_Church[Alonzo Church], https://en.wikipedia.org/wiki/John_von_Neumann[John von Neumann], and the other pioneers who defined the central problems of https://en.wikipedia.org/wiki/Information_theory[information theory], https://en.wikipedia.org/wiki/Digital_electronics[digital logic],  https://en.wikipedia.org/wiki/Computability[computability], and https://en.wikipedia.org/wiki/Computer_architecture[computer architecture].

anchor:IT-as-function[]

Additionally, as an organizational function, information technology also draws on organizational theory, systems theory, human factors and psychology, and more recent concepts such as design thinking, among many other areas. Discussions of “information technology” become contentious because some think of the traditional organization, while others think of the general problem area. IT has a long history as a corporate function, a single hierarchy under a powerful Chief Information Officer. This model has had its dysfunctions, including a longstanding reputation for being slow and expensive. Often, when one encounters the term “IT,” the author using the term is referring to this organizational tradition.

*We are less interested in the future of IT as a distinct organizational structure. There are many different models, from fully centralized to fully embedded.* Organizational structure will be discussed in Part III.

ifdef::aitm-pdf[]
marginnote!Digital management uses many different organizational structures.!marginnote
endif::aitm-pdf[]

For this book, we define “Information technology” in terms of its historic origins. We look to IT’s common origins in automating the laborious and error prone processes of computation, through the application of digital logic technologies based on information transmission.

Regardless of organizational form or delivery methods, IT is defined by these origins. And there are notable common threads throughout this problem domain: the fragility and complexity of these systems, the need for layered abstractions in their management, and more.

It does not matter if the application developers ultimately report up through the CIO, the CMO, the CFO, or the COO. Their daily experience remains largely the same. The dynamics of their management remain the same. Executives who seek to take control of IT so they can “remove that old bureaucracy” are well advised to be cautious; the bureaucracy emerged for a reason. More on this in subsequent chapters.

anchor:digital-transformation[]


===== IT and digital transformation
[quote, Nicholas Carr]
IT doesn't matter. cite:[Carr2003]

[quote, Mark Andreessen]
Software is eating the world. cite:[Andreessen2011]

[quote, Jeff Sussna, Designing Delivery]
The digital realm is infusing the physical realm, like tea in hot water. cite:[Sussna2015]

IT increasingly permeates business operations and social interactions. The breadth and depth of IT support for virtually all domains of society continues to expand. Lately, this is known as digital transformation cite:[Westerman2014].

The role of information technology seems critical to society and the economy, but there are various points of view. Nicholas Carr, in his controversial _Harvard Business Review_ article "IT Doesn't Matter," recognized that IT was becoming commoditized in an important sense cite:[Carr2003]. As Cloud providers started to offer utility-style computing, the choice of particular vendors of computers was no longer strategic. Looking to history, Carr argued that just as businesses no longer have “Vice Presidents for Electricity,” so businesses no longer need Chief Information Officers or dedicated IT departments.

NOTE: A "commodity" product is one that is offered from a variety of suppliers, with little or no difference between their offerings. Commodity products tend to compete on price, not on differences in features. Wheat is a commodity. Sports cars are not. "Commoditization" is the process by which products that used to compete by being different, increasingly compete on price.

Carr has insight -- there is no question IT is becoming pervasive -- but he ultimately reflects a narrow view of what “IT” is. If “IT” were merely computation at the lowest level -- just shuffling bits of information around, doing a little math -- then perhaps it could be embedded throughout a business like electricity.

But IT has emergent aspects that are not comparable to electrical power. As it pervades all dimensions of business operations, it brings its concerns with it: complexity, fragility, and the skills required to cope with them.

One watt of electrical power is like any other watt of electrical power, and can usefully be seen as a commodity. We can use it to run toasters, hair dryers, or industrial paint mixers, and there is little concern (beyond supply and demand management) that the consumption of power by the paint mixer will affect the toaster.  It's also true that one cycle of computing, in a certain sense, is like any other cycle. But information technology systems interact with each other in surprising and unpredictable ways, orders of magnitude more complex than electrical power grids. (This is not to imply the modern electrical grid is a simple system!)

IT also radically transforms industries: from retail to transportation to manufacturing to genetics. Applied software-centric IT is unleashing remarkable economic disruption.

A lawyer may depend on a cell phone, and (in keeping with Carr) beyond its provision as a commodity service, needs little else to deliver the legal strategies a firm needs. A graphic designer may use computerized graphic tools, but these have become relatively standardized and commoditized in the past twenty years, and probably are not a source of competitive advantage in the quest for new marketing clients.

On the other hand, consider a text analytic algorithm that replaces thousands of paralegals, resulting in order-of-magnitude more accurate legal research in a fraction of cost and time. This *is* strategic and disruptive to the legal community. A superior supply chain algorithm, and the ability to improve it on an ongoing basis, may indeed elevate a logistics firm’s performance above competitors. In cases like these -- and they seem to be increasing -- IT matters very much. The annual State of DevOps research finds that "Firms with high-performing IT organizations were twice as likely to exceed their profitability, market share, and productivity goals." cite:[Forsgren2014]

In the digitally transforming economy, traditional “back office” IT organizations find themselves called on to envision, develop, and support market-facing applications of IT. And what starts with one market-facing use case can quickly expand into entire portfolios.  It is such cases that are of particular concern in this book. Ultimately, it is possible that IT is the *most* strategic capability an organization can invest in. As Diomidis Spinellis, editor in chief of _IEEE Software_  notes cite:[Spinellis2015],

"other industries are also producing what’s in effect software (executable knowledge) but not treating it as such … Although many industries have developed their own highly effective processes over the years, software engineering maintains an essential advantage. It has developed methods and tools that let even small teams manage extremely high complexity … This advantage is important because the complexity in non-software activities is also increasing inexorably … [T]he time has come to transform our world … by giving back to science and technology the knowledge software engineering has produced."

This ability to manage complexity, to turn tacit into explicit and formalize the previously unstructured, is an essential aspect of digital transformation.

===== Defining "IT"

So, how do we define an IT problem, as opposed to other kinds of business problems? An IT problem is any problem where you are primarily constrained by your capability and understanding of IT.

* If you need computer scientists or engineers who understand the fundamentals of information theory and computer science, you are doing IT.
* If you need people who understand when your information-centric problems might need to be referred to such theorists and engineers, you are likely doing IT.
* If you need people who are skilled in building upon those fundamentals, and operating technical platforms derived from them (such as programming languages, general purpose computers, and network routers), you are doing IT.

Regardless of whether IT is housed under a traditional CIO, an operations capability, a Chief Marketing Officer, or a “line of business”, when it is critical to operations certain concerns inevitably follow:

* Requirements (i.e. your intent for IT)
* Sourcing and provisioning
* IT-centric product design and construction
* Configuration and change management
* Support
* Improvement

Executives who take control of information technology in hopes of making it more "agile" are often surprised to find that these concerns were not mere bureaucracy, but instead had well grounded origins in past failures. Ignoring these lessons is perilous.

And yet, the traditional, process-heavy IT organization does seem dysfunctional from a business point of view: a central theme of this book.
