anchor:ops-mgmt[]

=== Chapter 6: Operations Management

ifdef::collaborator-draft[]

****
*Collaborative*

Status: This section is comprehensively rewritten to "draft 1.5" as of 2016-11-21.

 At this point, the primary needs are for expert reviews in terms of curation choices, and also contributions of case studies.

 include::../../../collab-links.adoc[]

****

endif::collaborator-draft[]


ifdef::instructor-ed[]

****
_Instructor's note_

Although this is entitled "operations management" it also brings in infrastructure engineering at a higher level, assuming that the product is continuing to scale up. Chapter 12 will revisit infrastructure engineering and operations in terms of the most highly scaled and complex Web-scale systems.

Thus, Chapters 2, 6, and 12 constitute a sort of "infrastructure and operations" track within the book.

****
endif::instructor-ed[]

==== Introduction

As your product gains more use, you find that running it inevitably becomes a distinct concern from building it. For all their logic, computers are still surprisingly unreliable. Servers running well tested software may remain "up" for weeks, and then all of a sudden hang and have to be rebooted. Sometimes it's clear why (for example, a log file filled up that no-one expected) and in other cases there just is no explanation.

Engineering and operating complex IT-based distributed systems is a significant challenge. Even with xref:infracode[infrastructure as code] and automated xref:continuous-delivery[continuous delivery] pipelines, operations as a class of work is distinct from software development per se. The work is relatively more interrupt-driven, as compared to the "heads-down" focus of developing new features. Questions of scalability, performance, caching, load balancing, and so forth usually become apparent first through feedback from the operations perspective -- whether or not you have a formal operations "team."

We are still just one team with one product, but as we enter this last chapter of Part II, the assumption is that we have considerable use of our product. With today's technology, correctly deployed and operated, even a small team can support large workloads. This does not come easily, however. Systems must be monitored and specific techniques employed for managing their performance and capacity. We will also revisit the topic of configuration management at a more advanced level.

We discussed the evolution of infrastructure in xref:chapter-2[Chapter 2] and applications development in xref:chapter-3[Chapter 3], and will continue to build on those foundations. The practices of Change, Incident, and Problem management have been employed in the industry for decades and are important foundations for thinking about operations. The concept of Site Reliability Engineering is an important new discipline emerging from the practices of companies such as Google and Facebook. We will examine its principles and practices.

===== Chapter 6 outline

* Defining "operations"

* Event management and monitoring

* Capacity and performance management

* Incidents, disasters, and everything in between

* Advanced topics
** Ops -> dev feedback
** Configuration
** Control
** Web-scale IT


===== Chapter 6 learning objectives

* Distinguish kinds of work, especially operational vs development
* Understand basics of monitoring, event management and impact
* Describe the basics of change and incident management
* Describe operational feedback into product design & the kinds of concerns it raises
* Describe impact and dependency analysis and why it is important
