
==== Designing software for operations

[quote, Limoncelli/Chalup/Hogan]
Building a scalable system does not happen by accident.

Review Allspaw, Limoncelli, Beyer, read Nygaard & Abbott

 [to be written. Reference Nygard's Release IT; SNMP; DMTF. See also http://blog.softwareoperability.com/.]

 broad and fast-moving topic. not possible to go into depth here.

 instructor's note: consider accompanying this book w/Limoncelli or Allspaw.

 visibility @ scale, introspection

 http://www.joelonsoftware.com/articles/fog0000000069.html

 The more complex the system, the more difficult it is to have an accurate mental model.

Limoncelli, Thomas A.; Chalup, Strata R.; Hogan, Christina J.. The Practice of Cloud System Administration: Designing and Operating Large Distributed Systems, Volume 2 (p. 11). Pearson Education. Kindle Edition.

 basic logging - xref to monitoring

 basic distributed architecture
  load balancing & redundancy
  distributed state
  reverse proxy
  CAP & caching
  loose coupling
  latency numbers

hardware issues - hot swapping etc

text-based configuration as far as possible

graceful start/stop

80/20 rule for operational feedback into product backlog - prevents queue starvation - Limoncelli2014 2.2.2

AKF scaling cube

operational software practices

logging
crashes & panics
