
anchor:IT-lifecycles[]

=== Special section: The IT lifecycles

We've discussed products and the various ways digital organizations deliver them, from simple work management to more sophisticated project and process management approaches. Now, we need to refine our understanding of the products themselves and how they are managed.

We previously discussed the relationship between xref:feature-v-component[feature versus component teams] in chapter 4. In chapter 9, we touched on the idea of xref:shared-services[shared services] teams.  Both of these ideas are now expanded into what is called the "four lifecycle model."

The four lifecycle model was first documented in <<Betz2011a>>. The four lifecycles are:

* The Application Service lifecycle
* The Infrastructure Service lifecycle
* The Asset lifecycle
* The Technology Product lifecycle

First, bear in mind that services are equivalent to products. A digital product is, in general, delivered as a service.

Each of these lifecycles reflects the existence of a significant concept, that is managed over time, as a portfolio. (More on IT portfolio management practices in Chapter 10.)

An *Application Service* is a business or market-facing product, consumed by people whose primary activities are *not* defined by an interest in xref:what-is-IT[information technology]: for example, a bank customer lookiing up her account balance, or an Accounts Payable systems operator. In terms of "feature versus component," the concept of Application is more aligned to "feature."

The *Application Service Lifecycle* is the end to end existence of such a systems, from xref:service-lifecycle[idea to retirement]. In general, the realization such a system is needed originates *externally* to the IT capability (regardless of its degree of centralization.)
