
anchor:IT-lifecycles[]

=== Special section: The IT lifecycles

ifdef::collaborator-draft[]

****
*Collaborative*

 Status: This section is in active development as of Jun 24 2016. Expect volatility.

include::../../../collab-links.adoc[]

****

endif::collaborator-draft[]

We've discussed products and the various ways digital organizations deliver them, from simple work management to more sophisticated project and process management approaches. Now, we need to refine our understanding of the products themselves and how they are managed.

We previously discussed the relationship between xref:feature-v-component[feature versus component teams] in chapter 4. In chapter 9, we touched on the idea of xref:shared-services[shared services] teams.  Both of these ideas are now expanded into what is called the "four lifecycle model."

The four lifecycle model was first documented in <<Betz2011a>>. The four lifecycles are:

* The Application Service lifecycle
* The Infrastructure Service lifecycle
* The Asset lifecycle
* The Technology Product lifecycle

Each of these lifecycles reflects the existence of a significant concept, that is managed over time, as a portfolio. (More on IT portfolio management practices in Chapter 10.)

First, bear in mind that services are equivalent to products. Digital value is usually delivered as a service, and therefore shares standard service characteristics from academic marketing, including the idea that services are produced and consumed simultaneously (e.g. an account lookup) and are perishable (a computer's idle time cannot be recovered). 

The first two concepts (Application and Infrastructure Service) below reflect these characteristics; the second two (Asset and Technology Product) do not.

An *Application Service* is a business or market-facing product, consumed by people whose primary activities are *not* defined by an interest in xref:what-is-IT[information technology]: for example, a bank customer lookiing up her account balance, or an Accounts Payable systems operator. In terms of "feature versus component," the concept of Application is more aligned to "feature."

The *Application Service Lifecycle* is the end to end existence of such a systems, from xref:service-lifecycle[idea to retirement]. In general, the realization such a system is needed originates *externally* to the IT capability (regardless of its degree of centralization.)

An *Infrastructure Service* is, by contrast and as xref:what-is-IT-infrastructure[previously discussed], a digital or IT service primarily of interest to other digital or IT services/products. Its lifecycle is similar to that of the application service, except that the user is some other IT service.

(Note that more recent academic theory is moving away from these definitions, but they are still useful as initial criteria to describe a service versus a good.)

Note that in terms of our anchor:shared-services[service definition discussion], the above lifecycle concepts are service *systems*. The lifecycle of service offerings is a business lifecycle having more to do with go to market strategy on the part of the firm. We covered this to some extent in Chapter 4 and will revisit it in Chapter 12.

An *Asset* is a valuable, tangible investment of organizational resources that is tracked against loss or misuse, and optimized for value over time.
